/**
 * Translation slice for fileViewer.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to fileViewer's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface FileViewerTranslation {
    default: { title: string; description: string };
    doc: {
        installation: {
            title: string;
            commandTab: string;
            manualTab: string;
            manualStep1: string;
            manualStep2: string;
            manualStep3: string;
        };
        usage: { title: string; body: string };
        composition: { title: string; body: string };
        examples: {
            title: string;
            default: { title: string; description: string };
        };
        definedBehaviour: {
            title: string;
            intro: string;
            verifiedBy: string;
            statements: {
                imageViewer: string;
                image360Viewer: string;
                videoViewer: string;
                dashHls: string;
                nameFallback: string;
                customFallback: string;
            };
        };
        rtl: { title: string; body: string };
        apiReference: { title: string; intro: string };
    };
}

export const fileViewerEn: FileViewerTranslation = {
    default: { title: `Default`, description: `Bundled landscape image renders through ImageViewer. Swap the URL, name, or MIME type to exercise different code paths.` },
    doc: {
        installation: { title: `Installation`, commandTab: `Command`, manualTab: `Manual`, manualStep1: `Install the following dependencies:`, manualStep2: `Copy and paste the following code into your project.`, manualStep3: `Update the import paths to match your project setup.` },
        usage: { title: `Usage`, body: `<FileViewer> takes a resolved src URL plus name and mimeType, and renders the appropriate built-in viewer. URL resolution (auth, signed URLs, etc.) is the consumer's responsibility.` },
        composition: { title: `Composition`, body: `FileViewer dispatches on mimeType: image/* → ImageViewer (or Image360Viewer when is360 is set); video/* and DASH / HLS manifests → VideoViewer. Unknown types fall back to the file name or a custom fallback node.` },
        examples: { title: `Examples`, default: { title: `Default`, description: `Preview a bundled image. Edit any of the three fields to inspect different render paths.` } },
        definedBehaviour: {
            title: `Defined behaviour`, intro: `Statements describing how <FileViewer> is expected to behave, each linked to the test that verifies it.`, verifiedBy: `verified by`,
            statements: {
                imageViewer: `Renders ImageViewer for image/* without is360.`,
                image360Viewer: `Renders Image360Viewer for image/* when is360 is true.`,
                videoViewer: `Renders VideoViewer for any video/* mime type.`,
                dashHls: `Renders VideoViewer for DASH and HLS manifest mime types.`,
                nameFallback: `Falls back to the name when no viewer matches.`,
                customFallback: `Renders the explicit fallback when provided and nothing matches.`
            }
        },
        rtl: { title: `RTL`, body: `Inner viewers follow their own RTL behaviour; the wrapper itself is layout-neutral.` },
        apiReference: { title: `API Reference`, intro: `Props accepted by <FileViewer>.` }
    }
};

export const fileViewerDe: FileViewerTranslation = {
    default: { title: `Standard`, description: `Mitgeliefertes Landschaftsbild wird durch den ImageViewer gerendert. Vertausche URL, Name oder MIME-Typ, um andere Renderpfade zu testen.` },
    doc: {
        installation: { title: `Installation`, commandTab: `Befehl`, manualTab: `Manuell`, manualStep1: `Installiere die folgenden Abhängigkeiten:`, manualStep2: `Kopiere den folgenden Code in dein Projekt.`, manualStep3: `Passe die Import-Pfade an deine Projektstruktur an.` },
        usage: { title: `Verwendung`, body: `<FileViewer> nimmt eine bereits aufgelöste src-URL plus name und mimeType entgegen und rendert den passenden internen Viewer. URL-Auflösung (Auth, signierte URLs etc.) ist Aufgabe des Konsumenten.` },
        composition: { title: `Komposition`, body: `FileViewer wählt anhand des mimeType: image/* → ImageViewer (bzw. Image360Viewer, wenn is360 gesetzt ist); video/* sowie DASH-/HLS-Manifeste → VideoViewer. Unbekannte Typen fallen auf den Dateinamen oder einen eigenen Fallback zurück.` },
        examples: { title: `Beispiele`, default: { title: `Standard`, description: `Zeige ein mitgeliefertes Bild. Ändere eines der drei Felder, um verschiedene Renderpfade zu prüfen.` } },
        definedBehaviour: {
            title: `Definiertes Verhalten`, intro: `Aussagen darüber, wie sich <FileViewer> verhalten soll — jede verlinkt mit dem Test, der sie verifiziert.`, verifiedBy: `verifiziert durch`,
            statements: {
                imageViewer: `Rendert ImageViewer für image/* ohne is360.`,
                image360Viewer: `Rendert Image360Viewer für image/* wenn is360 gesetzt ist.`,
                videoViewer: `Rendert VideoViewer für jeden video/*-MIME-Typ.`,
                dashHls: `Rendert VideoViewer für DASH- und HLS-Manifest-MIME-Typen.`,
                nameFallback: `Fällt auf den Namen zurück, wenn kein Viewer passt.`,
                customFallback: `Rendert den explizit übergebenen Fallback, wenn nichts passt.`
            }
        },
        rtl: { title: `RTL`, body: `Innere Viewer folgen ihrem eigenen RTL-Verhalten; der Wrapper selbst ist layout-neutral.` },
        apiReference: { title: `API-Referenz`, intro: `Props, die <FileViewer> akzeptiert.` }
    }
};
