// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserToBeCreated } from "./UserToBeCreated";

export interface CreateUserRequestBody { users: Array<UserToBeCreated>, }