// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilezPermissionAcl } from "./FilezPermissionAcl";

export interface FilezPermissionResource<T> { acl: FilezPermissionAcl<T> | null, ribston: string | null, }