// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserGroupVisibility } from "./UserGroupVisibility";

export interface UpdateUserGroupInfosRequestField { name: string | null, visibility: UserGroupVisibility | null, permission_ids: Array<string> | null, }