// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UsageLimits { max_storage: number, used_storage: number, max_files: number, used_files: number, max_bandwidth: number, used_bandwidth: number, }