/**
 * Translation slice for radioGroup.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to radioGroup's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface RadioGroupTranslation {
    default: { title: string; description: string };
    disabledOption: { title: string; description: string };
    doc: {
        installation: {
            title: string;
            commandTab: string;
            manualTab: string;
            manualStep1: string;
            manualStep2: string;
            manualStep3: string;
        };
        usage: { title: string; body: string };
        composition: { title: string; body: string };
        examples: {
            title: string;
            default: { title: string; description: string };
            disabledOption: { title: string; description: string };
        };
        definedBehaviour: {
            title: string;
            intro: string;
            verifiedBy: string;
            statements: {
                rendersRadios: string;
                roleRadiogroup: string;
                defaultValueOnMount: string;
                firesOnValueChange: string;
                fullyControllable: string;
                disabledNoSwitch: string;
            };
        };
        rtl: { title: string; body: string };
        apiReference: { title: string; intro: string };
    };
}

export const radioGroupEn: RadioGroupTranslation = {
    default: {
        title: `Controlled selection`,
        description: `Three options, one selected — onValueChange fires with the new value when the user picks.`
    },
    disabledOption: {
        title: `Disabled option`,
        description: `Mark a single <RadioGroupItem disabled> to lock it out of selection; the rest of the group remains interactive.`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Command`,
            manualTab: `Manual`,
            manualStep1: `Install the following dependencies:`,
            manualStep2: `Copy and paste the following code into your project.`,
            manualStep3: `Update the import paths to match your project setup.`
        },
        usage: {
            title: `Usage`,
            body: `<RadioGroup> wraps Radix RadioGroup. Each <RadioGroupItem value> must be unique inside the group.`
        },
        composition: {
            title: `Composition`,
            body: `Wrap each item inside a <Label> for accessible labelling. Mark individual items disabled or disable the whole group at the root.`
        },
        examples: {
            title: `Examples`,
            default: {
                title: `Controlled selection`,
                description: `Three options with onValueChange.`
            },
            disabledOption: {
                title: `Disabled option`,
                description: `One item disabled.`
            }
        },
        definedBehaviour: {
            title: `Defined behaviour`,
            intro: `Statements describing how <RadioGroup> is expected to behave, each linked to the test that verifies it.`,
            verifiedBy: `verified by`,
            statements: {
                rendersRadios: `Renders each item as a radio.`,
                roleRadiogroup: `Uses role="radiogroup" on the wrapper.`,
                defaultValueOnMount: `Reflects defaultValue on first mount.`,
                firesOnValueChange: `Fires onValueChange when an item is clicked.`,
                fullyControllable: `Is fully controllable via value + onValueChange.`,
                disabledNoSwitch: `Does not switch to a disabled item.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `Under dir="rtl" the radio indicator and its label flip; arrow-key navigation mirrors so Left/Right step to the visually-adjacent item.`
        },
        apiReference: {
            title: `API Reference`,
            intro: `Props accepted by <RadioGroup> and <RadioGroupItem>.`
        }
    }
};

export const radioGroupDe: RadioGroupTranslation = {
    default: {
        title: `Kontrollierte Auswahl`,
        description: `Drei Optionen, eine ausgewählt — onValueChange feuert mit dem neuen Wert beim Klick.`
    },
    disabledOption: {
        title: `Option deaktiviert`,
        description: `Ein einzelnes <RadioGroupItem disabled> aus der Auswahl ausschließen; der Rest der Gruppe bleibt interaktiv.`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Befehl`,
            manualTab: `Manuell`,
            manualStep1: `Installiere die folgenden Abhängigkeiten:`,
            manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
            manualStep3: `Passe die Importpfade an dein Projekt an.`
        },
        usage: {
            title: `Verwendung`,
            body: `<RadioGroup> kapselt Radix RadioGroup. Jedes <RadioGroupItem value> muss in der Gruppe eindeutig sein.`
        },
        composition: {
            title: `Komposition`,
            body: `Jedes Item in einem <Label> einwickeln für barrierefreie Beschriftung. Einzelne Items oder die ganze Gruppe deaktivieren.`
        },
        examples: {
            title: `Beispiele`,
            default: {
                title: `Kontrollierte Auswahl`,
                description: `Drei Optionen mit onValueChange.`
            },
            disabledOption: {
                title: `Option deaktiviert`,
                description: `Ein Item deaktiviert.`
            }
        },
        definedBehaviour: {
            title: `Festgelegtes Verhalten`,
            intro: `Aussagen darüber, wie sich <RadioGroup> verhalten soll, jeweils mit Verweis auf den Test.`,
            verifiedBy: `geprüft durch`,
            statements: {
                rendersRadios: `Rendert jedes Item als radio.`,
                roleRadiogroup: `Setzt role="radiogroup" auf den Wrapper.`,
                defaultValueOnMount: `Übernimmt defaultValue beim ersten Mount.`,
                firesOnValueChange: `Feuert onValueChange beim Klick auf ein Item.`,
                fullyControllable: `Ist vollständig steuerbar via value + onValueChange.`,
                disabledNoSwitch: `Wechselt nicht zu einem deaktivierten Item.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `Unter dir="rtl" spiegeln Indikator und Label; Pfeil-Navigation dreht sich, sodass Links/Rechts zum visuell benachbarten Item führen.`
        },
        apiReference: {
            title: `API-Referenz`,
            intro: `Props, die <RadioGroup> und <RadioGroupItem> akzeptieren.`
        }
    }
};
