/**
 * Translation slice for compass.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to compass's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface CompassTranslation {
  default: { title: string; description: string };
  markers: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
      markers: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        defaultReadout: string;
        normalisesNegative: string;
        normalisesLarge: string;
        mapsCardinal: string;
        cardinalsByDefault: string;
        readoutNullHides: string;
        customReadout: string;
        rendersMarkers: string;
        hideCardinals: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const compassEn: CompassTranslation = {
  default: {
    title: `Slider-driven`,
    description: `Drag the slider 0-360° to change the heading; the bar scrolls so the centre marker stays pinned to the current bearing.`,
  },
  markers: {
    title: `With waypoints`,
    description: `Pass markers={[{ bearing, label }]} to label extra bearings on the bar.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<Compass> is a HUD-style horizontal compass bar. Drive heading from any yaw source — Image360Viewer onHeadingChange, a 3D controller, vehicle telemetry, etc.`,
    },
    composition: {
      title: `Composition`,
      body: `Tune fieldOfView for the zoom level, tickInterval for the tick spacing, and pass markers to label additional bearings. Negative or > 360° headings are normalised automatically.`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Slider-driven`,
        description: `Bar follows a slider that goes 0-360°.`,
      },
      markers: {
        title: `With waypoints`,
        description: `Two extra labelled bearings.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <Compass> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        defaultReadout: `Renders the default readout as integer degrees + cardinal direction.`,
        normalisesNegative: `Normalises a negative heading into the 0-359° range.`,
        normalisesLarge: `Normalises a heading > 360°.`,
        mapsCardinal: `Maps headings near a cardinal to that cardinal direction.`,
        cardinalsByDefault: `Renders cardinal labels (N / E / S / W) by default.`,
        readoutNullHides: `Hides the readout when readout={null}.`,
        customReadout: `Accepts a custom readout node.`,
        rendersMarkers: `Renders extra markers passed via the markers prop.`,
        hideCardinals: `hideCardinals removes the default cardinal labels from the bar.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `The bar scrolls horizontally regardless of text direction. The numeric readout follows the surrounding text direction.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <Compass>.`,
    },
  },
};

export const compassDe: CompassTranslation = {
  default: {
    title: `Slider-gesteuert`,
    description: `Ziehe den Slider 0-360°; die Leiste scrollt, sodass der Mittelmarker beim aktuellen Bearing bleibt.`,
  },
  markers: {
    title: `Mit Wegpunkten`,
    description: `markers={[{ bearing, label }]} beschriftet zusätzliche Bearings auf der Leiste.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Importpfade an dein Projekt an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<Compass> ist eine HUD-artige horizontale Kompass-Leiste. heading aus beliebiger yaw-Quelle treiben — Image360Viewer onHeadingChange, 3D-Controller, Fahrzeug-Telemetrie usw.`,
    },
    composition: {
      title: `Komposition`,
      body: `fieldOfView für den Zoom, tickInterval für den Tick-Abstand, markers für zusätzliche Bearings. Negative oder > 360°-Werte werden automatisch normalisiert.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Slider-gesteuert`,
        description: `Leiste folgt einem 0-360°-Slider.`,
      },
      markers: {
        title: `Mit Wegpunkten`,
        description: `Zwei zusätzliche beschriftete Bearings.`,
      },
    },
    definedBehaviour: {
      title: `Festgelegtes Verhalten`,
      intro: `Aussagen darüber, wie sich <Compass> verhalten soll, jeweils mit Verweis auf den Test.`,
      verifiedBy: `geprüft durch`,
      statements: {
        defaultReadout: `Rendert den Default-Readout als Ganzgrad + Himmelsrichtung.`,
        normalisesNegative: `Normalisiert ein negatives heading auf 0-359°.`,
        normalisesLarge: `Normalisiert ein heading > 360°.`,
        mapsCardinal: `Mappt Headings nahe einer Himmelsrichtung auf diese.`,
        cardinalsByDefault: `Rendert standardmäßig Himmelsrichtungs-Labels (N / E / S / W).`,
        readoutNullHides: `Blendet den Readout aus, wenn readout={null}.`,
        customReadout: `Akzeptiert einen eigenen Readout-Knoten.`,
        rendersMarkers: `Rendert zusätzliche Marker aus dem markers-Prop.`,
        hideCardinals: `hideCardinals entfernt die Default-Himmelsrichtungs-Labels von der Leiste.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Die Leiste scrollt horizontal unabhängig von der Schreibrichtung. Der numerische Readout folgt der Schreibrichtung.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <Compass> akzeptiert.`,
    },
  },
};
