/**
 * Translation slice for nodeEditor.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to nodeEditor's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface NodeEditorTranslation {
  default: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        acceptsMatchingTypes: string;
        rejectsMismatchedTypes: string;
        rejectsMixedTypedUntyped: string;
        allowsTwoUntyped: string;
        rejectsIncompleteDrag: string;
        extraAfterTyped: string;
        lazyChunk: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const nodeEditorEn: NodeEditorTranslation = {
  default: {
    title: `Typed graph`,
    description: `Four nodes wired through typed ports. The Slider node outputs a number; drag from its right handle to the Doubler's input to see 2× appear live. The Text node outputs a string — dragging it to a number input is rejected by the typed validator. Each node body embeds an arbitrary React component (Slider, Input, live values) to show intermediary results.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<NodeEditor> wraps @xyflow/react (React Flow) with built-in port-type validation, a default node renderer (TypedNode) that embeds arbitrary React content, and a lazy-loaded implementation chunk so consumers only pay the bundle cost when a node editor actually mounts.`,
    },
    composition: {
      title: `Composition`,
      body: `Use <TypedHandle portType="..."> inside custom nodes to declare strict-equality port types. The editor's isValidConnection rejects any connection whose source/target portTypes differ — or where one side is typed and the other isn't. Pass your own renderers via nodeTypes; the built-in "typed" renderer (TypedNode) is always registered and reads inputs/outputs/body off node.data.`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Typed graph`,
        description: `Four nodes wired through typed ports. The Slider node outputs a number; drag from its right handle to the Doubler's input to see 2× appear live. The Text node outputs a string — dragging it to a number input is rejected by the typed validator. Each node body embeds an arbitrary React component (Slider, Input, live values) to show intermediary results.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <NodeEditor> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        acceptsMatchingTypes: `Connection between two TypedHandles is accepted when both portType strings are equal.`,
        rejectsMismatchedTypes: `Connection between two TypedHandles is rejected when portTypes differ.`,
        rejectsMixedTypedUntyped: `Connection where one side is a TypedHandle and the other is a bare Handle is rejected.`,
        allowsTwoUntyped: `Connection between two untyped Handles is allowed.`,
        rejectsIncompleteDrag: `An incomplete drag (any of source / sourceHandle / target / targetHandle is null) is rejected.`,
        extraAfterTyped: `A caller-provided isValidConnection is consulted only after the typed check passes.`,
        lazyChunk: `The implementation chunk is loaded lazily via React.lazy so the @xyflow/react bundle ships only when a NodeEditor mounts.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `The graph canvas itself is direction-agnostic — coordinates are absolute. Custom node renderers should respect direction in their text content if needed.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <NodeEditor>, <TypedHandle>, and the data shape consumed by the built-in TypedNode renderer.`,
    },
  },
};

export const nodeEditorDe: NodeEditorTranslation = {
  default: {
    title: `Typisierter Graph`,
    description: `Vier Knoten, verbunden über typisierte Ports. Der Slider-Knoten gibt eine Zahl aus; zieh von seinem rechten Anschluss zum Eingang des Doublers, um 2× live zu sehen. Der Text-Knoten gibt einen String aus — eine Verbindung zu einem Zahl-Eingang lehnt der typisierte Validator ab. Jeder Knoten-Body bettet eine beliebige React-Komponente (Slider, Input, Live-Werte) ein, um Zwischenergebnisse anzuzeigen.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Import-Pfade an deine Projektstruktur an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<NodeEditor> umhüllt @xyflow/react (React Flow) mit eingebauter Port-Typ-Validierung, einem Standard-Knoten-Renderer (TypedNode), der beliebige React-Inhalte einbettet, und einer lazy geladenen Implementierungs-Chunk, sodass Konsumenten den Bundle-Aufpreis nur zahlen, wenn ein Node-Editor tatsächlich gemountet wird.`,
    },
    composition: {
      title: `Komposition`,
      body: `Verwende <TypedHandle portType="..."> innerhalb eigener Knoten, um Port-Typen mit strikter Gleichheit zu deklarieren. Die isValidConnection des Editors lehnt jede Verbindung ab, deren Quell- und Ziel-portType voneinander abweichen — oder bei der eine Seite typisiert und die andere nicht ist. Übergib deine eigenen Renderer per nodeTypes; der eingebaute "typed"-Renderer (TypedNode) ist immer registriert und liest inputs/outputs/body aus node.data.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Typisierter Graph`,
        description: `Vier Knoten, verbunden über typisierte Ports. Der Slider-Knoten gibt eine Zahl aus; zieh von seinem rechten Anschluss zum Eingang des Doublers, um 2× live zu sehen. Der Text-Knoten gibt einen String aus — eine Verbindung zu einem Zahl-Eingang lehnt der typisierte Validator ab. Jeder Knoten-Body bettet eine beliebige React-Komponente (Slider, Input, Live-Werte) ein, um Zwischenergebnisse anzuzeigen.`,
      },
    },
    definedBehaviour: {
      title: `Definiertes Verhalten`,
      intro: `Aussagen darüber, wie sich <NodeEditor> verhalten soll — jede verlinkt mit dem Test, der sie verifiziert.`,
      verifiedBy: `verifiziert durch`,
      statements: {
        acceptsMatchingTypes: `Eine Verbindung zwischen zwei TypedHandles wird akzeptiert, wenn beide portType-Strings gleich sind.`,
        rejectsMismatchedTypes: `Eine Verbindung zwischen zwei TypedHandles wird abgelehnt, wenn die portTypes abweichen.`,
        rejectsMixedTypedUntyped: `Eine Verbindung, bei der eine Seite ein TypedHandle und die andere ein nacktes Handle ist, wird abgelehnt.`,
        allowsTwoUntyped: `Eine Verbindung zwischen zwei untypisierten Handles ist erlaubt.`,
        rejectsIncompleteDrag: `Ein unvollständiges Drag (source / sourceHandle / target / targetHandle ist null) wird abgelehnt.`,
        extraAfterTyped: `Ein vom Aufrufer übergebenes isValidConnection wird erst konsultiert, nachdem die Typprüfung bestanden ist.`,
        lazyChunk: `Die Implementierungs-Chunk wird per React.lazy lazy geladen, sodass das @xyflow/react-Bundle nur ausgeliefert wird, wenn ein NodeEditor gemountet wird.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Die Graph-Leinwand selbst ist richtungs-agnostisch — Koordinaten sind absolut. Eigene Knoten-Renderer sollten Schreibrichtung bei Bedarf in ihren Textinhalten berücksichtigen.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <NodeEditor>, <TypedHandle> und die Datenform des eingebauten TypedNode-Renderers akzeptieren.`,
    },
  },
};
