/**
 * Translation slice for resourceList.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to resourceList's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface ResourceListTranslation {
  default: { title: string; description: string };
  grid: { title: string; description: string };
  multipleLayouts: { title: string; description: string };
  selection: { title: string; description: string };
  reorderable: { title: string; description: string };
  crossListDrag: { title: string; description: string };
  contextMenu: { title: string; description: string };
  multipleListsSharedAction: { title: string; description: string };
  horizontalStrip: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
      grid: { title: string; description: string };
      multipleLayouts: { title: string; description: string };
      selection: { title: string; description: string };
      reorderable: { title: string; description: string };
      crossListDrag: { title: string; description: string };
      contextMenu: { title: string; description: string };
      multipleListsSharedAction: { title: string; description: string };
      horizontalStrip: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        callsFetcher: string;
        firstWindow: string;
        forwardsSort: string;
        reorderFires: string;
        crossListAccept: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const resourceListEn: ResourceListTranslation = {
  default: {
    title: `Default`,
    description: `Tabular view of 600 deployments rendered via the column row handler. Resize columns by dragging the header borders; click a header to sort.`,
  },
  grid: {
    title: `Grid`,
    description: `360 colour swatches rendered as a fixed-cell gallery via GridListRowHandler. Drag the slider in the header to change the column count.`,
  },
  multipleLayouts: {
    title: `Multiple layouts`,
    description: `Same product catalog under both a Column and a Grid row handler. Switch layouts via the icon picker in the header — the list keeps its scroll position.`,
  },
  selection: {
    title: `Selection`,
    description: `Selection state surfaced via the onSelect handler. Click rows, ctrl/cmd-click to toggle, or shift-click for a range; the panel above mirrors the current count and last selected id.`,
  },
  reorderable: {
    title: `Reorderable`,
    description: `Set reorderable on the list to render a drag grip on every row. Dropping a row above or below another fires onReorder(fromIndex, toIndex); the consumer owns the data and applies the move.`,
  },
  crossListDrag: {
    title: `Cross-list drag`,
    description: `Three lists. A ↔ B accept each other's drops via reorderAcceptsFrom; C accepts only its own drags. While a drag is in flight every other list paints an overlay: a primary outline for accepting lists, a dimmed wash + "does not accept drops" badge for rejecting ones.`,
  },
  contextMenu: {
    title: `Context menu`,
    description: `Right-click any row to open an action menu (Open / Duplicate / Delete). The example wires a Radix DropdownMenu to onContextMenu inside the column render so the right-click target is the row itself.`,
  },
  multipleListsSharedAction: {
    title: `Shared action across lists`,
    description: `Two ResourceLists rendered side by side share a single "Delete" action via the global ActionManager. Each row is wrapped in [data-actionscope] + [data-list-id] + [data-item-id]; the one handler reads those attributes off the right-clicked element to dispatch back into the correct list's state.`,
  },
  horizontalStrip: {
    title: `Horizontal strip`,
    description: `Custom RowRendererDirection.Horizontal handler renders a horizontally-scrolling strip of cards. Each card embeds a FileViewer in "embedded" mode so the 60 thumbnails decode lazily as they scroll into view.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<ResourceList> renders a large paginated + virtualised list of any resource type. Plug in a getResourcesList function that fetches contiguous windows of items from the server, and pass one or more row handlers to control the layout.`,
    },
    composition: {
      title: `Composition`,
      body: `Provide one or more rowHandlers (Column / Grid / custom) — the user can switch between them via the header. Sort state is forwarded to getResourcesList so the server can return the correct page.`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Default`,
        description: `Tabular view of 600 deployments rendered via the column row handler. Resize columns by dragging the header borders; click a header to sort.`,
      },
      grid: {
        title: `Grid`,
        description: `360 colour swatches rendered as a fixed-cell gallery via GridListRowHandler. Drag the slider in the header to change the column count.`,
      },
      multipleLayouts: {
        title: `Multiple layouts`,
        description: `Same product catalog under both a Column and a Grid row handler. Switch layouts via the icon picker in the header — the list keeps its scroll position.`,
      },
      selection: {
        title: `Selection`,
        description: `Selection state surfaced via the onSelect handler. Click rows, ctrl/cmd-click to toggle, or shift-click for a range; the panel above mirrors the current count and last selected id.`,
      },
      reorderable: {
        title: `Reorderable`,
        description: `Set reorderable on the list to render a drag grip on every row. Dropping a row above or below another fires onReorder(fromIndex, toIndex); the consumer owns the data and applies the move.`,
      },
      crossListDrag: {
        title: `Cross-list drag`,
        description: `Three lists. A ↔ B accept each other's drops via reorderAcceptsFrom; C accepts only its own drags. While a drag is in flight every other list paints an overlay: a primary outline for accepting lists, a dimmed wash + "does not accept drops" badge for rejecting ones.`,
      },
      contextMenu: {
        title: `Context menu`,
        description: `Right-click any row to open an action menu (Open / Duplicate / Delete). The example wires a Radix DropdownMenu to onContextMenu inside the column render so the right-click target is the row itself.`,
      },
      multipleListsSharedAction: {
        title: `Shared action across lists`,
        description: `Two ResourceLists rendered side by side share a single "Delete" action via the global ActionManager. Each row is wrapped in [data-actionscope] + [data-list-id] + [data-item-id]; the one handler reads those attributes off the right-clicked element to dispatch back into the correct list's state.`,
      },
      horizontalStrip: {
        title: `Horizontal strip`,
        description: `Custom RowRendererDirection.Horizontal handler renders a horizontally-scrolling strip of cards. Each card embeds a FileViewer in "embedded" mode so the 60 thumbnails decode lazily as they scroll into view.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <ResourceList> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        callsFetcher: `Calls getResourcesList on mount.`,
        firstWindow: `First fetch passes fromIndex=0 and a finite positive limit.`,
        forwardsSort: `Forwards sortBy and sortDirection in the request body.`,
        reorderFires: `Fires onReorder with the from / to indices after a drag-and-drop reorder.`,
        crossListAccept: `Accepts drops from lists listed in reorderAcceptsFrom and rejects all others.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Header buttons and column order mirror under dir="rtl".`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <ResourceList>.`,
    },
  },
};

export const resourceListDe: ResourceListTranslation = {
  default: {
    title: `Standard`,
    description: `Tabellenansicht von 600 Deployments mit dem Spalten-Row-Handler. Spaltenbreiten lassen sich am Header ziehen; ein Klick auf den Spaltenkopf sortiert.`,
  },
  grid: {
    title: `Raster`,
    description: `360 Farbfelder als feste Kachel-Galerie über GridListRowHandler. Mit dem Slider im Header lässt sich die Anzahl der Spalten anpassen.`,
  },
  multipleLayouts: {
    title: `Mehrere Layouts`,
    description: `Derselbe Produktkatalog unter einem Spalten- und einem Raster-Row-Handler. Über den Icon-Picker im Header wechselst du das Layout — die Scrollposition bleibt erhalten.`,
  },
  selection: {
    title: `Auswahl`,
    description: `Auswahlzustand über den onSelect-Callback. Klicken, Strg/Cmd-Klick zum Umschalten, Shift-Klick für einen Bereich; das Panel darüber spiegelt Anzahl und zuletzt gewählte ID.`,
  },
  reorderable: {
    title: `Sortierbar per Drag & Drop`,
    description: `Setze reorderable an der Liste, um auf jeder Zeile einen Drag-Griff zu rendern. Wird eine Zeile über oder unter einer anderen abgelegt, feuert onReorder(fromIndex, toIndex); der Konsument hält die Daten und führt die Umordnung aus.`,
  },
  crossListDrag: {
    title: `Drag & Drop zwischen Listen`,
    description: `Drei Listen. A ↔ B akzeptieren über reorderAcceptsFrom gegenseitig Drops; C akzeptiert nur eigene Drags. Während ein Drag läuft, malt jede andere Liste ein Overlay: ein primärfarbener Rahmen für akzeptierende, ein abgedunkelter Schleier mit „nimmt keine Drops an“-Hinweis für ablehnende.`,
  },
  contextMenu: {
    title: `Kontextmenü`,
    description: `Rechtsklick auf eine Zeile öffnet ein Aktionsmenü (Öffnen / Duplizieren / Löschen). Das Beispiel hängt ein Radix-DropdownMenu in onContextMenu innerhalb des Spalten-Render — Ziel des Rechtsklicks ist die Zeile selbst.`,
  },
  multipleListsSharedAction: {
    title: `Gemeinsame Aktion über Listen hinweg`,
    description: `Zwei ResourceLists nebeneinander teilen sich eine einzige „Löschen“-Aktion über den globalen ActionManager. Jede Zeile bekommt [data-actionscope] + [data-list-id] + [data-item-id]; der eine Handler liest diese Attribute am rechtsangeklickten Element ab und dispatcht in den State der jeweils richtigen Liste.`,
  },
  horizontalStrip: {
    title: `Horizontaler Streifen`,
    description: `Ein eigener RowRendererDirection.Horizontal-Handler rendert einen horizontal scrollenden Streifen aus Karten. Jede Karte bettet FileViewer im „embedded“-Modus ein, sodass die 60 Vorschauen erst beim Scrollen geladen werden.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Import-Pfade an deine Projektstruktur an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<ResourceList> rendert eine große, paginierte und virtualisierte Liste beliebiger Ressourcen. Übergib eine getResourcesList-Funktion, die zusammenhängende Fenster vom Server lädt, und einen oder mehrere Row-Handler für das Layout.`,
    },
    composition: {
      title: `Komposition`,
      body: `Stelle einen oder mehrere rowHandlers bereit (Column / Grid / custom) — der Nutzer kann im Header zwischen ihnen wechseln. Sortierungs-Zustand wird an getResourcesList weitergegeben, damit der Server die korrekte Seite liefert.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Standard`,
        description: `Tabellenansicht von 600 Deployments mit dem Spalten-Row-Handler. Spaltenbreiten lassen sich am Header ziehen; ein Klick auf den Spaltenkopf sortiert.`,
      },
      grid: {
        title: `Raster`,
        description: `360 Farbfelder als feste Kachel-Galerie über GridListRowHandler. Mit dem Slider im Header lässt sich die Anzahl der Spalten anpassen.`,
      },
      multipleLayouts: {
        title: `Mehrere Layouts`,
        description: `Derselbe Produktkatalog unter einem Spalten- und einem Raster-Row-Handler. Über den Icon-Picker im Header wechselst du das Layout — die Scrollposition bleibt erhalten.`,
      },
      selection: {
        title: `Auswahl`,
        description: `Auswahlzustand über den onSelect-Callback. Klicken, Strg/Cmd-Klick zum Umschalten, Shift-Klick für einen Bereich; das Panel darüber spiegelt Anzahl und zuletzt gewählte ID.`,
      },
      reorderable: {
        title: `Sortierbar per Drag & Drop`,
        description: `Setze reorderable an der Liste, um auf jeder Zeile einen Drag-Griff zu rendern. Wird eine Zeile über oder unter einer anderen abgelegt, feuert onReorder(fromIndex, toIndex); der Konsument hält die Daten und führt die Umordnung aus.`,
      },
      crossListDrag: {
        title: `Drag & Drop zwischen Listen`,
        description: `Drei Listen. A ↔ B akzeptieren über reorderAcceptsFrom gegenseitig Drops; C akzeptiert nur eigene Drags. Während ein Drag läuft, malt jede andere Liste ein Overlay: ein primärfarbener Rahmen für akzeptierende, ein abgedunkelter Schleier mit „nimmt keine Drops an“-Hinweis für ablehnende.`,
      },
      contextMenu: {
        title: `Kontextmenü`,
        description: `Rechtsklick auf eine Zeile öffnet ein Aktionsmenü (Öffnen / Duplizieren / Löschen). Das Beispiel hängt ein Radix-DropdownMenu in onContextMenu innerhalb des Spalten-Render — Ziel des Rechtsklicks ist die Zeile selbst.`,
      },
      multipleListsSharedAction: {
        title: `Gemeinsame Aktion über Listen hinweg`,
        description: `Zwei ResourceLists nebeneinander teilen sich eine einzige „Löschen“-Aktion über den globalen ActionManager. Jede Zeile bekommt [data-actionscope] + [data-list-id] + [data-item-id]; der eine Handler liest diese Attribute am rechtsangeklickten Element ab und dispatcht in den State der jeweils richtigen Liste.`,
      },
      horizontalStrip: {
        title: `Horizontaler Streifen`,
        description: `Ein eigener RowRendererDirection.Horizontal-Handler rendert einen horizontal scrollenden Streifen aus Karten. Jede Karte bettet FileViewer im „embedded“-Modus ein, sodass die 60 Vorschauen erst beim Scrollen geladen werden.`,
      },
    },
    definedBehaviour: {
      title: `Definiertes Verhalten`,
      intro: `Aussagen darüber, wie sich <ResourceList> verhalten soll — jede verlinkt mit dem Test, der sie verifiziert.`,
      verifiedBy: `verifiziert durch`,
      statements: {
        callsFetcher: `Ruft getResourcesList beim Mounten auf.`,
        firstWindow: `Erster Fetch übergibt fromIndex=0 und ein endliches, positives limit.`,
        forwardsSort: `Leitet sortBy und sortDirection im Request-Body weiter.`,
        reorderFires: `Feuert onReorder mit den from/to-Indizes nach einer Drag-&-Drop-Umordnung.`,
        crossListAccept: `Akzeptiert Drops nur von Listen, die in reorderAcceptsFrom stehen, und lehnt alle anderen ab.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Header-Buttons und Spaltenanordnung werden unter dir="rtl" gespiegelt.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <ResourceList> akzeptiert.`,
    },
  },
};
