/*
 * mows-package-manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiResponseEmptyApiResponse {
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<serde_json::Value>>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "status")]
    pub status: models::ApiResponseStatus,
}

impl ApiResponseEmptyApiResponse {
    pub fn new(message: String, status: models::ApiResponseStatus) -> ApiResponseEmptyApiResponse {
        ApiResponseEmptyApiResponse {
            data: None,
            message,
            status,
        }
    }
}

