/*
 * mows-package-manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiResponseRenderRepositoriesResBodyData {
    #[serde(rename = "results")]
    pub results: Vec<std::collections::HashMap<String, String>>,
}

impl ApiResponseRenderRepositoriesResBodyData {
    pub fn new(results: Vec<std::collections::HashMap<String, String>>) -> ApiResponseRenderRepositoriesResBodyData {
        ApiResponseRenderRepositoriesResBodyData {
            results,
        }
    }
}

