/*
 * mows-package-manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RenderRepositoriesRepositorySelector {
    RenderRepositoriesRepositorySelectorOneOf(Box<models::RenderRepositoriesRepositorySelectorOneOf>),
    RenderRepositoriesRepositorySelectorOneOf1(Box<models::RenderRepositoriesRepositorySelectorOneOf1>),
}

impl Default for RenderRepositoriesRepositorySelector {
    fn default() -> Self {
        Self::RenderRepositoriesRepositorySelectorOneOf(Default::default())
    }
}

