/*
 * mows-package-manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Repository {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "uri")]
    pub uri: String,
}

impl Repository {
    pub fn new(id: i32, uri: String) -> Repository {
        Repository {
            id,
            uri,
        }
    }
}

