// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterRule } from "./FilterRule";

export interface AdvancedSearch { query: string, groupId: string, filters: Array<FilterRule>, }