// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Visibility } from "./Visibility";

export interface CreateUserGroupRequestBody { name: string | null, visibility: Visibility, permission_ids: Array<string>, }