// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Visibility } from "./Visibility";

export interface CreateFileGroupRequestBody { name: string | null, visibility: Visibility, }