// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilezPermissionAcl } from "./FilezPermissionAcl";
import type { FilezPermissionUseType } from "./FilezPermissionUseType";

export interface CreatePermissionRequestBody { name: string | null, acl: FilezPermissionAcl | null, ribston: string | null, use_type: FilezPermissionUseType, }