// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateFileRequest { name: string, mime_type: string, storage_id: string | null, static_file_group_ids: Array<string> | null, created: bigint | null, modified: bigint | null, }