// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateFileRequest { name: string, mimeType: string, storageId: string | null, staticFileGroupIds: Array<string> | null, created: bigint | null, modified: bigint | null, }