// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupType } from "./GroupType";

export interface DeleteGroupRequestBody { group_id: string, group_type: GroupType, }