// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EveryoneAcl { get_file: boolean | null, update_file: boolean | null, delete_file: boolean | null, get_file_info: boolean | null, }