// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageLimits } from "./UsageLimits";

export interface FilezUser { _id: string, appData: Record<string, any>, limits: Record<string, UsageLimits>, userGroupIds: Array<string>, }