// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FilezFile {
    _id: string;
    mime_type: string;
    name: string;
    owner_id: string;
    pending_new_owner_id: string | null;
    sha256: string | null;
    storage_id: string | null;
    size: number;
    server_created: number;
    created: number;
    modified: number;
    accessed: number;
    accessed_count: number;
    static_file_group_ids: Array<string>;
    dynamic_file_group_ids: Array<string>;
    time_of_death: number;
    app_data: Record<string, any>;
    permission_ids: Array<string>;
    keywords: Array<string>;
    readonly: boolean;
    readonly_path: string | null;
}
