// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilezFileGroup } from "./FilezFileGroup";
import type { UserGroup } from "./UserGroup";

export type FilezGroups = UserGroup | FilezFileGroup;