// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilezPermissionAcl } from "./FilezPermissionAcl";
import type { FilezPermissionUseType } from "./FilezPermissionUseType";

export interface FilezPermission { _id: string, use_type: FilezPermissionUseType, name: string | null, owner_id: string, acl: FilezPermissionAcl | null, ribston: string | null, }