// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilezPermissionAclUsers } from "./FilezPermissionAclUsers";

export interface FilezPermissionAclWho { link: boolean | null, passwords: Array<string> | null, users: FilezPermissionAclUsers | null, }