// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilezPermissionUseType } from "./FilezPermissionUseType";
import type { PermissionResourceType } from "./PermissionResourceType";

export interface FilezPermission { _id: string, use_type: FilezPermissionUseType, name: string | null, owner_id: string, content: PermissionResourceType, }