// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilezFileGroup } from "./FilezFileGroup";
import type { FilezUserGroup } from "./FilezUserGroup";

export type FilezGroups = FilezUserGroup | FilezFileGroup;