// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilezFilePermissionAclWhatOptions = "GetFile" | "GetFileDerivatives" | "GetFileInfos" | "DeleteFile" | "UpdateFileInfosName" | "UpdateFileInfosMimeType" | "UpdateFileInfosKeywords" | "UpdateFileInfosStaticFileGroups" | "UpdateFile";