// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilezFile } from "./FilezFile";

export interface GetFileInfosByGroupIdResponseBody { total_count: number, files: Array<FilezFile>, }