// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortOrder } from "./SortOrder";

export interface GetItemListRequestBody { id?: string, from_index: number, limit: number, sort_field: string | null, sort_order: SortOrder | null, filter: string | null, }