// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilezUser } from "./FilezUser";
import type { ReducedFilezUser } from "./ReducedFilezUser";

export interface GetUserResponseBody { reduced_users: Array<ReducedFilezUser> | null, full_users: Array<FilezUser> | null, }