// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReducedFilezUser } from "./ReducedFilezUser";

export interface GetUserListResponseBody { users: Array<ReducedFilezUser>, total_count: number, }