// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStage } from "./JobStage";
import type { JobStatus } from "./JobStatus";
import type { JobType } from "./JobType";

export interface Job { _id: string, forAppId: string, appInfo: Record<string, any>, jobType: JobType, status: JobStatus, createdTimeMillis: bigint, updatedTimeMillis: bigint, endTimeMillis: bigint | null, stages: Array<JobStage>, }