// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatus } from "./JobStatus";

export interface JobStage { status: JobStatus, startedTimeMillis: bigint, endTimeMillis: bigint | null, title: string, description: string, error: string | null, }