// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatus } from "./JobStatus";

export interface JobStage { status: JobStatus, started_time_millis: bigint, end_time_millis: bigint | null, title: string, description: string, error: string | null, }