// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PasswordAcl { get_file: Array<string> | null, update_file: Array<string> | null, delete_file: Array<string> | null, get_file_info: Array<string> | null, }