// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvancedSearch } from "./AdvancedSearch";
import type { SimpleSearch } from "./SimpleSearch";

export type SearchType = { "SimpleSearch": SimpleSearch } | { "AdvancedSearch": AdvancedSearch };