// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchRequestType } from "./SearchRequestType";

export interface SearchRequest { searchType: SearchRequestType, limit: number, }