// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvancedSearchRequest } from "./AdvancedSearchRequest";
import type { SimpleSearchRequest } from "./SimpleSearchRequest";

export type SearchRequestType = { "simpleSearch": SimpleSearchRequest } | { "advancedSearch": AdvancedSearchRequest };