// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateUserGroupInfosRequestField } from "./UpdateUserGroupInfosRequestField";

export interface UpdateUserGroupRequestBody { user_group_id: string, fields: UpdateUserGroupInfosRequestField, }