// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileGroupType } from "./FileGroupType";
import type { FilterRule } from "./FilterRule";

export type UpdateFileGroupInfosRequestField = { "Name": string } | { "DynamicGroupRules": FilterRule } | { "GroupType": FileGroupType } | { "Keywords": Array<string> } | { "MimeTypes": Array<string> } | { "GroupHierarchyPaths": Array<string> };