// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateFileInfosRequestField { mime_type?: string, name?: string, static_file_group_ids?: Array<string>, keywords?: Array<string>, owner_id?: string, storage_id?: string, permission_ids?: Array<string>, }