// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateFileGroupInfosRequestField } from "./UpdateFileGroupInfosRequestField";

export interface UpdateFileGroupRequestBody { file_group_id: string, field: UpdateFileGroupInfosRequestField, }