// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileGroupType } from "./FileGroupType";
import type { FilterRule } from "./FilterRule";

export interface UpdateFileGroupRequestBody { file_group_id: string, new_name: string | null, new_dynamic_group_rules: FilterRule | null, new_group_type: FileGroupType | null, new_keywords: Array<string> | null, new_mime_types: Array<string> | null, }