// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateFileInfosRequestField } from "./UpdateFileInfosRequestField";

export interface UpdateFileInfosRequest { fileId: string, field: UpdateFileInfosRequestField, }