// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateFileInfosRequestField { mime_type: string | null, name: string | null, static_file_group_ids: Array<string> | null, keywords: Array<string> | null, owner_id: string | null, storage_id: string | null, permission_ids: Array<string> | null, }