// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilezPermissionUseType } from "./FilezPermissionUseType";
import type { PermissionResourceType } from "./PermissionResourceType";

export interface UpdatePermissionRequestBody { permission_id: string, name: string | null, content: PermissionResourceType, use_type: FilezPermissionUseType, }