// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateFileInfosRequestField = { "MimeType": string } | { "Name": string } | { "OwnerId": string } | { "StorageId": string } | { "StaticFileGroupIds": Array<string> } | { "Keywords": Array<string> };