// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileResourceType } from "./FileResourceType";

export interface UpdatePermissionsRequestBody { permissionIds: Array<string>, resourceId: string, resourceType: FileResourceType, }