// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageLimits } from "./UsageLimits";

export interface UploadSpace { _id: string, owner_id: string, limits: Record<string, UsageLimits>, file_group_id: string, }