// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UsageLimits { max_storage: bigint, used_storage: bigint, max_files: bigint, used_files: bigint, max_bandwidth: bigint, used_bandwidth: bigint, }