// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UsageLimits { maxStorage: bigint, usedStorage: bigint, maxFiles: bigint, usedFiles: bigint, maxBandwidth: bigint, usedBandwidth: bigint, }