// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UsersAclUsersAndUserGroups { userIds: Array<string> | null, userGroupIds: Array<string> | null, }