// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Visibility } from "./Visibility";

export interface UserGroup { _id: string, name: string | null, owner_id: string, visibility: Visibility, permission_ids: Array<string>, }