/**
 * Translation slice for dialog.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to dialog's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface DialogTranslation {
  default: { title: string; description: string };
  hideClose: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
      hideClose: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        closedByDefault: string;
        defaultOpen: string;
        opensOnTrigger: string;
        ariaWiring: string;
        closeButton: string;
        closesOnEscape: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const dialogEn: DialogTranslation = {
  default: {
    title: `Confirm destructive action`,
    description: `Click the button to open a modal dialog with title, body, and Cancel / Delete actions in the footer.`,
  },
  hideClose: {
    title: `Without the corner X`,
    description: `showCloseButton={false} hides the built-in corner close — useful when closing must go through an explicit footer action.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<Dialog> wraps Radix Dialog. Compose with <DialogTrigger>, <DialogContent>, <DialogHeader> (with <DialogTitle> and <DialogDescription>), <DialogFooter>, and <DialogClose>.`,
    },
    composition: {
      title: `Composition`,
      body: `DialogContent renders a corner close button by default; pass showCloseButton={false} to hide it. Escape and overlay-clicks also close the dialog.`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Confirm destructive action`,
        description: `Dialog with header + body + Cancel/Delete footer.`,
      },
      hideClose: {
        title: `Without the corner X`,
        description: `showCloseButton={false} forces explicit footer action.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <Dialog> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        closedByDefault: `Is closed by default — the content is not rendered.`,
        defaultOpen: `Renders the content when defaultOpen is set.`,
        opensOnTrigger: `Opens when the trigger is clicked.`,
        ariaWiring: `Exposes role="dialog" with the title + description wired into aria-labelledby / aria-describedby.`,
        closeButton: `Renders a built-in close button labelled "Close" that closes the dialog when clicked.`,
        closesOnEscape: `Closes on Escape.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Under dir="rtl" the corner close button moves to the leading edge; footer actions follow the surrounding text direction.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <Dialog> and <DialogContent>. The other slots (<DialogHeader>, <DialogTitle>, <DialogDescription>, <DialogFooter>, <DialogClose>) accept all native attributes for their underlying element.`,
    },
  },
};

export const dialogDe: DialogTranslation = {
  default: {
    title: `Destruktive Aktion bestätigen`,
    description: `Über den Button öffnet ein Modal-Dialog mit Titel, Body und Cancel/Delete-Aktionen im Footer.`,
  },
  hideClose: {
    title: `Ohne Eck-X`,
    description: `showCloseButton={false} blendet das eingebaute Eck-X aus — nützlich, wenn das Schließen über eine explizite Footer-Aktion erfolgen muss.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Importpfade an dein Projekt an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<Dialog> kapselt Radix Dialog. Kombiniere mit <DialogTrigger>, <DialogContent>, <DialogHeader> (mit <DialogTitle> + <DialogDescription>), <DialogFooter> und <DialogClose>.`,
    },
    composition: {
      title: `Komposition`,
      body: `DialogContent rendert standardmäßig ein Eck-X — mit showCloseButton={false} ausblenden. Escape und Overlay-Klicks schließen den Dialog ebenfalls.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Destruktive Aktion bestätigen`,
        description: `Dialog mit Header + Body + Cancel/Delete-Footer.`,
      },
      hideClose: {
        title: `Ohne Eck-X`,
        description: `showCloseButton={false} erzwingt explizite Footer-Aktion.`,
      },
    },
    definedBehaviour: {
      title: `Festgelegtes Verhalten`,
      intro: `Aussagen darüber, wie sich <Dialog> verhalten soll, jeweils mit Verweis auf den Test.`,
      verifiedBy: `geprüft durch`,
      statements: {
        closedByDefault: `Ist standardmäßig geschlossen — der Inhalt wird nicht gerendert.`,
        defaultOpen: `Rendert den Inhalt, wenn defaultOpen gesetzt ist.`,
        opensOnTrigger: `Öffnet sich beim Klick auf den Trigger.`,
        ariaWiring: `Exponiert role="dialog" mit aria-labelledby / aria-describedby auf Title / Description.`,
        closeButton: `Rendert einen eingebauten Schließen-Button mit Label "Close", der den Dialog beim Klick schließt.`,
        closesOnEscape: `Schließt sich bei Escape.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Unter dir="rtl" wandert das Eck-X an die führende Kante; Footer-Aktionen folgen der Schreibrichtung.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <Dialog> und <DialogContent> akzeptieren. Die anderen Slots akzeptieren die nativen Attribute ihres jeweiligen Elements.`,
    },
  },
};
