/**
 * Translation slice for avatar.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to avatar's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface AvatarTranslation {
    default: { title: string; description: string };
    loading: { title: string; description: string };
    doc: {
        installation: {
            title: string;
            commandTab: string;
            manualTab: string;
            manualStep1: string;
            manualStep2: string;
            manualStep3: string;
        };
        usage: { title: string; body: string };
        composition: { title: string; body: string };
        examples: {
            title: string;
            default: { title: string; description: string };
            loading: { title: string; description: string };
        };
        definedBehaviour: {
            title: string;
            intro: string;
            verifiedBy: string;
            statements: {
                uppercasedInitial: string;
                unicodeInitial: string;
                skeletonWhenMissing: string;
                skeletonWhenEmpty: string;
                classNameMerge: string;
                styleForwards: string;
            };
        };
        rtl: { title: string; body: string };
        apiReference: { title: string; intro: string };
    };
}

export const avatarEn: AvatarTranslation = {
    default: {
        title: `Initials`,
        description: `The first character of displayName, uppercased, inside a circular outline.`
    },
    loading: {
        title: `Loading state`,
        description: `Without a displayName the avatar renders a Skeleton placeholder — useful while auth is still resolving.`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Command`,
            manualTab: `Manual`,
            manualStep1: `Install the following dependencies:`,
            manualStep2: `Copy and paste the following code into your project.`,
            manualStep3: `Update the import paths to match your project setup.`
        },
        usage: {
            title: `Usage`,
            body: `<Avatar> renders the uppercased first letter of displayName inside a circle. Omit displayName for a Skeleton placeholder.`
        },
        composition: {
            title: `Composition`,
            body: `Compose with className for size variants (e.g. h-7 w-7 text-xs for an inline trigger, h-16 w-16 text-xl for a profile header).`
        },
        examples: {
            title: `Examples`,
            default: {
                title: `Initials`,
                description: `Four avatars — three with names, one loading.`
            },
            loading: {
                title: `Loading state`,
                description: `Single placeholder while waiting on auth.`
            }
        },
        definedBehaviour: {
            title: `Defined behaviour`,
            intro: `Statements describing how <Avatar> is expected to behave, each linked to the test that verifies it.`,
            verifiedBy: `verified by`,
            statements: {
                uppercasedInitial: `Shows the uppercased first letter of displayName.`,
                unicodeInitial: `Accepts non-ASCII first letters (ü, é, ñ, …).`,
                skeletonWhenMissing: `Renders the skeleton placeholder when displayName is omitted.`,
                skeletonWhenEmpty: `Renders the skeleton placeholder when displayName is the empty string.`,
                classNameMerge: `Merges className onto the outer wrapper without losing the rounded outline.`,
                styleForwards: `Forwards inline style onto the wrapper.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `Avatar is direction-agnostic — the circular initial reads the same in either text direction.`
        },
        apiReference: {
            title: `API Reference`,
            intro: `Props accepted by <Avatar>.`
        }
    }
};

export const avatarDe: AvatarTranslation = {
    default: {
        title: `Initialen`,
        description: `Der erste Buchstabe von displayName, großgeschrieben, in einem runden Outline.`
    },
    loading: {
        title: `Ladezustand`,
        description: `Ohne displayName rendert der Avatar einen Skeleton-Platzhalter — sinnvoll, während die Auth noch lädt.`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Befehl`,
            manualTab: `Manuell`,
            manualStep1: `Installiere die folgenden Abhängigkeiten:`,
            manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
            manualStep3: `Passe die Importpfade an dein Projekt an.`
        },
        usage: {
            title: `Verwendung`,
            body: `<Avatar> rendert den groß geschriebenen ersten Buchstaben von displayName in einem Kreis. displayName weglassen für einen Skeleton-Platzhalter.`
        },
        composition: {
            title: `Komposition`,
            body: `Über className Größenvarianten setzen (z. B. h-7 w-7 text-xs für einen Inline-Trigger, h-16 w-16 text-xl für eine Profil-Headline).`
        },
        examples: {
            title: `Beispiele`,
            default: {
                title: `Initialen`,
                description: `Vier Avatare — drei mit Namen, einer im Lade-Zustand.`
            },
            loading: {
                title: `Ladezustand`,
                description: `Einzelner Platzhalter, während die Auth lädt.`
            }
        },
        definedBehaviour: {
            title: `Festgelegtes Verhalten`,
            intro: `Aussagen darüber, wie sich <Avatar> verhalten soll, jeweils mit Verweis auf den Test.`,
            verifiedBy: `geprüft durch`,
            statements: {
                uppercasedInitial: `Zeigt den groß geschriebenen ersten Buchstaben von displayName.`,
                unicodeInitial: `Akzeptiert Nicht-ASCII-Anfangsbuchstaben (ü, é, ñ …).`,
                skeletonWhenMissing: `Rendert den Skeleton-Platzhalter, wenn displayName weggelassen wird.`,
                skeletonWhenEmpty: `Rendert den Skeleton-Platzhalter, wenn displayName der leere String ist.`,
                classNameMerge: `Merged className auf den äußeren Wrapper, ohne den Kreis-Outline zu verlieren.`,
                styleForwards: `Reicht inline style an den Wrapper durch.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `Der Avatar ist richtungsneutral — die runde Initialen-Darstellung liest sich in jeder Schreibrichtung gleich.`
        },
        apiReference: {
            title: `API-Referenz`,
            intro: `Props, die <Avatar> akzeptiert.`
        }
    }
};
