/**
 * Translation slice for videoViewer.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to videoViewer's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface VideoViewerTranslation {
  default: { title: string; description: string };
  dash: { title: string; description: string };
  hls: { title: string; description: string };
  chapters: { title: string; description: string };
  controls: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
      dash: { title: string; description: string };
      hls: { title: string; description: string };
      chapters: { title: string; description: string };
      controls: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        dispatchByMime: string;
        dispatchManifest: string;
        recognisesManifests: string;
        constructsOnePlayer: string;
        nativeFallback: string;
        reusesOnSrcChange: string;
        cleansUpOnUnmount: string;
        keyboardTogglePlay: string;
        keyboardModifierGuard: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const videoViewerEn: VideoViewerTranslation = {
  default: {
    title: `Progressive MP4`,
    description: `Standard video/mp4 served progressively via MediaSource Extensions. The seek-bar tooltip surfaces a real-time thumbnail of the hovered/dragged frame: a hidden off-screen <video> + <canvas> grabs frames on demand and the main player canvas updates live as you scrub, with the slider thumb pinned to the cursor until the seek lands so it never snaps back while the new range buffers.`,
  },
  dash: {
    title: `DASH manifest`,
    description: `application/dash+xml with multiple bitrate renditions. The quality button shows whichever variant Shaka's ABR is currently playing; picking a specific rendition disables ABR, picking Auto re-enables it. When the manifest declares a thumbnail AdaptationSet, the seek tooltip swaps the frame-grab tile for the pre-rendered sprite.`,
  },
  hls: {
    title: `HLS playlist`,
    description: `application/vnd.apple.mpegurl multi-rendition playlist. Same dispatch path as DASH — Shaka parses both through the same Player and the same control behaviours (quality menu, captions menu, drag-scrub preview) apply.`,
  },
  chapters: {
    title: `Chapters`,
    description: `Hand <VideoViewer> a chapters array and the seek bar grows tick marks at every boundary while the hover/drag tooltip surfaces the matching chapter title above the timestamp.`,
  },
  controls: {
    title: `Controls showcase`,
    description: `Switch between progressive, DASH, and HLS sources to exercise every control. Move the pointer to keep the bar visible; tab into the player and press space, arrows, m, f, p, or c to use the keyboard shortcuts. The playback-rate popover hosts both a continuous slider (0.25× – 3×) and preset chips.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `Hand <VideoViewer> a resolved src URL and a mimeType. It plays standard video/* formats progressively (via MediaSource) and DASH/HLS manifests with adaptive bitrate. The backend must support HTTP Range requests and expose Content-Range / Accept-Ranges / Content-Length via CORS.`,
    },
    composition: {
      title: `Composition`,
      body: `<VideoViewer> is normally reached via <FileViewer>, which lazy-loads it behind a Suspense boundary so non-video callers don't pay the ~256 kB shaka-player cost. Direct usage works too — wrap it in a sized container.`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Progressive MP4`,
        description: `Standard video/mp4 via MediaSource. Demonstrates the live drag-scrub: the main player canvas updates as the cursor moves, the floating tooltip shows a frame-grabbed thumbnail + timestamp at every position, and the slider stays pinned to the release point until <currentTime> catches up (5 s watchdog if a seek silently fails).`,
      },
      dash: {
        title: `DASH manifest`,
        description: `Multi-bitrate DASH. The Quality button shows what ABR picked; the menu's Auto entry surfaces the same in parens plus a tier badge. Manifests that ship a thumbnail track will swap the frame-grab preview for the pre-rendered sprite automatically.`,
      },
      hls: {
        title: `HLS playlist`,
        description: `Multi-rendition HLS — same dispatch as DASH. Hover/drag the bar to see the frame-grab fallback work for HLS-served files just like for MP4.`,
      },
      chapters: {
        title: `Chapters`,
        description: `Pass a chapters array to render YouTube-style tick marks on the seek bar at every chapter boundary. The hover/drag tooltip surfaces the matching chapter title next to the timestamp, so the user sees both 'where in the clip' and 'which chapter'.`,
      },
      controls: {
        title: `Controls showcase`,
        description: `Cycle between progressive, DASH, and HLS sources to exercise every control + keyboard shortcut. The playback-rate popover hosts a continuous slider (0.25× – 3×) alongside preset chips.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <VideoViewer> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        dispatchByMime: `<FileViewer> dispatches video/* mime types to <VideoViewer>.`,
        dispatchManifest: `<FileViewer> dispatches DASH and HLS manifest mime types to <VideoViewer>.`,
        recognisesManifests: `The isVideoOrStream helper matches video/* plus every supported streaming-manifest mime type.`,
        constructsOnePlayer: `Each mount installs Shaka polyfills once and constructs exactly one Player.`,
        nativeFallback: `When shaka.Player.isBrowserSupported() returns false, the component falls back to a native <video controls> element.`,
        reusesOnSrcChange: `Changing the src prop re-loads the existing Player instead of constructing a new one.`,
        cleansUpOnUnmount: `Unmounting calls Player.destroy() exactly once.`,
        keyboardTogglePlay: `Space and k toggle play / pause on the focused player.`,
        keyboardModifierGuard: `Keyboard shortcuts ignore modifier-combined presses so browser shortcuts (Cmd+F, Ctrl+R, …) keep working.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `The video surface is direction-agnostic. The control bar lays out its right-aligned action cluster with logical (start/end) flex order, so dir="rtl" inverts the cluster correctly without extra wiring.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <VideoViewer>.`,
    },
  },
};

export const videoViewerDe: VideoViewerTranslation = {
  default: {
    title: `Progressives MP4`,
    description: `Standard-video/mp4 wird progressiv über MediaSource Extensions ausgeliefert. Der Seek-Bar-Tooltip zeigt eine Live-Vorschau des überfahrenen/gezogenen Frames: ein verstecktes off-screen <video> + <canvas> erfasst Frames on demand, und die Hauptplayer-Fläche aktualisiert sich live beim Scrubbing. Der Slider-Daumen bleibt am Cursor fixiert, bis der Seek tatsächlich landet — er springt nicht zurück, während der neue Bereich gepuffert wird.`,
  },
  dash: {
    title: `DASH-Manifest`,
    description: `application/dash+xml mit mehreren Bitratenvarianten. Die Qualitäts-Schaltfläche zeigt, welche Variante Shakas ABR gerade abspielt; eine konkrete Variante deaktiviert ABR, der Eintrag „Auto“ schaltet ABR wieder ein. Liefert das Manifest ein Thumbnail-AdaptationSet, ersetzt die Seek-Vorschau das Frame-Grab-Bild automatisch durch das vorgerenderte Sprite.`,
  },
  hls: {
    title: `HLS-Playlist`,
    description: `application/vnd.apple.mpegurl-Playlist mit mehreren Renditions. Gleicher Dispatch-Pfad wie DASH — Shaka parst beides mit demselben Player, dieselben Bedienverhalten (Qualität, Untertitel, Drag-Scrub-Vorschau) gelten.`,
  },
  chapters: {
    title: `Kapitel`,
    description: `Übergib <VideoViewer> ein chapters-Array, und die Seek-Leiste erhält Strich-Marken an jeder Kapitelgrenze; der Hover/Drag-Tooltip blendet den passenden Kapiteltitel über dem Zeitstempel ein.`,
  },
  controls: {
    title: `Steuerungs-Showcase`,
    description: `Wechsle zwischen progressiver, DASH- und HLS-Quelle, um alle Bedienelemente auszuprobieren. Bewege den Zeiger, damit die Leiste sichtbar bleibt; fokussiere den Player und drücke Leertaste, Pfeiltasten, m, f, p oder c für die Tastaturkürzel. Das Wiedergaberate-Popover bietet sowohl einen stufenlosen Schieberegler (0,25× – 3×) als auch Voreinstellungen.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere und füge den folgenden Code in dein Projekt ein.`,
      manualStep3: `Passe die Import-Pfade an deine Projektstruktur an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `Übergib <VideoViewer> eine aufgelöste src-URL und einen mimeType. Standard-video/*-Formate werden progressiv (über MediaSource) abgespielt, DASH/HLS-Manifeste adaptiv. Das Backend muss HTTP-Range-Requests unterstützen und Content-Range / Accept-Ranges / Content-Length über CORS exponieren.`,
    },
    composition: {
      title: `Komposition`,
      body: `<VideoViewer> wird normalerweise über <FileViewer> erreicht; dieser lädt ihn lazy hinter einer Suspense-Grenze, damit Aufrufer ohne Video die ca. 256 kB shaka-player nicht bezahlen. Direkte Nutzung funktioniert ebenfalls — einfach in einen dimensionierten Container packen.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Progressives MP4`,
        description: `Standard-video/mp4 über MediaSource. Zeigt das Live-Drag-Scrubbing: die Hauptplayer-Fläche aktualisiert sich beim Ziehen, der schwebende Tooltip zeigt an jeder Position ein Frame-Grab-Thumbnail plus Zeitstempel, und der Slider bleibt an der Freigabeposition fixiert, bis <currentTime> ankommt (5-s-Watchdog falls der Seek stillschweigend fehlschlägt).`,
      },
      dash: {
        title: `DASH-Manifest`,
        description: `Multi-Bitraten-DASH. Die Qualitäts-Schaltfläche zeigt, was ABR gewählt hat; der Auto-Menüeintrag spiegelt dasselbe in Klammern plus Stufen-Badge. Manifeste mit Thumbnail-Track ersetzen die Frame-Grab-Vorschau automatisch durch das vorgerenderte Sprite.`,
      },
      hls: {
        title: `HLS-Playlist`,
        description: `Mehrere HLS-Renditions — gleicher Dispatch-Pfad wie DASH. Über/Ziehen über die Leiste, um zu sehen, dass der Frame-Grab-Fallback bei HLS-Dateien genauso funktioniert wie bei MP4.`,
      },
      chapters: {
        title: `Kapitel`,
        description: `Übergib ein chapters-Array, und die Seek-Leiste erhält YouTube-artige Strich-Marken an jeder Kapitelgrenze. Der Hover/Drag-Tooltip blendet den passenden Kapiteltitel neben dem Zeitstempel ein, damit der Nutzer „wo im Clip“ und „welches Kapitel“ gleichzeitig sieht.`,
      },
      controls: {
        title: `Steuerungs-Showcase`,
        description: `Wechsle zwischen progressiver, DASH- und HLS-Quelle, um alle Bedienelemente und Tastaturkürzel auszuprobieren. Das Wiedergaberate-Popover bietet sowohl einen stufenlosen Schieberegler (0,25× – 3×) als auch Voreinstellungen.`,
      },
    },
    definedBehaviour: {
      title: `Definiertes Verhalten`,
      intro: `Aussagen darüber, wie sich <VideoViewer> verhalten soll, jeweils mit dem Test verlinkt, der sie verifiziert.`,
      verifiedBy: `verifiziert durch`,
      statements: {
        dispatchByMime: `<FileViewer> reicht video/*-MIME-Typen an <VideoViewer> weiter.`,
        dispatchManifest: `<FileViewer> reicht DASH- und HLS-Manifest-MIME-Typen an <VideoViewer> weiter.`,
        recognisesManifests: `Die isVideoOrStream-Hilfsfunktion erkennt video/* und alle unterstützten Streaming-Manifest-MIME-Typen.`,
        constructsOnePlayer: `Jedes Mounten installiert Shaka-Polyfills einmalig und konstruiert genau einen Player.`,
        nativeFallback: `Wenn shaka.Player.isBrowserSupported() false liefert, fällt die Komponente auf ein natives <video controls> zurück.`,
        reusesOnSrcChange: `Ein Wechsel der src-Prop lädt den bestehenden Player neu, statt einen neuen zu konstruieren.`,
        cleansUpOnUnmount: `Beim Unmounten wird Player.destroy() genau einmal aufgerufen.`,
        keyboardTogglePlay: `Leertaste und k schalten Wiedergabe/Pause des fokussierten Players um.`,
        keyboardModifierGuard: `Tastaturkürzel ignorieren modifierkombinierte Tasten, damit Browser-Shortcuts (Cmd+F, Strg+R, …) weiterhin funktionieren.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Die Videofläche ist richtungsneutral. Die Steuerleiste ordnet ihre rechtsbündige Aktionsgruppe mit logischer (start/end) Flex-Reihenfolge an, sodass dir="rtl" die Gruppe korrekt spiegelt — ohne Zusatzverkabelung.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <VideoViewer> akzeptiert.`,
    },
  },
};
