/**
 * Translation slice for label.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to label's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface LabelTranslation {
  default: { title: string; description: string };
  htmlFor: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
      htmlFor: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        rendersNativeLabel: string;
        typographyClasses: string;
        htmlForFocuses: string;
        classNameMerge: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const labelEn: LabelTranslation = {
  default: {
    title: `Wrapping`,
    description: `Wrap the control inside the label — clicking the label area toggles it.`,
  },
  htmlFor: {
    title: `htmlFor`,
    description: `Use htmlFor when the control sits outside the label. Clicking the label focuses the matching input.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<Label> wraps the Radix Label primitive with shadcn typography. Pair with form controls — clicking the label focuses the associated input.`,
    },
    composition: {
      title: `Composition`,
      body: `Two equally-valid patterns: wrap the control inside the label, OR set htmlFor to the control's id.`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Wrapping`,
        description: `Checkbox nested inside <Label>.`,
      },
      htmlFor: {
        title: `htmlFor`,
        description: `Label adjacent to a separate Input.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <Label> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        rendersNativeLabel: `Renders a native label element.`,
        typographyClasses: `Carries the heading typography classes (text-sm, font-medium).`,
        htmlForFocuses: `Forwards htmlFor and focuses the matched input on click.`,
        classNameMerge: `Merges a custom className with the base classes.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Labels follow the surrounding text direction. The label-text reads RTL when wrapped in dir="rtl".`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <Label>.`,
    },
  },
};

export const labelDe: LabelTranslation = {
  default: {
    title: `Einwickeln`,
    description: `Den Control im Label einwickeln — Klicks auf den Label-Bereich schalten den Control um.`,
  },
  htmlFor: {
    title: `htmlFor`,
    description: `Wenn der Control außerhalb des Labels lebt, htmlFor verwenden. Klicks auf das Label fokussieren das passende Input.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Importpfade an dein Projekt an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<Label> kapselt die Radix-Label-Primitive mit shadcn-Typo. Mit Form-Controls kombinieren — Klicks aufs Label fokussieren das zugehörige Input.`,
    },
    composition: {
      title: `Komposition`,
      body: `Zwei gleichwertige Muster: Control im Label einwickeln ODER htmlFor auf die ID des Controls setzen.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Einwickeln`,
        description: `Checkbox im <Label> verschachtelt.`,
      },
      htmlFor: {
        title: `htmlFor`,
        description: `Label neben einem separaten Input.`,
      },
    },
    definedBehaviour: {
      title: `Festgelegtes Verhalten`,
      intro: `Aussagen darüber, wie sich <Label> verhalten soll, jeweils mit Verweis auf den Test.`,
      verifiedBy: `geprüft durch`,
      statements: {
        rendersNativeLabel: `Rendert ein natives label-Element.`,
        typographyClasses: `Trägt die Heading-Typo-Klassen (text-sm, font-medium).`,
        htmlForFocuses: `Reicht htmlFor durch und fokussiert beim Klick das passende Input.`,
        classNameMerge: `Merged ein eigenes className mit den Basis-Klassen.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Labels folgen der umgebenden Schreibrichtung. Der Label-Text liest RTL, wenn in dir="rtl" eingewickelt.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <Label> akzeptiert.`,
    },
  },
};
