/**
 * Translation slice for numberInput.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to numberInput's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface NumberInputTranslation {
    default: { title: string; description: string };
    decimal: { title: string; description: string };
    doc: {
        installation: {
            title: string;
            commandTab: string;
            manualTab: string;
            manualStep1: string;
            manualStep2: string;
            manualStep3: string;
        };
        usage: { title: string; body: string };
        composition: { title: string; body: string };
        examples: {
            title: string;
            default: { title: string; description: string };
            decimal: { title: string; description: string };
        };
        definedBehaviour: {
            title: string;
            intro: string;
            verifiedBy: string;
            statements: {
                rendersValue: string;
                nullRendersEmpty: string;
                clearEmitsNull: string;
                bumpsByStepPlus: string;
                bumpsByStepMinus: string;
                clampsToMin: string;
                clampsToMax: string;
                clampOnBlur: string;
                hideStepper: string;
            };
        };
        rtl: { title: string; body: string };
        apiReference: { title: string; intro: string };
    };
}

export const numberInputEn: NumberInputTranslation = {
    default: {
        title: `Integer with stepper`,
        description: `Drag-clamp to [0, 64] with step=1. The − / + buttons disable when at min/max.`
    },
    decimal: {
        title: `Decimal value`,
        description: `integerOnly={false} accepts decimals; step=0.1 controls the increment.`
    },
    doc: {
        installation: { title: `Installation`, commandTab: `Command`, manualTab: `Manual`, manualStep1: `Install the following dependencies:`, manualStep2: `Copy and paste the following code into your project.`, manualStep3: `Update the import paths to match your project setup.` },
        usage: { title: `Usage`, body: `<NumberInput> is a controlled numeric input with inline stepper buttons and min/max/step clamping. Empty value is communicated as null so callers can fall back to a server-side default.` },
        composition: { title: `Composition`, body: `Pair with the placeholder to communicate "what gets used when empty". Use integerOnly={false} for decimal values; hideStepper drops the − / + buttons.` },
        examples: { title: `Examples`, default: { title: `Integer with stepper`, description: `0-64 vCPUs, step=1.` }, decimal: { title: `Decimal value`, description: `0.1-10 GiB, step=0.1.` } },
        definedBehaviour: {
            title: `Defined behaviour`, intro: `Statements describing how <NumberInput> is expected to behave, each linked to the test that verifies it.`, verifiedBy: `verified by`,
            statements: {
                rendersValue: `Renders an input with the controlled value.`,
                nullRendersEmpty: `Renders empty when value is null.`,
                clearEmitsNull: `Fires onChange with null when the user clears the field.`,
                bumpsByStepPlus: `Bumps by step when the + button is clicked.`,
                bumpsByStepMinus: `Bumps by −step when the − button is clicked.`,
                clampsToMin: `Clamps to min on −.`,
                clampsToMax: `Clamps to max on +.`,
                clampOnBlur: `Clamps an out-of-range typed value on blur.`,
                hideStepper: `hideStepper drops the +/- buttons.`
            }
        },
        rtl: { title: `RTL`, body: `Under dir="rtl" the stepper buttons stay on the trailing edge of the input.` },
        apiReference: { title: `API Reference`, intro: `Props accepted by <NumberInput>.` }
    }
};

export const numberInputDe: NumberInputTranslation = {
    default: { title: `Ganzzahl mit Stepper`, description: `Klemmt auf [0, 64] mit step=1. Die − / + Buttons deaktivieren bei min/max.` },
    decimal: { title: `Dezimalwert`, description: `integerOnly={false} akzeptiert Dezimalwerte; step=0.1 steuert den Schritt.` },
    doc: {
        installation: { title: `Installation`, commandTab: `Befehl`, manualTab: `Manuell`, manualStep1: `Installiere die folgenden Abhängigkeiten:`, manualStep2: `Kopiere den folgenden Code in dein Projekt.`, manualStep3: `Passe die Importpfade an dein Projekt an.` },
        usage: { title: `Verwendung`, body: `<NumberInput> ist ein kontrolliertes numerisches Input mit Inline-Stepper-Buttons und min/max/step-Klemmung. Leerer Wert wird als null durchgereicht.` },
        composition: { title: `Komposition`, body: `Über placeholder „was bei leer verwendet wird" kommunizieren. integerOnly={false} für Dezimalwerte; hideStepper entfernt die − / + Buttons.` },
        examples: { title: `Beispiele`, default: { title: `Ganzzahl mit Stepper`, description: `0-64 vCPUs, step=1.` }, decimal: { title: `Dezimalwert`, description: `0.1-10 GiB, step=0.1.` } },
        definedBehaviour: {
            title: `Festgelegtes Verhalten`, intro: `Aussagen darüber, wie sich <NumberInput> verhalten soll, jeweils mit Verweis auf den Test.`, verifiedBy: `geprüft durch`,
            statements: {
                rendersValue: `Rendert ein Input mit dem kontrollierten Wert.`,
                nullRendersEmpty: `Rendert leer, wenn value null ist.`,
                clearEmitsNull: `Feuert onChange mit null, wenn das Feld geleert wird.`,
                bumpsByStepPlus: `Erhöht um step beim Klick auf +.`,
                bumpsByStepMinus: `Verringert um step beim Klick auf −.`,
                clampsToMin: `Klemmt auf min beim − .`,
                clampsToMax: `Klemmt auf max beim + .`,
                clampOnBlur: `Klemmt einen out-of-range-Wert beim Blur.`,
                hideStepper: `hideStepper entfernt die +/- Buttons.`
            }
        },
        rtl: { title: `RTL`, body: `Unter dir="rtl" bleiben die Stepper-Buttons am nachfolgenden Rand des Inputs.` },
        apiReference: { title: `API-Referenz`, intro: `Props, die <NumberInput> akzeptiert.` }
    }
};
