/**
 * Translation slice for input.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to input's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface InputTranslation {
  default: { title: string; description: string };
  types: { title: string; description: string };
  disabled: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
      types: { title: string; description: string };
      disabled: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        rendersTextInput: string;
        forwardsType: string;
        firesOnChange: string;
        fullyControllable: string;
        noInputWhenDisabled: string;
        forwardsRef: string;
        classNameMerge: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const inputEn: InputTranslation = {
  default: {
    title: `With label`,
    description: `Pair <Input> with <Label htmlFor> for accessible labelling.`,
  },
  types: {
    title: `Common types`,
    description: `text / password / number — every standard HTML input type forwards through.`,
  },
  disabled: {
    title: `Disabled`,
    description: `disabled disables the input and dims it.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<Input> is a thin styled wrapper over the native <input>. All native input attributes forward (type, value, onChange, placeholder, disabled, autoComplete, …).`,
    },
    composition: {
      title: `Composition`,
      body: `Pair with <Label htmlFor> for accessible labelling. Wire value + onChange for controlled mode.`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `With label`,
        description: `Labelled email input.`,
      },
      types: {
        title: `Common types`,
        description: `text / password / number.`,
      },
      disabled: {
        title: `Disabled`,
        description: `Disabled read-only field.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <Input> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        rendersTextInput: `Renders a native input element by default.`,
        forwardsType: `Forwards the type attribute (e.g. password) onto the native input.`,
        firesOnChange: `Fires onChange when the user types.`,
        fullyControllable: `Is fully controllable via value + onChange.`,
        noInputWhenDisabled: `Does not accept input when disabled.`,
        forwardsRef: `Forwards a ref to the underlying input element.`,
        classNameMerge: `Merges a custom className with the base classes.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Under dir="rtl" the input flips: caret starts on the right, placeholder + selected text follow the surrounding text direction.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <Input>.`,
    },
  },
};

export const inputDe: InputTranslation = {
  default: {
    title: `Mit Label`,
    description: `Kombiniere <Input> mit <Label htmlFor> für barrierefreie Beschriftung.`,
  },
  types: {
    title: `Häufige Typen`,
    description: `text / password / number — alle HTML-input-Typen werden durchgereicht.`,
  },
  disabled: {
    title: `Deaktiviert`,
    description: `disabled deaktiviert das Eingabefeld und dimmt es ab.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Importpfade an dein Projekt an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<Input> ist ein gestylter Wrapper um das native <input>. Alle nativen Attribute werden durchgereicht (type, value, onChange, placeholder, disabled, autoComplete …).`,
    },
    composition: {
      title: `Komposition`,
      body: `Kombiniere mit <Label htmlFor> für barrierefreie Beschriftung. value + onChange für kontrollierten Modus.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Mit Label`,
        description: `Beschrifteter Email-Input.`,
      },
      types: {
        title: `Häufige Typen`,
        description: `text / password / number.`,
      },
      disabled: {
        title: `Deaktiviert`,
        description: `Deaktiviertes Nur-Lese-Feld.`,
      },
    },
    definedBehaviour: {
      title: `Festgelegtes Verhalten`,
      intro: `Aussagen darüber, wie sich <Input> verhalten soll, jeweils mit Verweis auf den Test.`,
      verifiedBy: `geprüft durch`,
      statements: {
        rendersTextInput: `Rendert standardmäßig ein natives input-Element.`,
        forwardsType: `Reicht das type-Attribut (z. B. password) ans native input weiter.`,
        firesOnChange: `Feuert onChange beim Tippen.`,
        fullyControllable: `Ist vollständig steuerbar via value + onChange.`,
        noInputWhenDisabled: `Akzeptiert keine Eingabe, wenn disabled gesetzt ist.`,
        forwardsRef: `Reicht ein ref ans zugrundeliegende input-Element durch.`,
        classNameMerge: `Merged ein eigenes className mit den Basis-Klassen.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Unter dir="rtl" dreht sich das Input: Cursor startet rechts, Placeholder und Auswahl folgen der Schreibrichtung.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <Input> akzeptiert.`,
    },
  },
};
