/**
 * Translation slice for lyrics.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to lyrics's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface LyricsTranslation {
    basic: { title: string; description: string };
    compact: { title: string; description: string };
    karaoke: { title: string; description: string };
    synced: { title: string; description: string };
    rtl: { title: string; description: string };
    doc: {
        installation: {
            title: string;
            commandTab: string;
            manualTab: string;
            manualStep1: string;
            manualStep2: string;
            manualStep3: string;
        };
        usage: { title: string; body: string };
        composition: { title: string; body: string };
        examples: {
            title: string;
            basic: { title: string; description: string };
            compact: { title: string; description: string };
            karaoke: { title: string; description: string };
            synced: { title: string; description: string };
        };
        definedBehaviour: {
            title: string;
            intro: string;
            verifiedBy: string;
            statements: {
                parsesMetadata: string;
                expandsRepeats: string;
                karaokeWords: string;
                appliesOffset: string;
                activeIndex: string;
                seekOnClick: string;
                seekOnEnter: string;
                emptySource: string;
                noClickWithoutSeek: string;
                preparsed: string;
            };
        };
        rtl: { title: string; body: string };
        apiReference: { title: string; intro: string };
    };
}

export const lyricsEn: LyricsTranslation = {
    basic: {
        title: `Basic LRC`,
        description: `Time-synced lyrics parsed from a classic LRC string. The active line is highlighted and kept centred; inactive lines fade with distance.`
    },
    compact: {
        title: `Compact variant`,
        description: `Same parser, no auto-scroll, no fade — useful inside dense surfaces like a sidebar or card footer where the full lyric list is meant to be scanned at a glance.`
    },
    karaoke: {
        title: `Word-level (enhanced LRC)`,
        description: `Enhanced LRC sources sprinkle \`<mm:ss.xx>\` markers between words. The component highlights the active word as the timeline advances.`
    },
    synced: {
        title: `Synced with AudioPlayer`,
        description: `Wired to the lib's \`<AudioPlayer>\` via its imperative ref — press play and the active line follows the playhead. Clicking a lyric line seeks the player back. Audio: Brad Sucks — "Bad Sign" (CC-BY-SA 3.0, archive.org). LRC: community-authored synced lyrics from LRCLIB, keyed to this exact 232 s recording.`
    },
    rtl: {
        title: `Right-to-left`,
        description: `Wrapped in \`dir="rtl"\`. Lines remain centred and time-ordered, but the surrounding text direction flips.`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Command`,
            manualTab: `Manual`,
            manualStep1: `Install the following dependencies:`,
            manualStep2: `Copy and paste the following code into your project.`,
            manualStep3: `Update the import paths to match your project setup.`
        },
        usage: {
            title: `Usage`,
            body: `Feed the component a raw LRC string (or a pre-parsed \`ParsedLyrics\` value) plus the current playback time in seconds. The component finds the active line, optionally scrolls it into view, and exposes a seek callback so clicks on a line can drive your audio element.`
        },
        composition: {
            title: `Composition`,
            body: `The \`scrolling\` variant is the default and auto-scrolls the active line to the centre. Switch to \`variant="compact"\` when you want a static list. Pair with any audio source by piping \`audio.currentTime\` into \`currentTime\` and pointing \`onSeek\` back at \`audio.currentTime\` — no special hook required.`
        },
        examples: {
            title: `Examples`,
            basic: {
                title: `Basic LRC`,
                description: `Drive the active line with a slider that stands in for an audio element. The procedural scroll behaviour keeps the active line in view.`
            },
            compact: {
                title: `Compact variant`,
                description: `Same source rendered without auto-scroll or fade — sized for tight surfaces.`
            },
            karaoke: {
                title: `Word-level highlighting`,
                description: `Enhanced LRC with per-word \`<mm:ss.xx>\` markers. The active word picks up the primary colour as time advances.`
            },
            synced: {
                title: `Wired to AudioPlayer`,
                description: `Press play on the \`<AudioPlayer>\` to drive the lyrics. Clicking a line seeks the player back via its imperative ref. Audio: Brad Sucks — "Bad Sign" (CC-BY-SA 3.0). LRC: community-authored sync from LRCLIB.`
            }
        },
        definedBehaviour: {
            title: `Defined behaviour`,
            intro: `Statements about how \`<Lyrics>\` should behave, each referencing the test that enforces it.`,
            verifiedBy: `Verified by`,
            statements: {
                parsesMetadata: `Reads \`[ti:]\`, \`[ar:]\`, and \`[al:]\` tags out of the source string into the parsed metadata.`,
                expandsRepeats: `Expands repeated \`[mm:ss.xx][mm:ss.xx]\` prefixes into separate lines so choruses appear once per timestamp.`,
                karaokeWords: `Recognises enhanced LRC \`<mm:ss.xx>\` markers and exposes per-word timings on the parsed line.`,
                appliesOffset: `Applies the \`[offset:ms]\` correction by shifting every timestamp.`,
                activeIndex: `Selects the line whose start is the greatest value \`<= currentTime\`.`,
                seekOnClick: `Fires \`onSeek\` with the clicked line's start time when interactive.`,
                seekOnEnter: `Fires \`onSeek\` when Enter is pressed on a focused line.`,
                emptySource: `Renders the empty state with \`data-state="empty"\` when the source has no usable lines.`,
                noClickWithoutSeek: `Skips the interactive role entirely when no \`onSeek\` callback is wired up.`,
                preparsed: `Accepts a pre-parsed \`ParsedLyrics\` value without re-running the parser.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `Wrap the component in \`dir="rtl"\` to flip the surrounding text direction. Lines stay centred and time-ordered — only the inline content and prose around them mirror.`
        },
        apiReference: {
            title: `API Reference`,
            intro: `Props accepted by \`<Lyrics>\`.`
        }
    }
};

export const lyricsDe: LyricsTranslation = {
    basic: {
        title: `Klassisches LRC`,
        description: `Zeitsynchroner Liedtext, geparst aus einem klassischen LRC-String. Die aktive Zeile wird hervorgehoben und mittig gehalten; inaktive Zeilen blenden mit Abstand aus.`
    },
    compact: {
        title: `Kompakte Variante`,
        description: `Gleicher Parser, ohne Auto-Scroll und ohne Ausblendung — geeignet für dichte Oberflächen wie Seitenleisten oder Karten-Footer, wenn die gesamte Liedtextliste auf einen Blick lesbar bleiben soll.`
    },
    karaoke: {
        title: `Wort-Ebene (Enhanced LRC)`,
        description: `Enhanced-LRC-Quellen verteilen \`<mm:ss.xx>\`-Marker zwischen den Wörtern. Die Komponente hebt das aktive Wort hervor, sobald die Zeitachse weiterläuft.`
    },
    synced: {
        title: `Synchron mit AudioPlayer`,
        description: `Verbunden mit dem \`<AudioPlayer>\` der Library über dessen imperative Ref — drücke Play, und die aktive Zeile folgt dem Abspielkopf. Ein Klick auf eine Liedzeile springt im Player zurück. Audio: Brad Sucks — "Bad Sign" (CC-BY-SA 3.0, archive.org). LRC: Community-erstellter, zeitsynchroner Liedtext aus LRCLIB, exakt auf diese 232 s lange Aufnahme abgestimmt.`
    },
    rtl: {
        title: `Rechts-nach-links`,
        description: `Mit \`dir="rtl"\` umschlossen. Die Zeilen bleiben mittig und in zeitlicher Reihenfolge, aber die umgebende Schreibrichtung kehrt sich um.`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Befehl`,
            manualTab: `Manuell`,
            manualStep1: `Installiere die folgenden Abhängigkeiten:`,
            manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
            manualStep3: `Passe die Importpfade an dein Projekt an.`
        },
        usage: {
            title: `Verwendung`,
            body: `Übergib der Komponente einen rohen LRC-String (oder einen vorab geparsten \`ParsedLyrics\`-Wert) sowie die aktuelle Wiedergabezeit in Sekunden. Sie findet die aktive Zeile, scrollt sie optional ins Bild und stellt einen Seek-Callback bereit, damit Klicks auf eine Zeile dein Audio-Element steuern können.`
        },
        composition: {
            title: `Komposition`,
            body: `Die Variante \`scrolling\` ist Standard und scrollt die aktive Zeile automatisch in die Mitte. Mit \`variant="compact"\` erhältst du eine statische Liste. Für die Audio-Kopplung leitest du \`audio.currentTime\` an \`currentTime\` weiter und verdrahtest \`onSeek\` zurück auf \`audio.currentTime\` — kein zusätzlicher Hook nötig.`
        },
        examples: {
            title: `Beispiele`,
            basic: {
                title: `Klassisches LRC`,
                description: `Die aktive Zeile wird über einen Slider gesteuert, der ein Audio-Element ersetzt. Auto-Scroll hält sie im Bild.`
            },
            compact: {
                title: `Kompakte Variante`,
                description: `Gleiche Quelle, gerendert ohne Auto-Scroll und ohne Fade — passend für enge Oberflächen.`
            },
            karaoke: {
                title: `Wortgenaue Hervorhebung`,
                description: `Enhanced LRC mit \`<mm:ss.xx>\`-Markern pro Wort. Das aktive Wort übernimmt im Verlauf die Primärfarbe.`
            },
            synced: {
                title: `Verbunden mit AudioPlayer`,
                description: `Drücke Play am \`<AudioPlayer>\`, um den Liedtext zu treiben. Ein Klick auf eine Zeile springt über die imperative Ref im Player zurück. Audio: Brad Sucks — "Bad Sign" (CC-BY-SA 3.0). LRC: Community-Sync aus LRCLIB.`
            }
        },
        definedBehaviour: {
            title: `Festgelegtes Verhalten`,
            intro: `Aussagen darüber, wie sich \`<Lyrics>\` verhalten soll, jeweils mit Verweis auf den Test, der das absichert.`,
            verifiedBy: `Geprüft durch`,
            statements: {
                parsesMetadata: `Liest \`[ti:]\`-, \`[ar:]\`- und \`[al:]\`-Tags aus dem Quelltext in die geparsten Metadaten.`,
                expandsRepeats: `Erweitert wiederholte \`[mm:ss.xx][mm:ss.xx]\`-Präfixe zu separaten Zeilen, sodass Refrains pro Zeitstempel einmal erscheinen.`,
                karaokeWords: `Erkennt Enhanced-LRC-\`<mm:ss.xx>\`-Marker und legt pro-Wort-Zeitstempel auf der geparsten Zeile offen.`,
                appliesOffset: `Wendet die \`[offset:ms]\`-Korrektur an und verschiebt jeden Zeitstempel.`,
                activeIndex: `Wählt die Zeile, deren Startzeitpunkt der größte Wert \`<= currentTime\` ist.`,
                seekOnClick: `Feuert \`onSeek\` mit der Startzeit der geklickten Zeile, wenn die Komponente interaktiv ist.`,
                seekOnEnter: `Feuert \`onSeek\`, wenn Enter auf einer fokussierten Zeile gedrückt wird.`,
                emptySource: `Rendert den Leerzustand mit \`data-state="empty"\`, wenn die Quelle keine verwertbaren Zeilen enthält.`,
                noClickWithoutSeek: `Lässt die interaktive Rolle komplett weg, wenn kein \`onSeek\`-Callback verdrahtet ist.`,
                preparsed: `Akzeptiert einen vorab geparsten \`ParsedLyrics\`-Wert, ohne den Parser erneut auszuführen.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `Umschließe die Komponente mit \`dir="rtl"\`, um die umgebende Schreibrichtung zu spiegeln. Die Zeilen bleiben zentriert und zeitlich geordnet — gespiegelt werden nur die umgebenden Inhalte und die Prosa darum.`
        },
        apiReference: {
            title: `API-Referenz`,
            intro: `Props, die \`<Lyrics>\` akzeptiert.`
        }
    }
};
