/**
 * Translation slice for consoleManager.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to consoleManager's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface ConsoleManagerTranslation {
  default: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        seedsTabs: string;
        opensNewTab: string;
        closesTab: string;
        renamesOnDblClick: string;
        typePicker: string;
        splitRight: string;
        collapseSplit: string;
        keepsInactiveMounted: string;
        dragReorder: string;
        dragCrossPane: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const consoleManagerEn: ConsoleManagerTranslation = {
  default: {
    title: `Default`,
    description: `Tabbed console multiplexer with a Terminal tab and a LogView tab. Double-click a tab to rename, drag to reorder, click + to spawn another.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<ConsoleManager> hosts one or more registered console types (Terminal, LogView, custom) in a tabbed + splittable layout. Tabs stay mounted across tab and pane switches so long-running consoles never reset.`,
    },
    composition: {
      title: `Composition`,
      body: `Each ConsoleType.render() is called once per spawned tab; the result mounts for the lifetime of that tab. defaultName(ordinal) controls per-type auto-naming.`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Default`,
        description: `Two registered console types: an interactive Terminal and a static LogView pane.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <ConsoleManager> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        seedsTabs: `Renders the seeded initial tabs and marks the first as active.`,
        opensNewTab: `Pressing + opens a new tab in the currently active pane (single registered type).`,
        closesTab: `Closes the active tab and falls back to the previous tab.`,
        renamesOnDblClick: `Double-click → rename → Enter commits the new name.`,
        typePicker: `Shows the type-picker chevron when more than one console type is registered.`,
        splitRight: `Split-right turns the leaf into a horizontal split with a new sibling pane.`,
        collapseSplit: `Closing the last tab in a split-spawned pane collapses the split back to a single pane.`,
        keepsInactiveMounted: `Keeps inactive tab bodies mounted so they survive a tab switch.`,
        dragReorder: `Drag-reorder within a pane swaps the dropped tabs' order.`,
        dragCrossPane: `Dragging a tab from one pane onto a tab in another moves it across.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Tab list and split layout mirror under dir="rtl"; tab bodies preserve their own direction.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <ConsoleManager>.`,
    },
  },
};

export const consoleManagerDe: ConsoleManagerTranslation = {
  default: {
    title: `Standard`,
    description: `Konsolen-Multiplexer mit Reitern: ein Terminal-Tab und ein LogView-Tab. Doppelklick auf einen Tab benennt um, Ziehen sortiert, + erzeugt neue.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Import-Pfade an deine Projektstruktur an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<ConsoleManager> hostet einen oder mehrere registrierte Konsolentypen (Terminal, LogView, eigene) in einer Tab- und teilbaren Pane-Struktur. Tabs bleiben über Tab- und Pane-Wechsel hinweg gemountet, sodass laufende Konsolen niemals zurückgesetzt werden.`,
    },
    composition: {
      title: `Komposition`,
      body: `ConsoleType.render() wird einmal pro neu erzeugtem Tab aufgerufen; das Ergebnis bleibt für die Lebensdauer dieses Tabs gemountet. defaultName(ordinal) steuert die typspezifische automatische Benennung.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Standard`,
        description: `Zwei registrierte Konsolentypen: ein interaktives Terminal und eine statische LogView-Pane.`,
      },
    },
    definedBehaviour: {
      title: `Definiertes Verhalten`,
      intro: `Aussagen darüber, wie sich <ConsoleManager> verhalten soll — jede verlinkt mit dem Test, der sie verifiziert.`,
      verifiedBy: `verifiziert durch`,
      statements: {
        seedsTabs: `Rendert die initial vorgegebenen Tabs und markiert den ersten als aktiv.`,
        opensNewTab: `Drücken von + öffnet einen neuen Tab in der aktuell aktiven Pane (bei genau einem registrierten Typ).`,
        closesTab: `Schließt den aktiven Tab und fällt auf den vorherigen Tab zurück.`,
        renamesOnDblClick: `Doppelklick → Umbenennen → Eingabetaste übernimmt den neuen Namen.`,
        typePicker: `Zeigt den Typ-Auswahl-Chevron, wenn mehr als ein Konsolentyp registriert ist.`,
        splitRight: `"Rechts teilen" verwandelt das Blatt in eine horizontale Teilung mit einer neuen Schwester-Pane.`,
        collapseSplit: `Das Schließen des letzten Tabs in einer durch Split entstandenen Pane klappt die Teilung zurück in eine einzelne Pane.`,
        keepsInactiveMounted: `Hält inaktive Tab-Inhalte gemountet, damit sie einen Tab-Wechsel überleben.`,
        dragReorder: `Per Drag-and-drop innerhalb einer Pane wird die Reihenfolge der Tabs vertauscht.`,
        dragCrossPane: `Das Ziehen eines Tabs aus Pane 1 auf einen Tab in Pane 2 verschiebt ihn dorthin.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Tab-Liste und Split-Layout werden unter dir="rtl" gespiegelt; Tab-Inhalte behalten ihre eigene Richtung.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <ConsoleManager> akzeptiert.`,
    },
  },
};
