#!/bin/bash
set -euo pipefail

mows tools cargo-workspace-docker

export SERVICE_NAME="filez-server"

# Resolve the repo root from this script's location instead of hardcoding
# `/home/paul/projects/mows` (DEVOPS-9). Anyone else running `bash
# build.sh` from a different checkout path was hitting buildx permission
# errors.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"

export BAKE_ARGS="${BAKE_ARGS:-default} --allow=fs.read=${REPO_ROOT} --set *.args.APP_STAGE_IMAGE=alpine"

export BUILDKIT_PROGRESS="plain"

# Build-time API specs:
#  * openapi.json  - HTTP API (via scripts/codegen.sh)
#  * FilezResourceCRD.yaml          - Kubernetes CRD
#  * FilezResourceCRDSchema.json    - JSON Schema for FilezResource
# All three are generated by dedicated cargo binaries (no live server).
cargo run --bin crdgen > ../charts/filez/templates/server/FilezResourceCRD.yaml
cargo run --bin schemagen > FilezResourceCRDSchema.json

cargo run --bin gen_migrations


docker buildx bake ${BAKE_ARGS:-default} 

docker push ${REGISTRY:-localhost:5000}/${SERVICE_NAME}

bash scripts/codegen.sh

