/**
 * Translation slice for chart.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to chart's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface ChartTranslation {
  bar: { title: string; description: string };
  line: { title: string; description: string };
  area: { title: string; description: string };
  pie: { title: string; description: string };
  radar: { title: string; description: string };
  radial: { title: string; description: string };
  themed: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      bar: { title: string; description: string };
      line: { title: string; description: string };
      area: { title: string; description: string };
      pie: { title: string; description: string };
      radar: { title: string; description: string };
      radial: { title: string; description: string };
      themed: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        rendersWrapper: string;
        stableDataChartId: string;
        forwardsClassName: string;
        emitsStyleVars: string;
        mountsRecharts: string;
        styleNothingWithoutColor: string;
        styleThemeScopes: string;
        tooltipInactive: string;
        tooltipRendersLabel: string;
        legendEmptyPayload: string;
        legendRendersRows: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const chartEn: ChartTranslation = {
  bar: {
    title: `Bar`,
    description: `Grouped bars with a shared XAxis. Series colours come from <ChartConfig>; the tooltip and legend pull labels from the same map.`,
  },
  line: {
    title: `Line`,
    description: `Smooth monotone line. The tooltip uses an inline "line" indicator that matches the stroke colour of the series.`,
  },
  area: {
    title: `Area`,
    description: `Stacked area with per-series gradients. <defs> hosts the gradients; series reference them via fill="url(#…)".`,
  },
  pie: {
    title: `Pie`,
    description: `Donut pie. The legend wraps to two rows on narrow widths so the chart never overflows its container.`,
  },
  radar: {
    title: `Radar`,
    description: `Polar radar with two overlaid series. The dashed series is rendered without fill so the solid layer reads as the primary signal.`,
  },
  radial: {
    title: `Radial`,
    description: `Radial bar with a muted background ring. Each ring is a slice from the same dataset, coloured via the <ChartConfig> palette.`,
  },
  themed: {
    title: `Themed colours`,
    description: `Uses the <ChartConfig> "theme" shape to pick a different colour in light vs. dark mode — flip the app theme and the same series re-paints with no JS work.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the package (recharts ships as a transitive dependency):`,
      manualStep2: `Copy a chart from the examples below and adjust the <ChartConfig> to match your series.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<ChartContainer> wraps any recharts chart, injects per-series CSS colour variables, and provides the context that <ChartTooltipContent> and <ChartLegendContent> read to resolve labels. The config map is the single source of truth for series colours and display names.`,
    },
    composition: {
      title: `Composition`,
      body: `Colours flow as CSS custom properties so the same chart can re-skin under light vs. dark themes without re-rendering. Use the "theme" shape on a config entry to provide per-theme values; use "color" when one shared value is enough.`,
    },
    examples: {
      title: `Examples`,
      bar: {
        title: `Bar`,
        description: `Grouped bars driven by two series in the <ChartConfig>.`,
      },
      line: {
        title: `Line`,
        description: `Single-series line with a custom tooltip indicator.`,
      },
      area: {
        title: `Area`,
        description: `Stacked area with per-series gradients defined in <defs>.`,
      },
      pie: {
        title: `Pie`,
        description: `Donut pie with a legend that wraps across narrow widths.`,
      },
      radar: {
        title: `Radar`,
        description: `Polar radar overlaying current vs. target.`,
      },
      radial: {
        title: `Radial`,
        description: `Radial bar showing each datum as a coloured ring.`,
      },
      themed: {
        title: `Themed colours`,
        description: `Per-theme colour values that flip with the app theme.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how the chart primitive is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        rendersWrapper: `Renders a <div data-slot="chart"> wrapper that owns the chart's CSS scope.`,
        stableDataChartId: `Tags the wrapper with a stable data-chart="chart-…" id derived from the id prop or React useId.`,
        forwardsClassName: `Merges the consumer's className onto the wrapper without dropping the base classes.`,
        emitsStyleVars: `Emits a <style> block that defines "--color-<key>" custom properties for every config entry that has a color or theme.`,
        mountsRecharts: `Mounts a recharts subtree (BarChart + Tooltip + Bar) inside the container without throwing.`,
        styleNothingWithoutColor: `<ChartStyle> renders nothing when no config entry declares a color or theme.`,
        styleThemeScopes: `<ChartStyle> emits one rule for the light theme and one ".dark"-scoped rule for the dark theme.`,
        tooltipInactive: `<ChartTooltipContent> renders nothing when not active.`,
        tooltipRendersLabel: `<ChartTooltipContent> renders the configured label and the formatted (toLocaleString) value for each payload entry.`,
        legendEmptyPayload: `<ChartLegendContent> renders nothing when its payload is empty.`,
        legendRendersRows: `<ChartLegendContent> renders one row per payload entry and reads the display label from the config.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Recharts lays out left-to-right; the wrapper and tooltip flip under dir="rtl" but the axes themselves are direction-agnostic.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by the chart primitives.`,
    },
  },
};

export const chartDe: ChartTranslation = {
  bar: {
    title: `Balken`,
    description: `Gruppierte Balken auf einer gemeinsamen X-Achse. Serienfarben stammen aus dem <ChartConfig>; Tooltip und Legende lesen die Beschriftungen aus derselben Map.`,
  },
  line: {
    title: `Linie`,
    description: `Weiche monotone Linie. Der Tooltip nutzt einen „line“-Indikator, dessen Farbe der Linienfarbe entspricht.`,
  },
  area: {
    title: `Fläche`,
    description: `Gestapelte Fläche mit Verlauf pro Serie. <defs> definiert die Gradienten; die Serien referenzieren sie über fill="url(#…)".`,
  },
  pie: {
    title: `Kreis`,
    description: `Donut-Diagramm. Die Legende bricht auf schmalen Breiten in zwei Reihen um, damit das Diagramm nie aus dem Container läuft.`,
  },
  radar: {
    title: `Radar`,
    description: `Polar-Radar mit zwei überlagerten Serien. Die gestrichelte Serie wird ohne Füllung gezeichnet, damit die durchgezogene als primäres Signal wirkt.`,
  },
  radial: {
    title: `Radial`,
    description: `Radialer Balken mit gedämpftem Hintergrund-Ring. Jeder Ring entspricht einem Datensatz und nutzt die Palette aus dem <ChartConfig>.`,
  },
  themed: {
    title: `Themen-Farben`,
    description: `Nutzt die „theme“-Form eines <ChartConfig>-Eintrags, um im hellen und dunklen Modus unterschiedliche Farben zu wählen — beim Theme-Wechsel wird die Serie ohne JS neu eingefärbt.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere das Paket (recharts wird als transitives Paket mitgeliefert):`,
      manualStep2: `Kopiere ein Beispiel von unten und passe das <ChartConfig> an deine Serien an.`,
      manualStep3: `Passe die Import-Pfade an deine Projektstruktur an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<ChartContainer> umschließt jedes recharts-Diagramm, injiziert pro Serie CSS-Farbvariablen und stellt den Kontext bereit, aus dem <ChartTooltipContent> und <ChartLegendContent> die Beschriftungen ableiten. Die Config-Map ist die einzige Quelle für Serienfarben und Anzeigenamen.`,
    },
    composition: {
      title: `Komposition`,
      body: `Farben fließen als CSS-Custom-Properties — dieselbe Komponente kann unter hellem und dunklem Theme neu eingefärbt werden, ohne neu zu rendern. Nutze die „theme“-Form eines Config-Eintrags für getrennte Werte pro Theme oder „color“ für einen gemeinsamen Wert.`,
    },
    examples: {
      title: `Beispiele`,
      bar: {
        title: `Balken`,
        description: `Gruppierte Balken mit zwei Serien aus dem <ChartConfig>.`,
      },
      line: {
        title: `Linie`,
        description: `Einzelne Linie mit angepasstem Tooltip-Indikator.`,
      },
      area: {
        title: `Fläche`,
        description: `Gestapelte Fläche mit Verläufen pro Serie aus <defs>.`,
      },
      pie: {
        title: `Kreis`,
        description: `Donut-Pie mit umbrechender Legende auf schmalen Breiten.`,
      },
      radar: {
        title: `Radar`,
        description: `Polar-Radar, das Ist- und Zielwerte überlagert.`,
      },
      radial: {
        title: `Radial`,
        description: `Radialer Balken, der jeden Datensatz als farbigen Ring zeigt.`,
      },
      themed: {
        title: `Themen-Farben`,
        description: `Theme-spezifische Farben, die mit dem App-Theme wechseln.`,
      },
    },
    definedBehaviour: {
      title: `Definiertes Verhalten`,
      intro: `Aussagen darüber, wie sich die Chart-Primitive verhalten — jede verlinkt mit dem Test, der sie verifiziert.`,
      verifiedBy: `verifiziert durch`,
      statements: {
        rendersWrapper: `Rendert einen <div data-slot="chart">-Wrapper, der den CSS-Scope des Diagramms besitzt.`,
        stableDataChartId: `Setzt am Wrapper eine stabile data-chart="chart-…"-ID, abgeleitet aus der id-Prop oder React useId.`,
        forwardsClassName: `Fügt die vom Aufrufer übergebene className zu den Basis-Klassen hinzu, ohne sie zu überschreiben.`,
        emitsStyleVars: `Gibt einen <style>-Block aus, der „--color-<key>“-Custom-Properties für jeden Config-Eintrag mit color oder theme definiert.`,
        mountsRecharts: `Mountet einen recharts-Teilbaum (BarChart + Tooltip + Bar) innerhalb des Containers ohne Fehler.`,
        styleNothingWithoutColor: `<ChartStyle> rendert nichts, wenn kein Config-Eintrag color oder theme definiert.`,
        styleThemeScopes: `<ChartStyle> erzeugt eine Regel für das helle und eine „.dark“-gescopte Regel für das dunkle Theme.`,
        tooltipInactive: `<ChartTooltipContent> rendert nichts, wenn nicht aktiv.`,
        tooltipRendersLabel: `<ChartTooltipContent> rendert die konfigurierte Beschriftung und den formatierten (toLocaleString) Wert pro Payload-Eintrag.`,
        legendEmptyPayload: `<ChartLegendContent> rendert nichts, wenn die Payload leer ist.`,
        legendRendersRows: `<ChartLegendContent> rendert eine Zeile pro Payload-Eintrag und liest die Beschriftung aus der Config.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Recharts ordnet von links nach rechts an; Wrapper und Tooltip kippen unter dir="rtl", die Achsen selbst sind richtungs-agnostisch.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die die Chart-Primitive akzeptieren.`,
    },
  },
};
