/**
 * Translation slice for modalHandler.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to modalHandler's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface ModalHandlerTranslation {
  default: { title: string; description: string };
  imperative: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
      imperative: { title: string; description: string };
    };
    imperativeApi: {
      title: string;
      intro: string;
      whenToUse: string;
      bannedNote: string;
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        invisibleWhenNoModal: string;
        themeSelector: string;
        languageSelector: string;
        keyboardShortcutEditor: string;
        customModal: string;
        imperativeConfirm: string;
        imperativeAlert: string;
        imperativePrompt: string;
        imperativeQueue: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const modalHandlerEn: ModalHandlerTranslation = {
  default: {
    title: `Default`,
    description: `Click a button to open one of the core modals; ModalHandler reads MowsContext.currentlyOpenModal and renders the matching dialog.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<ModalHandler> is mounted once globally inside <MowsProvider>. It listens to currentlyOpenModal and renders the matching core dialog (theme / language / keyboard shortcuts / code theme / settings).`,
    },
    composition: {
      title: `Composition`,
      body: `Register app-specific dialogs via extraModals. Open any modal by calling mowsContext.changeActiveModal(id).`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Default`,
        description: `Trigger the theme, language, and keyboard-shortcut modals through the action manager.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <ModalHandler> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        invisibleWhenNoModal: `Renders nothing visible when no modal is active.`,
        themeSelector: `Renders the theme-selector dialog when modal=themeSelector.`,
        languageSelector: `Renders the language-selector dialog when modal=languageSelector.`,
        keyboardShortcutEditor: `Renders the keyboard-shortcut editor when modal=keyboardShortcutEditor.`,
        customModal: `Renders a custom modal supplied via extraModals.`,
      },
    },
    rtl: { title: `RTL`, body: `Dialog content mirrors under dir="rtl".` },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <ModalHandler>.`,
    },
  },
};

export const modalHandlerDe: ModalHandlerTranslation = {
  default: {
    title: `Standard`,
    description: `Klicke eine Schaltfläche, um einen der Kern-Dialoge zu öffnen; ModalHandler liest MowsContext.currentlyOpenModal und rendert den passenden Dialog.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Import-Pfade an deine Projektstruktur an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<ModalHandler> wird einmal global innerhalb von <MowsProvider> eingebunden. Er beobachtet currentlyOpenModal und rendert den passenden Kerndialog (Theme / Sprache / Tastenkürzel / Code-Theme / Einstellungen).`,
    },
    composition: {
      title: `Komposition`,
      body: `Registriere app-spezifische Dialoge über extraModals. Öffne jeden Modal mit mowsContext.changeActiveModal(id).`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Standard`,
        description: `Löse die Theme-, Sprach- und Tastenkürzel-Dialoge über den Action Manager aus.`,
      },
    },
    definedBehaviour: {
      title: `Definiertes Verhalten`,
      intro: `Aussagen darüber, wie sich <ModalHandler> verhalten soll — jede verlinkt mit dem Test, der sie verifiziert.`,
      verifiedBy: `verifiziert durch`,
      statements: {
        invisibleWhenNoModal: `Rendert nichts Sichtbares, wenn kein Modal aktiv ist.`,
        themeSelector: `Rendert den Theme-Auswahl-Dialog bei modal=themeSelector.`,
        languageSelector: `Rendert den Sprach-Auswahl-Dialog bei modal=languageSelector.`,
        keyboardShortcutEditor: `Rendert den Tastenkürzel-Editor bei modal=keyboardShortcutEditor.`,
        customModal: `Rendert einen über extraModals bereitgestellten, benutzerdefinierten Modal.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Der Dialoginhalt wird unter dir="rtl" gespiegelt.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <ModalHandler> akzeptiert.`,
    },
  },
};
