// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dzi } from "./Dzi";

export interface ProcessedImage { width: number, height: number, resolutions: Array<number>, dzi: Dzi | null, }