// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileGroupType } from "./FileGroupType";
import type { FilterRule } from "./FilterRule";

export interface UpdateFileGroupInfosRequestField { name: string | null, dynamic_group_rules: FilterRule | null, group_type: FileGroupType | null, keywords: Array<string> | null, mime_types: Array<string> | null, group_hierarchy_paths: Array<string> | null, permission_ids: Array<string> | null, }