/**
 * Translation slice for machineMonitor.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to machineMonitor's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface MachineMonitorTranslation {
    default: { title: string; description: string };
    readOnly: { title: string; description: string };
    doc: {
        installation: {
            title: string;
            commandTab: string;
            manualTab: string;
            manualStep1: string;
            manualStep2: string;
            manualStep3: string;
        };
        usage: { title: string; body: string };
        composition: { title: string; body: string };
        examples: {
            title: string;
            default: { title: string; description: string };
            readOnly: { title: string; description: string };
        };
        definedBehaviour: {
            title: string;
            intro: string;
            verifiedBy: string;
            statements: {
                remountsOnUrl: string;
                readOnlyForcesViewOnly: string;
                readOnlyPointerEventsNone: string;
                noPointerEventsWithoutReadOnly: string;
                preservesExplicitViewOnly: string;
            };
        };
        rtl: { title: string; body: string };
        apiReference: { title: string; intro: string };
    };
}

export const machineMonitorEn: MachineMonitorTranslation = {
    default: {
        title: `Connect to a VNC server`,
        description: `Paste a ws:// or wss:// URL and click Connect. The viewer lazy-loads the react-vnc bundle on the first connection.`
    },
    readOnly: {
        title: `Read-only preview`,
        description: `readOnly implies viewOnly AND prevents auto-focus on hover, suppresses the dot cursor, and lets the page scroll through the canvas.`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Command`,
            manualTab: `Manual`,
            manualStep1: `Install the following dependencies:`,
            manualStep2: `Copy and paste the following code into your project.`,
            manualStep3: `Update the import paths to match your project setup.`
        },
        usage: {
            title: `Usage`,
            body: `<MachineMonitor> is a lazy-loaded react-vnc / @novnc/novnc wrapper. Provide either url or a pre-constructed websocket; everything else is driven through the imperative MachineMonitorHandle.`
        },
        composition: {
            title: `Composition`,
            body: `<MachineMonitor> wraps the VncScreen with a Suspense fallback, optional pointer-events suppression for readOnly previews, and an imperative handle that exposes connect / disconnect / sendCtrlAltDel / clipboardPaste / shutdown / reboot / reset.`
        },
        examples: {
            title: `Examples`,
            default: {
                title: `Live connection`,
                description: `Enter a ws:// URL and connect. The example in the docs has no server attached.`
            },
            readOnly: {
                title: `Read-only preview`,
                description: `readOnly forces viewOnly and suppresses pointer events.`
            }
        },
        definedBehaviour: {
            title: `Defined behaviour`,
            intro: `Statements describing how <MachineMonitor> is expected to behave, each linked to the test that verifies it.`,
            verifiedBy: `verified by`,
            statements: {
                remountsOnUrl: `Remounts the inner VncScreen when the url prop changes.`,
                readOnlyForcesViewOnly: `readOnly forces viewOnly + disables focusOnClick and the dot cursor.`,
                readOnlyPointerEventsNone: `readOnly wraps the canvas in a pointer-events:none element so the page can scroll through it.`,
                noPointerEventsWithoutReadOnly: `Does not set pointer-events:none when readOnly is omitted.`,
                preservesExplicitViewOnly: `Preserves an explicit viewOnly prop when readOnly is not set.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `The remote framebuffer is the server's responsibility; the wrapper is direction-agnostic.`
        },
        apiReference: {
            title: `API Reference`,
            intro: `Props accepted by <MachineMonitor> and the MachineMonitorHandle exposed via ref.`
        }
    }
};

export const machineMonitorDe: MachineMonitorTranslation = {
    default: {
        title: `Mit einem VNC-Server verbinden`,
        description: `Füge eine ws://- oder wss://-URL ein und klicke „Connect". Der Viewer lädt das react-vnc-Bundle bei der ersten Verbindung.`
    },
    readOnly: {
        title: `Read-only-Vorschau`,
        description: `readOnly impliziert viewOnly UND verhindert Auto-Focus beim Hover, unterdrückt den Punkt-Cursor und lässt die Seite durch das Canvas scrollen.`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Befehl`,
            manualTab: `Manuell`,
            manualStep1: `Installiere die folgenden Abhängigkeiten:`,
            manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
            manualStep3: `Passe die Importpfade an dein Projekt an.`
        },
        usage: {
            title: `Verwendung`,
            body: `<MachineMonitor> ist ein lazy geladener react-vnc-/@novnc/novnc-Wrapper. Übergib entweder url oder einen vorab konstruierten websocket; alles weitere läuft über das imperative MachineMonitorHandle.`
        },
        composition: {
            title: `Komposition`,
            body: `<MachineMonitor> kapselt das VncScreen mit einem Suspense-Fallback, optionaler pointer-events-Unterdrückung für readOnly-Vorschauen und einem imperativen Handle (connect / disconnect / sendCtrlAltDel / clipboardPaste / shutdown / reboot / reset).`
        },
        examples: {
            title: `Beispiele`,
            default: {
                title: `Live-Verbindung`,
                description: `Gib eine ws://-URL ein und verbinde dich. In der Doku ist kein Server angeschlossen.`
            },
            readOnly: {
                title: `Read-only-Vorschau`,
                description: `readOnly erzwingt viewOnly und unterdrückt Pointer-Events.`
            }
        },
        definedBehaviour: {
            title: `Festgelegtes Verhalten`,
            intro: `Aussagen darüber, wie sich <MachineMonitor> verhalten soll, jeweils mit Verweis auf den Test.`,
            verifiedBy: `geprüft durch`,
            statements: {
                remountsOnUrl: `Mountet das innere VncScreen neu, wenn sich das url-Prop ändert.`,
                readOnlyForcesViewOnly: `readOnly erzwingt viewOnly + deaktiviert focusOnClick und den Punkt-Cursor.`,
                readOnlyPointerEventsNone: `readOnly umschließt das Canvas mit einem pointer-events:none-Element, sodass die Seite hindurchscrollen kann.`,
                noPointerEventsWithoutReadOnly: `Setzt pointer-events:none nicht, wenn readOnly weggelassen wird.`,
                preservesExplicitViewOnly: `Behält ein explizit gesetztes viewOnly bei, wenn readOnly nicht gesetzt ist.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `Das Remote-Framebuffer liegt in der Verantwortung des Servers; der Wrapper ist richtungsneutral.`
        },
        apiReference: {
            title: `API-Referenz`,
            intro: `Props, die <MachineMonitor> akzeptiert, sowie das via ref bereitgestellte MachineMonitorHandle.`
        }
    }
};
