/*
 * mows-package-manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRepositoriesResBody {
    #[serde(rename = "repositories")]
    pub repositories: Vec<models::Repository>,
}

impl GetRepositoriesResBody {
    pub fn new(repositories: Vec<models::Repository>) -> GetRepositoriesResBody {
        GetRepositoriesResBody {
            repositories,
        }
    }
}

