/*
 * mows-package-manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenderRepositoriesRepositorySelectorOneOf1 {
    #[serde(rename = "Direct")]
    pub direct: Box<models::NewRepository>,
}

impl RenderRepositoriesRepositorySelectorOneOf1 {
    pub fn new(direct: models::NewRepository) -> RenderRepositoriesRepositorySelectorOneOf1 {
        RenderRepositoriesRepositorySelectorOneOf1 {
            direct: Box::new(direct),
        }
    }
}

