/*
 * mows-package-manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenderRepositoriesTargetOneOf2 {
    #[serde(rename = "Git")]
    pub git: serde_json::Value,
}

impl RenderRepositoriesTargetOneOf2 {
    pub fn new(git: serde_json::Value) -> RenderRepositoriesTargetOneOf2 {
        RenderRepositoriesTargetOneOf2 {
            git,
        }
    }
}

