/*
 * mows-package-manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenderRepositoriesTargetOneOf1 {
    #[serde(rename = "KubectlApply")]
    pub kubectl_apply: Box<models::RenderRepositoriesTargetKubectlApply>,
}

impl RenderRepositoriesTargetOneOf1 {
    pub fn new(kubectl_apply: models::RenderRepositoriesTargetKubectlApply) -> RenderRepositoriesTargetOneOf1 {
        RenderRepositoriesTargetOneOf1 {
            kubectl_apply: Box::new(kubectl_apply),
        }
    }
}

