/*
 * mows-package-manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenderRepositoriesRepository {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "secrets", skip_serializing_if = "Option::is_none")]
    pub secrets: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "target")]
    pub target: Box<models::RenderRepositoriesTarget>,
}

impl RenderRepositoriesRepository {
    pub fn new(id: i32, namespace: String, target: models::RenderRepositoriesTarget) -> RenderRepositoriesRepository {
        RenderRepositoriesRepository {
            id,
            namespace,
            secrets: None,
            target: Box::new(target),
        }
    }
}

