/**
 * Translation slice for sectionHeading.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to sectionHeading's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface SectionHeadingTranslation {
    default: { title: string; description: string };
    levels: { title: string; description: string };
    doc: {
        installation: {
            title: string;
            commandTab: string;
            manualTab: string;
            manualStep1: string;
            manualStep2: string;
            manualStep3: string;
        };
        usage: { title: string; body: string };
        composition: { title: string; body: string };
        examples: {
            title: string;
            default: { title: string; description: string };
            levels: { title: string; description: string };
        };
        definedBehaviour: {
            title: string;
            intro: string;
            verifiedBy: string;
            statements: {
                rendersLevel: string;
                defaultsToH2: string;
                anchorHref: string;
                pushesHash: string;
                noDuplicateHistory: string;
                preventsDefaultScroll: string;
                hoverUnderlineText: string;
                dimMarker: string;
            };
        };
        rtl: { title: string; body: string };
        apiReference: { title: string; intro: string };
    };
}

export const sectionHeadingEn: SectionHeadingTranslation = {
    default: {
        title: `Default`,
        description: `A single permalink heading. Hover the text to underline it and reveal the muted # marker; clicking pushes #<id> to the URL.`
    },
    levels: {
        title: `Levels`,
        description: `One <SectionHeading> per heading level (h1–h6). The component renders the requested level via React.createElement; styling is the consumer's responsibility (via className).`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Command`,
            manualTab: `Manual`,
            manualStep1: `Install the following dependencies:`,
            manualStep2: `Copy and paste the following code into your project.`,
            manualStep3: `Update the import paths to match your project setup.`
        },
        usage: {
            title: `Usage`,
            body: `Import <SectionHeading> from the package and render it with an id (becomes the URL hash on click) and the heading level. Style the heading via className.`
        },
        composition: {
            title: `Composition`,
            body: `<SectionHeading> is a thin wrapper around the native <hN> element. It owns the anchor link, the hash push on click, and the hover-underline + dim # marker affordance. Visual styling is left to the consumer.`
        },
        examples: {
            title: `Examples`,
            default: {
                title: `Default`,
                description: `A single h2 heading with the standard hover affordance.`
            },
            levels: {
                title: `Levels`,
                description: `All six heading levels rendered side by side.`
            }
        },
        definedBehaviour: {
            title: `Defined behaviour`,
            intro: `Statements describing how <SectionHeading> is expected to behave, each linked to the test that verifies it.`,
            verifiedBy: `verified by`,
            statements: {
                rendersLevel: `Renders the requested heading level (h1–h6) with the given id.`,
                defaultsToH2: `Defaults to h2 when no level is provided.`,
                anchorHref: `Wraps its text in an anchor whose href matches the id.`,
                pushesHash: `Clicking the heading pushes #<id> to the URL via history.pushState.`,
                noDuplicateHistory: `Does not push a duplicate history entry when the hash is already current.`,
                preventsDefaultScroll: `Prevents the browser's default scroll so scrollToSection can run.`,
                hoverUnderlineText: `Underlines only the heading text on hover, not the # marker.`,
                dimMarker: `Renders a dim # marker that appears on hover and is not underlined.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `Headings inherit direction from their DOM ancestor — wrap in dir="rtl" and the # marker flips to the start of the heading.`
        },
        apiReference: {
            title: `API Reference`,
            intro: `Props accepted by <SectionHeading>.`
        }
    }
};

export const sectionHeadingDe: SectionHeadingTranslation = {
    default: {
        title: `Standard`,
        description: `Eine einzelne Permalink-Überschrift. Hover über den Text unterstreicht ihn und zeigt die gedämpfte #-Markierung; ein Klick schreibt #<id> in die URL.`
    },
    levels: {
        title: `Ebenen`,
        description: `Ein <SectionHeading> pro Überschriftenebene (h1–h6). Die Komponente rendert die gewünschte Ebene per React.createElement; das Styling liegt beim Konsumenten (via className).`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Befehl`,
            manualTab: `Manuell`,
            manualStep1: `Installiere die folgenden Abhängigkeiten:`,
            manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
            manualStep3: `Passe die Importpfade an dein Projekt an.`
        },
        usage: {
            title: `Verwendung`,
            body: `Importiere <SectionHeading> aus dem Paket und rendere es mit einer id (wird beim Klick zur URL-Hash) und der Überschriften-Ebene. Style die Überschrift via className.`
        },
        composition: {
            title: `Komposition`,
            body: `<SectionHeading> ist ein schlanker Wrapper um das native <hN>-Element. Es besitzt den Anker-Link, das Setzen der Hash beim Klick und die Hover-Unterstreichung + gedämpfte #-Markierung. Die visuelle Gestaltung bleibt beim Konsumenten.`
        },
        examples: {
            title: `Beispiele`,
            default: {
                title: `Standard`,
                description: `Eine einzelne h2-Überschrift mit der Standard-Hover-Affordanz.`
            },
            levels: {
                title: `Ebenen`,
                description: `Alle sechs Überschriften-Ebenen nebeneinander gerendert.`
            }
        },
        definedBehaviour: {
            title: `Festgelegtes Verhalten`,
            intro: `Aussagen darüber, wie sich <SectionHeading> verhalten soll, jeweils mit Verweis auf den Test.`,
            verifiedBy: `geprüft durch`,
            statements: {
                rendersLevel: `Rendert die angeforderte Überschriftenebene (h1–h6) mit der angegebenen id.`,
                defaultsToH2: `Verwendet h2 als Standard, wenn keine Ebene angegeben ist.`,
                anchorHref: `Wickelt den Text in einen Anker, dessen href zur id passt.`,
                pushesHash: `Ein Klick auf die Überschrift schreibt #<id> per history.pushState in die URL.`,
                noDuplicateHistory: `Erzeugt keinen doppelten History-Eintrag, wenn die Hash bereits aktuell ist.`,
                preventsDefaultScroll: `Verhindert das Default-Scrollen des Browsers, damit scrollToSection greift.`,
                hoverUnderlineText: `Unterstreicht beim Hover nur den Überschriftentext, nicht die #-Markierung.`,
                dimMarker: `Rendert eine gedämpfte #-Markierung, die beim Hover erscheint und nicht unterstrichen wird.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `Überschriften erben die Richtung vom DOM-Vorfahren — ein umgebendes dir="rtl" verschiebt die #-Markierung an den Anfang der Überschrift.`
        },
        apiReference: {
            title: `API-Referenz`,
            intro: `Props, die <SectionHeading> akzeptiert.`
        }
    }
};
