/**
 * Translation slice for inputGroup.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to inputGroup's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface InputGroupTranslation {
    default: { title: string; description: string };
    trailingAddon: { title: string; description: string };
    doc: {
        installation: {
            title: string;
            commandTab: string;
            manualTab: string;
            manualStep1: string;
            manualStep2: string;
            manualStep3: string;
        };
        usage: { title: string; body: string };
        composition: { title: string; body: string };
        examples: {
            title: string;
            default: { title: string; description: string };
            trailingAddon: { title: string; description: string };
        };
        definedBehaviour: {
            title: string;
            intro: string;
            verifiedBy: string;
            statements: {
                rendersGroup: string;
                focusOnAddonClick: string;
                alignInlineEnd: string;
                alignDefault: string;
                forwardsAriaInvalid: string;
            };
        };
        rtl: { title: string; body: string };
        apiReference: { title: string; intro: string };
    };
}

export const inputGroupEn: InputGroupTranslation = {
    default: {
        title: `Leading icon`,
        description: `An <InputGroupAddon> before the input acts as a leading icon. Clicking the addon focuses the input.`
    },
    trailingAddon: {
        title: `Trailing addon`,
        description: `Place a trailing addon (e.g. currency code) by setting align="inline-end" on the addon — the order order-last class moves it to the end of the flex row.`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Command`,
            manualTab: `Manual`,
            manualStep1: `Install the following dependencies:`,
            manualStep2: `Copy and paste the following code into your project.`,
            manualStep3: `Update the import paths to match your project setup.`
        },
        usage: {
            title: `Usage`,
            body: `<InputGroup> composes <InputGroupAddon> and <InputGroupInput>. Addons can be icons, buttons, or styled text via <InputGroupButton> / <InputGroupText>.`
        },
        composition: {
            title: `Composition`,
            body: `Place the addon before the input for leading content, after for trailing — and set align="inline-end" on trailing addons so they sit at the end of the row.`
        },
        examples: {
            title: `Examples`,
            default: {
                title: `Leading icon`,
                description: `Search icon followed by the input.`
            },
            trailingAddon: {
                title: `Trailing addon`,
                description: `Numeric input + EUR suffix.`
            }
        },
        definedBehaviour: {
            title: `Defined behaviour`,
            intro: `Statements describing how <InputGroup> is expected to behave, each linked to the test that verifies it.`,
            verifiedBy: `verified by`,
            statements: {
                rendersGroup: `Renders a role="group" wrapper with the input and leading addon.`,
                focusOnAddonClick: `Focuses the inner input when the addon is clicked.`,
                alignInlineEnd: `align="inline-end" places the addon last (data-align attribute + order-last class).`,
                alignDefault: `Addon align defaults to inline-start when omitted.`,
                forwardsAriaInvalid: `Forwards aria-invalid onto the inner input.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `Under dir="rtl" the leading addon flips to the right of the input; align="inline-end" addons follow accordingly.`
        },
        apiReference: {
            title: `API Reference`,
            intro: `Props accepted by <InputGroup> and <InputGroupAddon>.`
        }
    }
};

export const inputGroupDe: InputGroupTranslation = {
    default: {
        title: `Führendes Icon`,
        description: `Ein <InputGroupAddon> vor dem Input wirkt wie ein führendes Icon. Klick auf das Addon fokussiert das Input.`
    },
    trailingAddon: {
        title: `Nachgestelltes Addon`,
        description: `Nachgestellte Addons (z. B. Währungs-Code) mit align="inline-end" auf dem Addon — order-last verschiebt es ans Ende der Flex-Zeile.`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Befehl`,
            manualTab: `Manuell`,
            manualStep1: `Installiere die folgenden Abhängigkeiten:`,
            manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
            manualStep3: `Passe die Importpfade an dein Projekt an.`
        },
        usage: {
            title: `Verwendung`,
            body: `<InputGroup> kombiniert <InputGroupAddon> und <InputGroupInput>. Addons können Icons, Buttons oder gestylter Text via <InputGroupButton> / <InputGroupText> sein.`
        },
        composition: {
            title: `Komposition`,
            body: `Addon vor dem Input für führenden Inhalt, danach für nachgestellten — bei nachgestellten Addons align="inline-end" setzen.`
        },
        examples: {
            title: `Beispiele`,
            default: {
                title: `Führendes Icon`,
                description: `Such-Icon vor dem Input.`
            },
            trailingAddon: {
                title: `Nachgestelltes Addon`,
                description: `Numerisches Input + EUR-Suffix.`
            }
        },
        definedBehaviour: {
            title: `Festgelegtes Verhalten`,
            intro: `Aussagen darüber, wie sich <InputGroup> verhalten soll, jeweils mit Verweis auf den Test.`,
            verifiedBy: `geprüft durch`,
            statements: {
                rendersGroup: `Rendert einen role="group"-Wrapper mit Input und führendem Addon.`,
                focusOnAddonClick: `Fokussiert das innere Input beim Klick auf das Addon.`,
                alignInlineEnd: `align="inline-end" platziert das Addon zuletzt (data-align-Attribut + order-last).`,
                alignDefault: `Addon-align ist standardmäßig inline-start, wenn weggelassen.`,
                forwardsAriaInvalid: `Reicht aria-invalid ans innere Input durch.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `Unter dir="rtl" wandert das führende Addon nach rechts vom Input; align="inline-end"-Addons folgen entsprechend.`
        },
        apiReference: {
            title: `API-Referenz`,
            intro: `Props, die <InputGroup> und <InputGroupAddon> akzeptieren.`
        }
    }
};
