// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateFileResponse { file_id: string, storage_name: string, sha256: string, }