// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserGroupVisibility } from "./UserGroupVisibility";

export interface FilezUserGroup { _id: string, name: string | null, owner_id: string, visibility: UserGroupVisibility, permission_ids: Array<string>, }