// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessedImage } from "./ProcessedImage";

export interface Image { result: ProcessedImage | null, started_at: bigint | null, finished_at: bigint | null, error: string | null, rescan: boolean | null, }