// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilezFileGroupPermissionAclWhatOptions } from "./FilezFileGroupPermissionAclWhatOptions";
import type { FilezFilePermissionAclWhatOptions } from "./FilezFilePermissionAclWhatOptions";
import type { FilezPermissionResource } from "./FilezPermissionResource";
import type { FilezUserGroupPermissionAclWhatOptions } from "./FilezUserGroupPermissionAclWhatOptions";
import type { FilezUserPermissionAclWhatOptions } from "./FilezUserPermissionAclWhatOptions";

export type PermissionResourceType = { "type": "File" } & FilezPermissionResource<FilezFilePermissionAclWhatOptions> | { "type": "FileGroup" } & FilezPermissionResource<FilezFileGroupPermissionAclWhatOptions> | { "type": "UserGroup" } & FilezPermissionResource<FilezUserGroupPermissionAclWhatOptions> | { "type": "User" } & FilezPermissionResource<FilezUserPermissionAclWhatOptions>;