// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppDataType } from "./AppDataType";

export interface SetAppDataRequest { app_data_type: AppDataType, id: string, app_name: string, app_data: any, }