services:
    chat-db:
        image: postgres:latest
        container_name: chat-db
        environment:
            POSTGRES_USER: chat
            POSTGRES_PASSWORD: chat
            POSTGRES_DB: chat
        ports:
            - "127.0.0.1:5433:5432"
