//! Hand-curated diesel schema for realtime-server.
//!
//! Mirrors filez's pattern: schema.rs is NOT regenerated by
//! `diesel print-schema`. Each table's columns line up with the
//! migration SQL; array columns use non-nullable element types
//! (Postgres allows NULL elements in array literals but our
//! migrations never produce them, and diesel-cli's auto-generation
//! over-typing them as Nullable<T> breaks the lib build —
//! lesson learned during filez Phase 5 work).

diesel::table! {
    idp_providers (id) {
        id -> Uuid,
        name -> Text,
        discovery_url -> Nullable<Text>,
        created_time -> Timestamp,
    }
}

diesel::table! {
    users (id) {
        id -> Uuid,
        external_user_id -> Nullable<Text>,
        display_name -> Text,
        created_time -> Timestamp,
        modified_time -> Timestamp,
        deleted -> Bool,
        user_type -> SmallInt,
        idp_id -> Uuid,
    }
}
diesel::joinable!(users -> idp_providers (idp_id));

diesel::table! {
    apps (id) {
        id -> Uuid,
        name -> Text,
        description -> Nullable<Text>,
        origins -> Nullable<Array<Text>>,
        trusted -> Bool,
        app_type -> SmallInt,
        created_time -> Timestamp,
        modified_time -> Timestamp,
        idp_id -> Uuid,
        external_client_id -> Nullable<Text>,
    }
}
diesel::joinable!(apps -> idp_providers (idp_id));

diesel::table! {
    access_policies (id) {
        id -> Uuid,
        owner_id -> Uuid,
        name -> Text,
        created_time -> Timestamp,
        modified_time -> Timestamp,
        subject_type -> SmallInt,
        subject_id -> Uuid,
        context_app_ids -> Array<Uuid>,
        resource_type -> SmallInt,
        resource_id -> Nullable<Uuid>,
        actions -> Array<SmallInt>,
        effect -> SmallInt,
        resource_scope -> SmallInt,
        expires_at -> Nullable<Timestamp>,
        revoked -> Bool,
        policy_bundle_id -> Nullable<Uuid>,
    }
}
diesel::joinable!(access_policies -> users (owner_id));

diesel::table! {
    user_groups (id) {
        id -> Uuid,
        owner_id -> Uuid,
        name -> Text,
        created_time -> Timestamp,
        modified_time -> Timestamp,
    }
}
diesel::joinable!(user_groups -> users (owner_id));

diesel::table! {
    user_user_group_members (user_id, user_group_id) {
        user_id -> Uuid,
        user_group_id -> Uuid,
        joined_at -> Timestamp,
    }
}
diesel::joinable!(user_user_group_members -> user_groups (user_group_id));
diesel::joinable!(user_user_group_members -> users (user_id));

diesel::table! {
    channels (id) {
        id -> Uuid,
        owner_id -> Uuid,
        name -> Text,
        topic -> Nullable<Text>,
        created_time -> Timestamp,
        modified_time -> Timestamp,
    }
}
diesel::joinable!(channels -> users (owner_id));

diesel::table! {
    channel_events (id) {
        id -> Uuid,
        channel_id -> Uuid,
        author_id -> Uuid,
        event_kind -> Nullable<Text>,
        payload -> Jsonb,
        sent_at -> Timestamp,
    }
}
diesel::joinable!(channel_events -> channels (channel_id));
diesel::joinable!(channel_events -> users (author_id));

diesel::allow_tables_to_appear_in_same_query!(
    idp_providers,
    users,
    apps,
    access_policies,
    user_groups,
    user_user_group_members,
    channels,
    channel_events,
);
