services:
    realtime-db:
        image: postgres:latest
        container_name: realtime-db
        environment:
            POSTGRES_USER: realtime
            POSTGRES_PASSWORD: realtime
            POSTGRES_DB: realtime
        ports:
            - "127.0.0.1:5433:5432"
