/**
 * Translation slice for settingsPanel.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to settingsPanel's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface SettingsPanelTranslation {
  default: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    appExtension: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        threeHeadings: string;
        standalonePickersShowCurrent: string;
        jsonTabShowsSettings: string;
        jsonSaveAppliesEdit: string;
        jsonRejectsBadVersion: string;
        notificationsSection: string;
        jsonIncludesToast: string;
        toastPositionFromJson: string;
        bracketPairToggle: string;
        appSectionWhenRegistered: string;
        jsonErrorOnInvalid: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const settingsPanelEn: SettingsPanelTranslation = {
  default: {
    title: `Default`,
    description: `Three sections: Appearance, Code editor, Language. A second tab exposes the live JSON so power-users can paste a settings blob.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `Mount <SettingsPanel> inside <MowsProvider>. It reads / writes theme, code theme, language, code editor settings and toast settings on the surrounding context.`,
    },
    composition: {
      title: `Composition`,
      body: `<SettingsPanel> stitches together <ThemePicker>, <CodeThemePicker>, <LanguagePicker>, the code-editor toggles and the toast position picker, plus a JSON tab that round-trips the entire unified <SettingsBlob> (core + app slots). Apps extend the panel with their own typed sections by registering a schema via <MowsProvider appSettings={…} /> — see the Settings system guide.`,
    },
    appExtension: {
      title: `Extending with app settings`,
      body: `Consumer apps add their own typed settings via \`defineAppSettings\`. The schema becomes a new section inside <SettingsPanel> (one sub-section per declared \`group\`), values are persisted under \`app.<appKey>\` in the same blob the panel's JSON tab exports, and reads happen through the typed \`useAppSetting\` hook. The full pattern — schema shape, field types, defaults, custom render escape hatch — lives in the <SettingsSystem> guide.`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Default`,
        description: `The full panel inside a 640px-tall container.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <SettingsPanel> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        threeHeadings: `Renders the three section headings (Appearance, Code editor, Language).`,
        standalonePickersShowCurrent: `Uses the standalone-style theme / code-theme / language pickers and shows their current values.`,
        jsonTabShowsSettings: `Switching to the JSON tab shows the unified settings blob (_v / core / app).`,
        jsonSaveAppliesEdit: `Editing the JSON and clicking Save calls settingsManager.replaceBlob with the parsed value.`,
        jsonRejectsBadVersion: `Rejects a JSON paste whose _v doesn't match the current schema version.`,
        notificationsSection: `Renders the Notifications section with the toast position picker.`,
        jsonIncludesToast: `Exposes core.toast inside the JSON view.`,
        toastPositionFromJson: `A pasted blob with core.toast lands in the settings manager after save.`,
        bracketPairToggle: `Bracket-pair colorization switch dispatches setCodeEditorSettings.`,
        appSectionWhenRegistered: `Renders an app-settings section when a schema is registered, and writes through the manager.`,
        jsonErrorOnInvalid: `Shows an error message when the edited JSON is invalid.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Section layout mirrors under dir="rtl"; the JSON tab is direction-agnostic.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <SettingsPanel>.`,
    },
  },
};

export const settingsPanelDe: SettingsPanelTranslation = {
  default: {
    title: `Standard`,
    description: `Drei Sektionen: Erscheinungsbild, Code-Editor, Sprache. Ein zweiter Tab zeigt das Live-JSON, sodass Power-User einen Settings-Blob einfügen können.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Importpfade an dein Projekt an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `Mounte <SettingsPanel> innerhalb von <MowsProvider>. Es liest / schreibt Theme, Code-Theme, Sprache, Code-Editor-Einstellungen und Toast-Einstellungen im umgebenden Context.`,
    },
    composition: {
      title: `Komposition`,
      body: `<SettingsPanel> verknüpft <ThemePicker>, <CodeThemePicker>, <LanguagePicker>, die Code-Editor-Toggles und den Toast-Position-Picker — plus einen JSON-Tab, der den gesamten vereinheitlichten <SettingsBlob> (core + app) durchschleust. Apps erweitern das Panel mit eigenen typisierten Sektionen, indem sie ein Schema via <MowsProvider appSettings={…} /> registrieren — siehe den Settings-System-Guide.`,
    },
    appExtension: {
      title: `Mit eigenen App-Settings erweitern`,
      body: `Consumer-Apps fügen ihre eigenen typisierten Settings über \`defineAppSettings\` hinzu. Das Schema wird als zusätzliche Sektion in <SettingsPanel> gerendert (eine Untersektion pro deklarierter \`group\`), Werte werden unter \`app.<appKey>\` im selben Blob persistiert, den der JSON-Tab des Panels exportiert, und Lese-Zugriffe laufen über den typisierten \`useAppSetting\`-Hook. Das vollständige Muster — Schema-Form, Feldtypen, Defaults, Custom-Render-Escape-Hatch — steht im <SettingsSystem>-Guide.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Standard`,
        description: `Das gesamte Panel in einem 640px hohen Container.`,
      },
    },
    definedBehaviour: {
      title: `Festgelegtes Verhalten`,
      intro: `Aussagen darüber, wie sich <SettingsPanel> verhalten soll, jeweils mit Verweis auf den Test.`,
      verifiedBy: `geprüft durch`,
      statements: {
        threeHeadings: `Rendert die drei Sektionsüberschriften (Erscheinungsbild, Code-Editor, Sprache).`,
        standalonePickersShowCurrent: `Verwendet die standalone-Variante der Theme- / Code-Theme- / Sprache-Picker und zeigt ihre aktuellen Werte.`,
        jsonTabShowsSettings: `Der JSON-Tab zeigt den vereinheitlichten Settings-Blob an (_v / core / app).`,
        jsonSaveAppliesEdit: `Editieren des JSONs und Klick auf Speichern ruft settingsManager.replaceBlob mit dem geparsten Wert auf.`,
        jsonRejectsBadVersion: `Lehnt einen JSON-Paste ab, dessen _v nicht zur aktuellen Schema-Version passt.`,
        notificationsSection: `Rendert die Sektion "Benachrichtigungen" mit dem Toast-Position-Picker.`,
        jsonIncludesToast: `Exponiert core.toast in der JSON-Ansicht.`,
        toastPositionFromJson: `Ein eingefügter Blob mit core.toast landet nach Save im Settings-Manager.`,
        bracketPairToggle: `Der Switch für Bracket-Pair-Colorization löst setCodeEditorSettings aus.`,
        appSectionWhenRegistered: `Rendert eine App-Settings-Sektion, wenn ein Schema registriert ist, und schreibt durch den Manager.`,
        jsonErrorOnInvalid: `Zeigt eine Fehlermeldung, wenn das editierte JSON ungültig ist.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Das Sektionslayout spiegelt unter dir="rtl"; der JSON-Tab ist richtungsneutral.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <SettingsPanel> akzeptiert.`,
    },
  },
};
