/**
 * Translation slice for settingsPanel.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to settingsPanel's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface SettingsPanelTranslation {
  default: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        threeHeadings: string;
        standalonePickersShowCurrent: string;
        jsonTabShowsSettings: string;
        jsonSaveAppliesEdit: string;
        notificationsSection: string;
        jsonIncludesToast: string;
        toastPositionFromJson: string;
        jsonErrorOnInvalid: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const settingsPanelEn: SettingsPanelTranslation = {
  default: {
    title: `Default`,
    description: `Three sections: Appearance, Code editor, Language. A second tab exposes the live JSON so power-users can paste a settings blob.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `Mount <SettingsPanel> inside <MowsProvider>. It reads / writes theme, code theme, language, code editor settings and toast settings on the surrounding context.`,
    },
    composition: {
      title: `Composition`,
      body: `<SettingsPanel> stitches together <ThemePicker>, <CodeThemePicker>, <LanguagePicker>, the code-editor toggles and the toast position picker, plus a JSON tab that round-trips the entire MowsSettings object.`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Default`,
        description: `The full panel inside a 640px-tall container.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <SettingsPanel> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        threeHeadings: `Renders the three section headings (Appearance, Code editor, Language).`,
        standalonePickersShowCurrent: `Uses the standalone-style theme / code-theme / language pickers and shows their current values.`,
        jsonTabShowsSettings: `Switching to the JSON tab shows the live current settings.`,
        jsonSaveAppliesEdit: `Editing the JSON and clicking Save applies the new settings on the surrounding context.`,
        notificationsSection: `Renders the Notifications section with the toast position picker.`,
        jsonIncludesToast: `Includes toast settings in the JSON view.`,
        toastPositionFromJson: `Applies toast.position from edited JSON to the surrounding context.`,
        jsonErrorOnInvalid: `Shows an error message when the edited JSON is invalid.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Section layout mirrors under dir="rtl"; the JSON tab is direction-agnostic.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <SettingsPanel>.`,
    },
  },
};

export const settingsPanelDe: SettingsPanelTranslation = {
  default: {
    title: `Standard`,
    description: `Drei Sektionen: Erscheinungsbild, Code-Editor, Sprache. Ein zweiter Tab zeigt das Live-JSON, sodass Power-User einen Settings-Blob einfügen können.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Importpfade an dein Projekt an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `Mounte <SettingsPanel> innerhalb von <MowsProvider>. Es liest / schreibt Theme, Code-Theme, Sprache, Code-Editor-Einstellungen und Toast-Einstellungen im umgebenden Context.`,
    },
    composition: {
      title: `Komposition`,
      body: `<SettingsPanel> verknüpft <ThemePicker>, <CodeThemePicker>, <LanguagePicker>, die Code-Editor-Toggles und den Toast-Position-Picker — plus einen JSON-Tab, der das gesamte MowsSettings-Objekt durchschleust.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Standard`,
        description: `Das gesamte Panel in einem 640px hohen Container.`,
      },
    },
    definedBehaviour: {
      title: `Festgelegtes Verhalten`,
      intro: `Aussagen darüber, wie sich <SettingsPanel> verhalten soll, jeweils mit Verweis auf den Test.`,
      verifiedBy: `geprüft durch`,
      statements: {
        threeHeadings: `Rendert die drei Sektionsüberschriften (Erscheinungsbild, Code-Editor, Sprache).`,
        standalonePickersShowCurrent: `Verwendet die standalone-Variante der Theme- / Code-Theme- / Sprache-Picker und zeigt ihre aktuellen Werte.`,
        jsonTabShowsSettings: `Der JSON-Tab zeigt die aktuellen Einstellungen live an.`,
        jsonSaveAppliesEdit: `Editieren des JSONs und Klick auf Speichern überträgt die neuen Werte in den Context.`,
        notificationsSection: `Rendert die Sektion "Benachrichtigungen" mit dem Toast-Position-Picker.`,
        jsonIncludesToast: `Bezieht die Toast-Einstellungen in die JSON-Ansicht mit ein.`,
        toastPositionFromJson: `Übernimmt toast.position aus dem editierten JSON in den umgebenden Context.`,
        jsonErrorOnInvalid: `Zeigt eine Fehlermeldung, wenn das editierte JSON ungültig ist.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Das Sektionslayout spiegelt unter dir="rtl"; der JSON-Tab ist richtungsneutral.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <SettingsPanel> akzeptiert.`,
    },
  },
};
