/*
 * mows-package-manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenderRepositoriesTargetOneOf {
    #[serde(rename = "DryRun")]
    pub dry_run: serde_json::Value,
}

impl RenderRepositoriesTargetOneOf {
    pub fn new(dry_run: serde_json::Value) -> RenderRepositoriesTargetOneOf {
        RenderRepositoriesTargetOneOf {
            dry_run,
        }
    }
}

