/**
 * Translation slice for emojiPicker.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to emojiPicker's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface EmojiPickerTranslation {
  default: { title: string; description: string };
  inPopover: { title: string; description: string };
  rtl: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
      inPopover: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        rendersShell: string;
        searchFilters: string;
        noResultsState: string;
        onSelectFires: string;
        appliesSkinTone: string;
        persistsRecents: string;
        dedupesRecents: string;
        clearSearchButton: string;
        escapeFlow: string;
        hidesSearch: string;
        hidesSkinTone: string;
        configurableColumns: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const emojiPickerEn: EmojiPickerTranslation = {
  default: {
    title: `Default`,
    description: `Full picker with search, category tabs, recently-used row, and skin-tone toggle. Click any cell to fire onSelect with the final (skin-toned) emoji string.`,
  },
  inPopover: {
    title: `Inside a popover`,
    description: `The most common deployment: the picker lives in a popover anchored to a "smile" button. The picker collapses its own border/shadow when nested inside the popover.`,
  },
  rtl: {
    title: `Right-to-left`,
    description: `Wrapped in dir="rtl" with a translated string bundle. Layout flips, category tabs read right-to-left.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<EmojiPicker> renders a categorized emoji grid with search and skin-tone support. Wire it to your text input or reaction bar via onSelect; the picker handles persistence of recently-used emojis and skin-tone preferences via localStorage.`,
    },
    composition: {
      title: `Composition`,
      body: `Drop the picker inside a <Popover> for the typical "open the picker from a button" flow, or render it inline as a side panel. The component is self-contained; consumers only wire onSelect to capture the chosen emoji string (already skin-toned).`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Default`,
        description: `Full picker with search, categories, recents, and skin tone.`,
      },
      inPopover: {
        title: `Inside a popover`,
        description: `Picker mounted inside a <Popover> anchored to a trigger button.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <EmojiPicker> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        rendersShell: `Renders the picker shell with the search input and category tab strip.`,
        searchFilters: `Typing in the search input replaces the category grid with a flat results grid.`,
        noResultsState: `Renders a "no results" affordance when the query matches no emoji.`,
        onSelectFires: `Clicking a cell fires onSelect with the bare character and entry metadata.`,
        appliesSkinTone: `Applies the active skin-tone modifier to skin-toneable emojis before firing onSelect.`,
        persistsRecents: `Persists picked emojis to localStorage under the configured storagePrefix.`,
        dedupesRecents: `Dedupes the recents list by base character — repeated picks of the same emoji do not duplicate.`,
        clearSearchButton: `Renders a clear-search button while the query is non-empty.`,
        escapeFlow: `First Escape clears a non-empty query; a second Escape invokes onClose.`,
        hidesSearch: `Hides the search bar when hideSearch is true.`,
        hidesSkinTone: `Hides the skin-tone trigger when hideSkinTone is true.`,
        configurableColumns: `Sets the grid template column count from the columns prop.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `The picker flips horizontally under dir="rtl"; category tabs read right-to-left and the search input mirrors its iconography.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <EmojiPicker>.`,
    },
  },
};

export const emojiPickerDe: EmojiPickerTranslation = {
  default: {
    title: `Standard`,
    description: `Vollständiger Picker mit Suche, Kategorie-Tabs, „Zuletzt verwendet“-Zeile und Hauttyp-Umschalter. Ein Klick auf eine Zelle löst onSelect mit dem finalen (hauttypierten) Emoji-String aus.`,
  },
  inPopover: {
    title: `In einem Popover`,
    description: `Die typische Einbettung: der Picker lebt in einem Popover, das an einem Smiley-Button hängt. Innerhalb des Popovers blendet der Picker seine eigene Umrandung/Schatten aus.`,
  },
  rtl: {
    title: `Rechts-nach-links`,
    description: `In dir="rtl" eingebettet mit übersetzten Strings. Layout spiegelt sich, Kategorie-Tabs lesen von rechts nach links.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Import-Pfade an deine Projektstruktur an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<EmojiPicker> rendert ein kategorisiertes Emoji-Raster mit Suche und Hauttyp-Unterstützung. Verbinde es über onSelect mit deiner Texteingabe oder Reaktionsleiste; der Picker speichert zuletzt verwendete Emojis und die Hauttyp-Präferenz selbständig in localStorage.`,
    },
    composition: {
      title: `Komposition`,
      body: `Setze den Picker in ein <Popover> für den klassischen „Picker per Button öffnen“-Flow oder rendere ihn als inline-Seitenpanel. Die Komponente ist eigenständig; Consumer müssen nur onSelect verbinden, um das gewählte Emoji (bereits hauttypiert) zu erhalten.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Standard`,
        description: `Vollständiger Picker mit Suche, Kategorien, Zuletzt-Zeile und Hauttyp.`,
      },
      inPopover: {
        title: `In einem Popover`,
        description: `Picker in einem <Popover>, verankert an einem Trigger-Button.`,
      },
    },
    definedBehaviour: {
      title: `Definiertes Verhalten`,
      intro: `Aussagen darüber, wie sich <EmojiPicker> verhalten soll — jede verlinkt mit dem Test, der sie verifiziert.`,
      verifiedBy: `verifiziert durch`,
      statements: {
        rendersShell: `Rendert das Picker-Gerüst mit Sucheingabe und Kategorie-Tab-Leiste.`,
        searchFilters: `Tippen in die Suchleiste ersetzt das Kategorie-Raster durch ein flaches Ergebnisraster.`,
        noResultsState: `Zeigt eine „Keine Ergebnisse“-Anzeige, wenn die Anfrage zu keinem Emoji passt.`,
        onSelectFires: `Ein Klick auf eine Zelle löst onSelect mit dem Basiszeichen und den Eintrags-Metadaten aus.`,
        appliesSkinTone: `Wendet den aktiven Hauttyp-Modifier auf hauttypierbare Emojis an, bevor onSelect ausgelöst wird.`,
        persistsRecents: `Speichert ausgewählte Emojis im localStorage unter dem konfigurierten storagePrefix.`,
        dedupesRecents: `Dedupliziert die Zuletzt-Zeile per Basiszeichen — wiederholte Auswahl desselben Emojis erscheint nicht doppelt.`,
        clearSearchButton: `Zeigt eine „Suche leeren“-Schaltfläche, solange die Anfrage nicht leer ist.`,
        escapeFlow: `Erstes Escape leert eine nicht-leere Anfrage; ein zweites Escape ruft onClose auf.`,
        hidesSearch: `Versteckt die Suchleiste, wenn hideSearch gesetzt ist.`,
        hidesSkinTone: `Versteckt den Hauttyp-Trigger, wenn hideSkinTone gesetzt ist.`,
        configurableColumns: `Setzt die Anzahl der Grid-Spalten anhand des columns-Props.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Der Picker spiegelt sich unter dir="rtl"; Kategorie-Tabs lesen von rechts nach links und die Sucheingabe spiegelt ihre Iconografie.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <EmojiPicker> akzeptiert.`,
    },
  },
};
