/**
 * Translation slice for optionPicker.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to optionPicker's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface OptionPickerTranslation {
  default: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        rendersLabel: string;
        showsCountByDefault: string;
        hidesCountWhenFalse: string;
        menuItemsAfterOpen: string;
        firesOnToggle: string;
        staysOpenOnToggle: string;
        rendersHeader: string;
        disabledForwards: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const optionPickerEn: OptionPickerTranslation = {
  default: {
    title: `Multi-select`,
    description: `Three options inside a popover. Toggling an option keeps the menu open; the trigger shows "(enabled/total)" by default.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<OptionPicker> is a multi-select dropdown built on DropdownMenuCheckboxItem. Options are { id, label, enabled }; the consumer toggles them via onOptionChange.`,
    },
    composition: {
      title: `Composition`,
      body: `Pass triggerComponent for a custom trigger label. The menu deliberately does NOT close on select so the user can toggle multiple options in one interaction.`,
    },
    examples: {
      title: `Examples`,
      default: { title: `Multi-select`, description: `Three view options.` },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <OptionPicker> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        rendersLabel: `Renders the trigger label.`,
        showsCountByDefault: `Renders the enabled/total count on the trigger by default.`,
        hidesCountWhenFalse: `Omits the count when showCount={false}.`,
        menuItemsAfterOpen: `Renders one menuitemcheckbox per option after opening.`,
        firesOnToggle: `Fires onOptionChange when a menu item is toggled.`,
        staysOpenOnToggle: `Stays open after toggling an option (preventDefault on select).`,
        rendersHeader: `Renders the optional header label.`,
        disabledForwards: `Disabled trigger forwards the disabled attribute and ignores clicks.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Under dir="rtl" the menu mirrors so it opens on the leading edge.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <OptionPicker>.`,
    },
  },
};

export const optionPickerDe: OptionPickerTranslation = {
  default: {
    title: `Multi-Select`,
    description: `Drei Optionen im Popover. Toggle hält das Menü offen; der Trigger zeigt „(enabled/total)" als Default.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Importpfade an dein Projekt an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<OptionPicker> ist ein Multi-Select-Dropdown auf Basis von DropdownMenuCheckboxItem. Optionen sind { id, label, enabled }; der Konsument togglet via onOptionChange.`,
    },
    composition: {
      title: `Komposition`,
      body: `triggerComponent für ein eigenes Trigger-Label. Das Menü schließt absichtlich NICHT beim Auswählen, damit man mehrere Optionen in einem Zug togglen kann.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Multi-Select`,
        description: `Drei Ansichts-Optionen.`,
      },
    },
    definedBehaviour: {
      title: `Festgelegtes Verhalten`,
      intro: `Aussagen darüber, wie sich <OptionPicker> verhalten soll, jeweils mit Verweis auf den Test.`,
      verifiedBy: `geprüft durch`,
      statements: {
        rendersLabel: `Rendert das Trigger-Label.`,
        showsCountByDefault: `Rendert standardmäßig die enabled/total-Anzeige am Trigger.`,
        hidesCountWhenFalse: `Lässt die Anzeige weg, wenn showCount={false}.`,
        menuItemsAfterOpen: `Rendert ein menuitemcheckbox pro Option nach dem Öffnen.`,
        firesOnToggle: `Feuert onOptionChange beim Toggle eines Eintrags.`,
        staysOpenOnToggle: `Bleibt nach dem Toggle offen (preventDefault auf onSelect).`,
        rendersHeader: `Rendert das optionale Header-Label.`,
        disabledForwards: `Deaktivierter Trigger reicht disabled durch und ignoriert Klicks.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Unter dir="rtl" spiegelt das Menü und öffnet am führenden Rand.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <OptionPicker> akzeptiert.`,
    },
  },
};
