/**
 * Translation slice for hoverCard.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to hoverCard's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface HoverCardTranslation {
  default: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        closedByDefault: string;
        defaultOpenRenders: string;
        contentStyling: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const hoverCardEn: HoverCardTranslation = {
  default: {
    title: `Username preview`,
    description: `Hover (or focus) the link to see a preview card. Open and close delays are tunable on the root.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<HoverCard> wraps Radix HoverCard. The card opens on hover or focus on the trigger; it is keyboard-accessible.`,
    },
    composition: {
      title: `Composition`,
      body: `Tune the openDelay / closeDelay on the root to control timing. The trigger should be a link / button (the card is informational, not actionable).`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Username preview`,
        description: `Hover over @mows to see the preview card.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <HoverCard> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        closedByDefault: `Is closed by default — content is not rendered.`,
        defaultOpenRenders: `Renders the content when defaultOpen is set.`,
        contentStyling: `Applies width + popover background to the content surface.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Under dir="rtl" the card mirrors so it opens on the leading edge of the trigger.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <HoverCard> and <HoverCardContent>.`,
    },
  },
};

export const hoverCardDe: HoverCardTranslation = {
  default: {
    title: `Username-Vorschau`,
    description: `Hover (oder Fokus) auf den Link zeigt eine Vorschau. Open-/Close-Delays sind am Root einstellbar.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Importpfade an dein Projekt an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<HoverCard> kapselt Radix HoverCard. Öffnet bei Hover oder Fokus auf den Trigger; tastatur-zugänglich.`,
    },
    composition: {
      title: `Komposition`,
      body: `Open-/Close-Delay am Root tunen. Der Trigger sollte ein Link / Button sein (die Card ist informativ, nicht handlungsaufrufend).`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Username-Vorschau`,
        description: `Hover über @mows zeigt die Vorschau.`,
      },
    },
    definedBehaviour: {
      title: `Festgelegtes Verhalten`,
      intro: `Aussagen darüber, wie sich <HoverCard> verhalten soll, jeweils mit Verweis auf den Test.`,
      verifiedBy: `geprüft durch`,
      statements: {
        closedByDefault: `Ist standardmäßig geschlossen — Inhalt wird nicht gerendert.`,
        defaultOpenRenders: `Rendert den Inhalt, wenn defaultOpen gesetzt ist.`,
        contentStyling: `Wendet Breite + Popover-Hintergrund auf die Content-Oberfläche an.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Unter dir="rtl" spiegelt die Card, sodass sie am führenden Rand des Triggers öffnet.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <HoverCard> und <HoverCardContent> akzeptieren.`,
    },
  },
};
