/**
 * Curated emoji dataset shipped with `<EmojiPicker>`.
 *
 * Each entry is a tuple `[char, name, keywords]` so the file stays small —
 * a record-of-objects shape balloons by ~30% once minified. `t` (truthy)
 * marks an emoji that accepts a Fitzpatrick skin-tone modifier; the
 * picker re-renders those at runtime by appending the modifier code
 * point. Names + keywords are lower-cased at module-init time so search
 * comparisons stay O(n).
 *
 * This is a curated set (≈500 emojis) — not an exhaustive Unicode dump.
 * It mirrors what GitHub / Slack / Discord pickers default to and keeps
 * the bundle under 30 KB.
 */

export type EmojiCategoryId =
    | `smileys`
    | `people`
    | `animals`
    | `food`
    | `activities`
    | `travel`
    | `objects`
    | `symbols`
    | `flags`;

export interface EmojiCategoryDefinition {
    readonly id: EmojiCategoryId;
    /** A lucide-react icon name string used by `<EmojiPicker>` to pick a glyph. */
    readonly iconEmoji: string;
}

export const EMOJI_CATEGORIES: ReadonlyArray<EmojiCategoryDefinition> = [
    { id: `smileys`, iconEmoji: `😀` },
    { id: `people`, iconEmoji: `👋` },
    { id: `animals`, iconEmoji: `🐶` },
    { id: `food`, iconEmoji: `🍕` },
    { id: `activities`, iconEmoji: `⚽` },
    { id: `travel`, iconEmoji: `🚗` },
    { id: `objects`, iconEmoji: `💡` },
    { id: `symbols`, iconEmoji: `❤️` },
    { id: `flags`, iconEmoji: `🏳️` }
];

export interface EmojiEntry {
    readonly char: string;
    readonly name: string;
    readonly keywords: ReadonlyArray<string>;
    readonly category: EmojiCategoryId;
    readonly hasSkinTone: boolean;
}

/**
 * Fitzpatrick skin-tone modifier code points. Index 0 is "default" (no
 * modifier), 1–5 are the Unicode FITZPATRICK TYPE-1 through TYPE-6
 * modifiers (1-2 is a single modifier covering both lightest tones).
 */
export const SKIN_TONE_MODIFIERS: ReadonlyArray<string> = [
    ``,
    `\u{1F3FB}`,
    `\u{1F3FC}`,
    `\u{1F3FD}`,
    `\u{1F3FE}`,
    `\u{1F3FF}`
];

export type SkinToneIndex = 0 | 1 | 2 | 3 | 4 | 5;

/**
 * Apply a Fitzpatrick skin tone to an emoji that supports it. Falls back
 * to the bare character when the index is 0 or the emoji is not in the
 * skin-tone set. The membership check is sourced from the curated
 * dataset (see SKIN_TONE_CAPABLE_CHARS below) so callers can apply this
 * function uniformly across a row of mixed entries without leaking
 * spurious modifiers onto cats / hearts / etc.
 */
export const applySkinTone = (char: string, toneIndex: SkinToneIndex): string => {
    if (toneIndex === 0) return char;
    if (!SKIN_TONE_CAPABLE_CHARS.has(char)) return char;
    const modifier = SKIN_TONE_MODIFIERS[toneIndex];
    if (modifier === undefined || modifier === ``) return char;
    return char + modifier;
};

type Row = readonly [char: string, name: string, keywords: string, hasSkinTone?: 1];

const SMILEYS: ReadonlyArray<Row> = [
    [`😀`, `grinning face`, `happy smile joy`],
    [`😃`, `grinning face with big eyes`, `happy smile`],
    [`😄`, `grinning face with smiling eyes`, `happy smile laugh`],
    [`😁`, `beaming face with smiling eyes`, `happy grin`],
    [`😆`, `grinning squinting face`, `laugh haha`],
    [`😅`, `grinning face with sweat`, `phew relief`],
    [`🤣`, `rolling on the floor laughing`, `rofl haha lol`],
    [`😂`, `face with tears of joy`, `lol haha cry-laugh`],
    [`🙂`, `slightly smiling face`, `smile`],
    [`🙃`, `upside down face`, `silly`],
    [`😉`, `winking face`, `wink flirt`],
    [`😊`, `smiling face with smiling eyes`, `blush happy`],
    [`😇`, `smiling face with halo`, `angel innocent`],
    [`🥰`, `smiling face with hearts`, `love adore`],
    [`😍`, `smiling face with heart eyes`, `love crush`],
    [`🤩`, `star struck`, `wow excited`],
    [`😘`, `face blowing a kiss`, `kiss love`],
    [`😗`, `kissing face`, `kiss`],
    [`😚`, `kissing face with closed eyes`, `kiss`],
    [`😙`, `kissing face with smiling eyes`, `kiss`],
    [`🥲`, `smiling face with tear`, `happy cry grateful`],
    [`😋`, `face savoring food`, `yum tasty`],
    [`😛`, `face with tongue`, `tongue silly`],
    [`😜`, `winking face with tongue`, `tongue silly`],
    [`🤪`, `zany face`, `crazy silly`],
    [`😝`, `squinting face with tongue`, `tongue silly`],
    [`🤑`, `money mouth face`, `rich dollar`],
    [`🤗`, `hugging face`, `hug embrace`],
    [`🤭`, `face with hand over mouth`, `oops giggle`],
    [`🤫`, `shushing face`, `quiet shh secret`],
    [`🤔`, `thinking face`, `hmm think`],
    [`🤐`, `zipper mouth face`, `quiet secret`],
    [`🤨`, `face with raised eyebrow`, `suspicious skeptical`],
    [`😐`, `neutral face`, `meh expressionless`],
    [`😑`, `expressionless face`, `blank meh`],
    [`😶`, `face without mouth`, `silent speechless`],
    [`😏`, `smirking face`, `smirk smug`],
    [`😒`, `unamused face`, `meh annoyed`],
    [`🙄`, `face with rolling eyes`, `eyeroll annoyed`],
    [`😬`, `grimacing face`, `awkward`],
    [`🤥`, `lying face`, `pinocchio liar`],
    [`😌`, `relieved face`, `relaxed calm`],
    [`😔`, `pensive face`, `sad reflective`],
    [`😪`, `sleepy face`, `tired`],
    [`🤤`, `drooling face`, `drool want`],
    [`😴`, `sleeping face`, `sleep zzz`],
    [`😷`, `face with medical mask`, `sick mask`],
    [`🤒`, `face with thermometer`, `sick fever`],
    [`🤕`, `face with head bandage`, `injured`],
    [`🤢`, `nauseated face`, `sick gross`],
    [`🤮`, `face vomiting`, `sick puke`],
    [`🤧`, `sneezing face`, `cold sick`],
    [`🥵`, `hot face`, `sweating warm`],
    [`🥶`, `cold face`, `freezing winter`],
    [`🥴`, `woozy face`, `dizzy drunk`],
    [`😵`, `dizzy face`, `dizzy ko`],
    [`🤯`, `exploding head`, `mind blown shocked`],
    [`🤠`, `cowboy hat face`, `cowboy yeehaw`],
    [`🥳`, `partying face`, `party celebrate`],
    [`🥸`, `disguised face`, `incognito glasses`],
    [`😎`, `smiling face with sunglasses`, `cool sunglasses`],
    [`🤓`, `nerd face`, `geek nerd glasses`],
    [`🧐`, `face with monocle`, `inspect monocle`],
    [`😕`, `confused face`, `confused`],
    [`😟`, `worried face`, `worried`],
    [`🙁`, `slightly frowning face`, `frown sad`],
    [`☹️`, `frowning face`, `frown sad`],
    [`😮`, `face with open mouth`, `surprised wow`],
    [`😯`, `hushed face`, `quiet`],
    [`😲`, `astonished face`, `shocked surprised`],
    [`😳`, `flushed face`, `embarrassed blush`],
    [`🥺`, `pleading face`, `please beg puppy eyes`],
    [`😦`, `frowning face with open mouth`, `worried`],
    [`😧`, `anguished face`, `pain`],
    [`😨`, `fearful face`, `scared fear`],
    [`😰`, `anxious face with sweat`, `nervous worry`],
    [`😥`, `sad but relieved face`, `phew sad`],
    [`😢`, `crying face`, `sad tear`],
    [`😭`, `loudly crying face`, `cry sob sad`],
    [`😱`, `face screaming in fear`, `scream scared`],
    [`😖`, `confounded face`, `frustrated`],
    [`😣`, `persevering face`, `struggle`],
    [`😞`, `disappointed face`, `sad`],
    [`😓`, `downcast face with sweat`, `worry sad`],
    [`😩`, `weary face`, `tired ugh`],
    [`😫`, `tired face`, `exhausted`],
    [`🥱`, `yawning face`, `tired bored`],
    [`😤`, `face with steam from nose`, `angry frustrated`],
    [`😡`, `pouting face`, `angry mad`],
    [`😠`, `angry face`, `mad`],
    [`🤬`, `face with symbols on mouth`, `swearing cursing`],
    [`😈`, `smiling face with horns`, `devil mischief`],
    [`👿`, `angry face with horns`, `devil imp`],
    [`💀`, `skull`, `dead death`],
    [`☠️`, `skull and crossbones`, `pirate poison danger`],
    [`💩`, `pile of poo`, `poop crap`],
    [`🤡`, `clown face`, `clown silly`],
    [`👹`, `ogre`, `monster`],
    [`👺`, `goblin`, `monster`],
    [`👻`, `ghost`, `boo halloween`],
    [`👽`, `alien`, `ufo space`],
    [`👾`, `alien monster`, `game arcade`],
    [`🤖`, `robot`, `bot ai`],
    [`😺`, `grinning cat`, `cat happy`],
    [`😸`, `grinning cat with smiling eyes`, `cat happy`],
    [`😹`, `cat with tears of joy`, `cat laugh`],
    [`😻`, `smiling cat with heart eyes`, `cat love`],
    [`😼`, `cat with wry smile`, `cat smirk`],
    [`😽`, `kissing cat`, `cat kiss`],
    [`🙀`, `weary cat`, `cat scared`],
    [`😿`, `crying cat`, `cat sad`],
    [`😾`, `pouting cat`, `cat angry`]
];

const PEOPLE: ReadonlyArray<Row> = [
    [`👋`, `waving hand`, `wave hello bye`, 1],
    [`🤚`, `raised back of hand`, `stop hand`, 1],
    [`🖐️`, `hand with fingers splayed`, `hand`, 1],
    [`✋`, `raised hand`, `stop high five`, 1],
    [`🖖`, `vulcan salute`, `spock star trek`, 1],
    [`👌`, `OK hand`, `ok perfect`, 1],
    [`🤌`, `pinched fingers`, `italian gesture`, 1],
    [`🤏`, `pinching hand`, `small tiny`, 1],
    [`✌️`, `victory hand`, `peace`, 1],
    [`🤞`, `crossed fingers`, `luck hopeful`, 1],
    [`🤟`, `love you gesture`, `rock`, 1],
    [`🤘`, `sign of the horns`, `metal rock`, 1],
    [`🤙`, `call me hand`, `hang loose shaka`, 1],
    [`👈`, `backhand index pointing left`, `point left`, 1],
    [`👉`, `backhand index pointing right`, `point right`, 1],
    [`👆`, `backhand index pointing up`, `point up`, 1],
    [`🖕`, `middle finger`, `rude flip off`, 1],
    [`👇`, `backhand index pointing down`, `point down`, 1],
    [`☝️`, `index pointing up`, `one this`, 1],
    [`👍`, `thumbs up`, `like approve yes ok`, 1],
    [`👎`, `thumbs down`, `dislike no`, 1],
    [`✊`, `raised fist`, `fist power`, 1],
    [`👊`, `oncoming fist`, `punch bro fist`, 1],
    [`🤛`, `left facing fist`, `fist bump`, 1],
    [`🤜`, `right facing fist`, `fist bump`, 1],
    [`👏`, `clapping hands`, `applause clap`, 1],
    [`🙌`, `raising hands`, `praise celebrate`, 1],
    [`👐`, `open hands`, `hug`, 1],
    [`🤲`, `palms up together`, `pray cup`, 1],
    [`🤝`, `handshake`, `deal agreement`],
    [`🙏`, `folded hands`, `pray thanks please`, 1],
    [`✍️`, `writing hand`, `write sign`, 1],
    [`💅`, `nail polish`, `manicure`, 1],
    [`🤳`, `selfie`, `phone camera`, 1],
    [`💪`, `flexed biceps`, `strong muscle`, 1],
    [`🦾`, `mechanical arm`, `prosthetic`],
    [`🦿`, `mechanical leg`, `prosthetic`],
    [`🦵`, `leg`, ``, 1],
    [`🦶`, `foot`, ``, 1],
    [`👂`, `ear`, ``, 1],
    [`🦻`, `ear with hearing aid`, ``, 1],
    [`👃`, `nose`, ``, 1],
    [`🧠`, `brain`, `mind smart`],
    [`🫀`, `anatomical heart`, `organ`],
    [`🫁`, `lungs`, `breathe`],
    [`🦷`, `tooth`, `dentist`],
    [`🦴`, `bone`, ``],
    [`👀`, `eyes`, `look watch`],
    [`👁️`, `eye`, ``],
    [`👅`, `tongue`, `lick`],
    [`👄`, `mouth`, `lips`],
    [`👶`, `baby`, `infant`, 1],
    [`🧒`, `child`, ``, 1],
    [`👦`, `boy`, ``, 1],
    [`👧`, `girl`, ``, 1],
    [`🧑`, `person`, ``, 1],
    [`👱`, `person blond hair`, ``, 1],
    [`👨`, `man`, ``, 1],
    [`🧔`, `man beard`, ``, 1],
    [`👩`, `woman`, ``, 1],
    [`🧓`, `older person`, ``, 1],
    [`👴`, `old man`, `grandpa`, 1],
    [`👵`, `old woman`, `grandma`, 1],
    [`🙍`, `person frowning`, ``, 1],
    [`🙎`, `person pouting`, ``, 1],
    [`🙅`, `person gesturing no`, `cancel stop`, 1],
    [`🙆`, `person gesturing ok`, ``, 1],
    [`💁`, `person tipping hand`, `info`, 1],
    [`🙋`, `person raising hand`, ``, 1],
    [`🧏`, `deaf person`, ``, 1],
    [`🙇`, `person bowing`, `sorry apologize`, 1],
    [`🤦`, `person facepalming`, `facepalm`, 1],
    [`🤷`, `person shrugging`, `shrug idk`, 1],
    [`👮`, `police officer`, `cop`, 1],
    [`🕵️`, `detective`, `spy`, 1],
    [`💂`, `guard`, ``, 1],
    [`👷`, `construction worker`, ``, 1],
    [`🤴`, `prince`, ``, 1],
    [`👸`, `princess`, ``, 1],
    [`👳`, `person wearing turban`, ``, 1],
    [`👲`, `person with skullcap`, ``, 1],
    [`🧕`, `woman with headscarf`, ``, 1],
    [`🤵`, `person in tuxedo`, ``, 1],
    [`👰`, `person with veil`, `bride`, 1],
    [`🤰`, `pregnant woman`, ``, 1],
    [`🤱`, `breast feeding`, ``, 1],
    [`👼`, `baby angel`, ``, 1],
    [`🎅`, `santa claus`, `christmas`, 1],
    [`🤶`, `mrs claus`, `christmas`, 1],
    [`🦸`, `superhero`, ``, 1],
    [`🦹`, `supervillain`, ``, 1],
    [`🧙`, `mage`, `wizard witch`, 1],
    [`🧚`, `fairy`, ``, 1],
    [`🧛`, `vampire`, ``, 1],
    [`🧜`, `merperson`, `mermaid`, 1],
    [`🧝`, `elf`, ``, 1],
    [`🧞`, `genie`, ``],
    [`🧟`, `zombie`, ``],
    [`💆`, `person getting massage`, ``, 1],
    [`💇`, `person getting haircut`, ``, 1],
    [`🚶`, `person walking`, ``, 1],
    [`🧍`, `person standing`, ``, 1],
    [`🧎`, `person kneeling`, ``, 1],
    [`🏃`, `person running`, ``, 1],
    [`💃`, `woman dancing`, ``, 1],
    [`🕺`, `man dancing`, ``, 1],
    [`🧖`, `person in steamy room`, `sauna`, 1],
    [`🧗`, `person climbing`, ``, 1]
];

const ANIMALS: ReadonlyArray<Row> = [
    [`🐶`, `dog face`, `puppy`],
    [`🐱`, `cat face`, `kitten`],
    [`🐭`, `mouse face`, ``],
    [`🐹`, `hamster`, ``],
    [`🐰`, `rabbit face`, `bunny`],
    [`🦊`, `fox`, ``],
    [`🐻`, `bear`, ``],
    [`🐼`, `panda`, ``],
    [`🐨`, `koala`, ``],
    [`🐯`, `tiger face`, ``],
    [`🦁`, `lion`, ``],
    [`🐮`, `cow face`, ``],
    [`🐷`, `pig face`, ``],
    [`🐽`, `pig nose`, ``],
    [`🐸`, `frog`, ``],
    [`🐵`, `monkey face`, ``],
    [`🙈`, `see no evil monkey`, ``],
    [`🙉`, `hear no evil monkey`, ``],
    [`🙊`, `speak no evil monkey`, ``],
    [`🐒`, `monkey`, ``],
    [`🐔`, `chicken`, ``],
    [`🐧`, `penguin`, ``],
    [`🐦`, `bird`, ``],
    [`🐤`, `baby chick`, ``],
    [`🐣`, `hatching chick`, ``],
    [`🐥`, `front facing baby chick`, ``],
    [`🦆`, `duck`, ``],
    [`🦅`, `eagle`, ``],
    [`🦉`, `owl`, ``],
    [`🦇`, `bat`, ``],
    [`🐺`, `wolf`, ``],
    [`🐗`, `boar`, ``],
    [`🐴`, `horse face`, ``],
    [`🦄`, `unicorn`, ``],
    [`🐝`, `honeybee`, `bee`],
    [`🐛`, `bug`, ``],
    [`🦋`, `butterfly`, ``],
    [`🐌`, `snail`, ``],
    [`🐞`, `lady beetle`, `ladybug`],
    [`🐜`, `ant`, ``],
    [`🦗`, `cricket`, ``],
    [`🕷️`, `spider`, ``],
    [`🕸️`, `spider web`, ``],
    [`🦂`, `scorpion`, ``],
    [`🐢`, `turtle`, ``],
    [`🐍`, `snake`, ``],
    [`🦎`, `lizard`, ``],
    [`🦖`, `t-rex`, `dinosaur`],
    [`🦕`, `sauropod`, `dinosaur`],
    [`🐙`, `octopus`, ``],
    [`🦑`, `squid`, ``],
    [`🦐`, `shrimp`, ``],
    [`🦞`, `lobster`, ``],
    [`🦀`, `crab`, ``],
    [`🐡`, `blowfish`, ``],
    [`🐠`, `tropical fish`, ``],
    [`🐟`, `fish`, ``],
    [`🐬`, `dolphin`, ``],
    [`🐳`, `spouting whale`, ``],
    [`🐋`, `whale`, ``],
    [`🦈`, `shark`, ``],
    [`🐊`, `crocodile`, ``],
    [`🐅`, `tiger`, ``],
    [`🐆`, `leopard`, ``],
    [`🦓`, `zebra`, ``],
    [`🦍`, `gorilla`, ``],
    [`🦧`, `orangutan`, ``],
    [`🐘`, `elephant`, ``],
    [`🦛`, `hippopotamus`, `hippo`],
    [`🦏`, `rhinoceros`, `rhino`],
    [`🐪`, `camel`, ``],
    [`🐫`, `two hump camel`, ``],
    [`🦒`, `giraffe`, ``],
    [`🦘`, `kangaroo`, ``],
    [`🐃`, `water buffalo`, ``],
    [`🐂`, `ox`, ``],
    [`🐄`, `cow`, ``],
    [`🐎`, `horse`, ``],
    [`🐖`, `pig`, ``],
    [`🐏`, `ram`, ``],
    [`🐑`, `ewe`, `sheep`],
    [`🐐`, `goat`, ``],
    [`🦌`, `deer`, ``],
    [`🐕`, `dog`, ``],
    [`🐩`, `poodle`, ``],
    [`🦮`, `guide dog`, ``],
    [`🐈`, `cat`, ``],
    [`🐓`, `rooster`, ``],
    [`🦃`, `turkey`, ``],
    [`🦚`, `peacock`, ``],
    [`🦜`, `parrot`, ``],
    [`🦢`, `swan`, ``],
    [`🦩`, `flamingo`, ``],
    [`🕊️`, `dove`, `peace`],
    [`🐇`, `rabbit`, ``],
    [`🐁`, `mouse`, ``],
    [`🐀`, `rat`, ``],
    [`🐿️`, `chipmunk`, `squirrel`],
    [`🦔`, `hedgehog`, ``],
    [`🌵`, `cactus`, ``],
    [`🎄`, `christmas tree`, ``],
    [`🌲`, `evergreen tree`, ``],
    [`🌳`, `deciduous tree`, ``],
    [`🌴`, `palm tree`, ``],
    [`🌱`, `seedling`, ``],
    [`🌿`, `herb`, ``],
    [`☘️`, `shamrock`, ``],
    [`🍀`, `four leaf clover`, `lucky`],
    [`🎍`, `pine decoration`, ``],
    [`🎋`, `tanabata tree`, ``],
    [`🍃`, `leaf fluttering in wind`, ``],
    [`🍂`, `fallen leaf`, ``],
    [`🍁`, `maple leaf`, `canada`],
    [`🌾`, `sheaf of rice`, ``],
    [`🌺`, `hibiscus`, ``],
    [`🌻`, `sunflower`, ``],
    [`🌹`, `rose`, ``],
    [`🥀`, `wilted flower`, ``],
    [`🌷`, `tulip`, ``],
    [`🌼`, `blossom`, ``],
    [`🌸`, `cherry blossom`, `sakura`],
    [`💐`, `bouquet`, ``],
    [`🍄`, `mushroom`, ``],
    [`🐚`, `spiral shell`, ``]
];

const FOOD: ReadonlyArray<Row> = [
    [`🍇`, `grapes`, ``],
    [`🍈`, `melon`, ``],
    [`🍉`, `watermelon`, ``],
    [`🍊`, `tangerine`, `orange`],
    [`🍋`, `lemon`, ``],
    [`🍌`, `banana`, ``],
    [`🍍`, `pineapple`, ``],
    [`🥭`, `mango`, ``],
    [`🍎`, `red apple`, ``],
    [`🍏`, `green apple`, ``],
    [`🍐`, `pear`, ``],
    [`🍑`, `peach`, ``],
    [`🍒`, `cherries`, ``],
    [`🍓`, `strawberry`, ``],
    [`🫐`, `blueberries`, ``],
    [`🥝`, `kiwi fruit`, ``],
    [`🍅`, `tomato`, ``],
    [`🫒`, `olive`, ``],
    [`🥥`, `coconut`, ``],
    [`🥑`, `avocado`, ``],
    [`🍆`, `eggplant`, `aubergine`],
    [`🥔`, `potato`, ``],
    [`🥕`, `carrot`, ``],
    [`🌽`, `ear of corn`, ``],
    [`🌶️`, `hot pepper`, `chili`],
    [`🫑`, `bell pepper`, ``],
    [`🥒`, `cucumber`, ``],
    [`🥬`, `leafy green`, ``],
    [`🥦`, `broccoli`, ``],
    [`🧄`, `garlic`, ``],
    [`🧅`, `onion`, ``],
    [`🥜`, `peanuts`, ``],
    [`🌰`, `chestnut`, ``],
    [`🍞`, `bread`, ``],
    [`🥐`, `croissant`, ``],
    [`🥖`, `baguette bread`, ``],
    [`🫓`, `flatbread`, ``],
    [`🥨`, `pretzel`, ``],
    [`🥯`, `bagel`, ``],
    [`🥞`, `pancakes`, ``],
    [`🧇`, `waffle`, ``],
    [`🧀`, `cheese wedge`, ``],
    [`🍖`, `meat on bone`, ``],
    [`🍗`, `poultry leg`, ``],
    [`🥩`, `cut of meat`, ``],
    [`🥓`, `bacon`, ``],
    [`🍔`, `hamburger`, `burger`],
    [`🍟`, `french fries`, ``],
    [`🍕`, `pizza`, ``],
    [`🌭`, `hot dog`, ``],
    [`🥪`, `sandwich`, ``],
    [`🌮`, `taco`, ``],
    [`🌯`, `burrito`, ``],
    [`🫔`, `tamale`, ``],
    [`🥙`, `stuffed flatbread`, ``],
    [`🧆`, `falafel`, ``],
    [`🥚`, `egg`, ``],
    [`🍳`, `cooking`, `fried egg`],
    [`🥘`, `shallow pan of food`, ``],
    [`🍲`, `pot of food`, ``],
    [`🫕`, `fondue`, ``],
    [`🥣`, `bowl with spoon`, ``],
    [`🥗`, `green salad`, ``],
    [`🍿`, `popcorn`, ``],
    [`🧈`, `butter`, ``],
    [`🧂`, `salt`, ``],
    [`🥫`, `canned food`, ``],
    [`🍱`, `bento box`, ``],
    [`🍘`, `rice cracker`, ``],
    [`🍙`, `rice ball`, ``],
    [`🍚`, `cooked rice`, ``],
    [`🍛`, `curry rice`, ``],
    [`🍜`, `steaming bowl`, `ramen noodles`],
    [`🍝`, `spaghetti`, `pasta`],
    [`🍠`, `roasted sweet potato`, ``],
    [`🍢`, `oden`, ``],
    [`🍣`, `sushi`, ``],
    [`🍤`, `fried shrimp`, ``],
    [`🍥`, `fish cake with swirl`, ``],
    [`🥮`, `moon cake`, ``],
    [`🍡`, `dango`, ``],
    [`🥟`, `dumpling`, ``],
    [`🥠`, `fortune cookie`, ``],
    [`🥡`, `takeout box`, ``],
    [`🍦`, `soft ice cream`, ``],
    [`🍧`, `shaved ice`, ``],
    [`🍨`, `ice cream`, ``],
    [`🍩`, `doughnut`, `donut`],
    [`🍪`, `cookie`, ``],
    [`🎂`, `birthday cake`, ``],
    [`🍰`, `shortcake`, `cake slice`],
    [`🧁`, `cupcake`, ``],
    [`🥧`, `pie`, ``],
    [`🍫`, `chocolate bar`, ``],
    [`🍬`, `candy`, ``],
    [`🍭`, `lollipop`, ``],
    [`🍮`, `custard`, ``],
    [`🍯`, `honey pot`, ``],
    [`🍼`, `baby bottle`, ``],
    [`🥛`, `glass of milk`, ``],
    [`☕`, `hot beverage`, `coffee tea`],
    [`🫖`, `teapot`, ``],
    [`🍵`, `teacup without handle`, ``],
    [`🍶`, `sake`, ``],
    [`🍾`, `bottle with popping cork`, `champagne`],
    [`🍷`, `wine glass`, ``],
    [`🍸`, `cocktail glass`, ``],
    [`🍹`, `tropical drink`, ``],
    [`🍺`, `beer mug`, ``],
    [`🍻`, `clinking beer mugs`, `cheers`],
    [`🥂`, `clinking glasses`, `cheers`],
    [`🥃`, `tumbler glass`, ``],
    [`🥤`, `cup with straw`, ``],
    [`🧋`, `bubble tea`, ``],
    [`🧃`, `beverage box`, ``],
    [`🧉`, `mate`, ``],
    [`🧊`, `ice`, ``],
    [`🥢`, `chopsticks`, ``],
    [`🍽️`, `fork and knife with plate`, ``],
    [`🍴`, `fork and knife`, ``],
    [`🥄`, `spoon`, ``],
    [`🔪`, `kitchen knife`, ``],
    [`🏺`, `amphora`, ``]
];

const ACTIVITIES: ReadonlyArray<Row> = [
    [`⚽`, `soccer ball`, `football`],
    [`🏀`, `basketball`, ``],
    [`🏈`, `american football`, ``],
    [`⚾`, `baseball`, ``],
    [`🥎`, `softball`, ``],
    [`🎾`, `tennis`, ``],
    [`🏐`, `volleyball`, ``],
    [`🏉`, `rugby football`, ``],
    [`🥏`, `flying disc`, `frisbee`],
    [`🎱`, `pool 8 ball`, `billiards`],
    [`🪀`, `yo yo`, ``],
    [`🏓`, `ping pong`, ``],
    [`🏸`, `badminton`, ``],
    [`🏒`, `ice hockey`, ``],
    [`🏑`, `field hockey`, ``],
    [`🥍`, `lacrosse`, ``],
    [`🏏`, `cricket game`, ``],
    [`🪃`, `boomerang`, ``],
    [`🥅`, `goal net`, ``],
    [`⛳`, `flag in hole`, `golf`],
    [`🪁`, `kite`, ``],
    [`🏹`, `bow and arrow`, `archery`],
    [`🎣`, `fishing pole`, ``],
    [`🤿`, `diving mask`, ``],
    [`🥊`, `boxing glove`, ``],
    [`🥋`, `martial arts uniform`, ``],
    [`🎽`, `running shirt`, ``],
    [`🛹`, `skateboard`, ``],
    [`🛷`, `sled`, ``],
    [`⛸️`, `ice skate`, ``],
    [`🥌`, `curling stone`, ``],
    [`🎿`, `skis`, ``],
    [`⛷️`, `skier`, ``],
    [`🏂`, `snowboarder`, ``, 1],
    [`🪂`, `parachute`, ``],
    [`🏋️`, `person lifting weights`, ``, 1],
    [`🤼`, `people wrestling`, ``],
    [`🤸`, `person cartwheeling`, ``, 1],
    [`⛹️`, `person bouncing ball`, ``, 1],
    [`🤺`, `person fencing`, ``],
    [`🤾`, `person playing handball`, ``, 1],
    [`🏌️`, `person golfing`, ``, 1],
    [`🏇`, `horse racing`, ``, 1],
    [`🧘`, `person in lotus position`, `yoga`, 1],
    [`🏄`, `person surfing`, ``, 1],
    [`🏊`, `person swimming`, ``, 1],
    [`🤽`, `person playing water polo`, ``, 1],
    [`🚣`, `person rowing boat`, ``, 1],
    [`🧗`, `person climbing`, ``, 1],
    [`🚵`, `person mountain biking`, ``, 1],
    [`🚴`, `person biking`, ``, 1],
    [`🏆`, `trophy`, `winner`],
    [`🥇`, `1st place medal`, `gold`],
    [`🥈`, `2nd place medal`, `silver`],
    [`🥉`, `3rd place medal`, `bronze`],
    [`🏅`, `sports medal`, ``],
    [`🎖️`, `military medal`, ``],
    [`🎗️`, `reminder ribbon`, ``],
    [`🎫`, `ticket`, ``],
    [`🎟️`, `admission tickets`, ``],
    [`🎪`, `circus tent`, ``],
    [`🤹`, `person juggling`, ``, 1],
    [`🎭`, `performing arts`, ``],
    [`🩰`, `ballet shoes`, ``],
    [`🎨`, `artist palette`, ``],
    [`🎬`, `clapper board`, `movie film`],
    [`🎤`, `microphone`, ``],
    [`🎧`, `headphone`, `music`],
    [`🎼`, `musical score`, ``],
    [`🎹`, `musical keyboard`, `piano`],
    [`🥁`, `drum`, ``],
    [`🪘`, `long drum`, ``],
    [`🎷`, `saxophone`, ``],
    [`🎺`, `trumpet`, ``],
    [`🎸`, `guitar`, ``],
    [`🪕`, `banjo`, ``],
    [`🎻`, `violin`, ``],
    [`🪗`, `accordion`, ``],
    [`🎲`, `game die`, `dice`],
    [`♟️`, `chess pawn`, ``],
    [`🎯`, `bullseye`, `darts target`],
    [`🎳`, `bowling`, ``],
    [`🎮`, `video game`, `gaming controller`],
    [`🎰`, `slot machine`, ``],
    [`🧩`, `puzzle piece`, ``]
];

const TRAVEL: ReadonlyArray<Row> = [
    [`🚗`, `automobile`, `car`],
    [`🚕`, `taxi`, ``],
    [`🚙`, `sport utility vehicle`, `suv`],
    [`🚌`, `bus`, ``],
    [`🚎`, `trolleybus`, ``],
    [`🏎️`, `racing car`, ``],
    [`🚓`, `police car`, ``],
    [`🚑`, `ambulance`, ``],
    [`🚒`, `fire engine`, ``],
    [`🚐`, `minibus`, ``],
    [`🛻`, `pickup truck`, ``],
    [`🚚`, `delivery truck`, ``],
    [`🚛`, `articulated lorry`, `truck`],
    [`🚜`, `tractor`, ``],
    [`🦽`, `manual wheelchair`, ``],
    [`🦼`, `motorized wheelchair`, ``],
    [`🛴`, `kick scooter`, ``],
    [`🚲`, `bicycle`, `bike`],
    [`🛵`, `motor scooter`, ``],
    [`🏍️`, `motorcycle`, ``],
    [`🛺`, `auto rickshaw`, ``],
    [`🚨`, `police car light`, `siren`],
    [`🚔`, `oncoming police car`, ``],
    [`🚍`, `oncoming bus`, ``],
    [`🚘`, `oncoming automobile`, ``],
    [`🚖`, `oncoming taxi`, ``],
    [`🚡`, `aerial tramway`, ``],
    [`🚠`, `mountain cableway`, ``],
    [`🚟`, `suspension railway`, ``],
    [`🚃`, `railway car`, ``],
    [`🚋`, `tram car`, ``],
    [`🚞`, `mountain railway`, ``],
    [`🚝`, `monorail`, ``],
    [`🚄`, `high speed train`, ``],
    [`🚅`, `bullet train`, ``],
    [`🚆`, `train`, ``],
    [`🚇`, `metro`, `subway`],
    [`🚈`, `light rail`, ``],
    [`🚉`, `station`, ``],
    [`🚊`, `tram`, ``],
    [`🚂`, `locomotive`, `train`],
    [`✈️`, `airplane`, `plane`],
    [`🛫`, `airplane departure`, ``],
    [`🛬`, `airplane arrival`, ``],
    [`🪂`, `parachute`, ``],
    [`💺`, `seat`, ``],
    [`🚀`, `rocket`, ``],
    [`🛸`, `flying saucer`, `ufo`],
    [`🚁`, `helicopter`, ``],
    [`🛶`, `canoe`, ``],
    [`⛵`, `sailboat`, ``],
    [`🚤`, `speedboat`, ``],
    [`🛥️`, `motor boat`, ``],
    [`🛳️`, `passenger ship`, ``],
    [`⛴️`, `ferry`, ``],
    [`🚢`, `ship`, ``],
    [`⚓`, `anchor`, ``],
    [`⛽`, `fuel pump`, `gas station`],
    [`🚧`, `construction`, ``],
    [`🚦`, `vertical traffic light`, ``],
    [`🚥`, `horizontal traffic light`, ``],
    [`🗺️`, `world map`, ``],
    [`🗿`, `moai`, `easter island`],
    [`🗽`, `statue of liberty`, ``],
    [`🗼`, `tokyo tower`, ``],
    [`🏰`, `castle`, ``],
    [`🏯`, `japanese castle`, ``],
    [`🏟️`, `stadium`, ``],
    [`🎡`, `ferris wheel`, ``],
    [`🎢`, `roller coaster`, ``],
    [`🎠`, `carousel horse`, ``],
    [`⛲`, `fountain`, ``],
    [`⛱️`, `umbrella on ground`, `beach`],
    [`🏖️`, `beach with umbrella`, ``],
    [`🏝️`, `desert island`, ``],
    [`🏜️`, `desert`, ``],
    [`🌋`, `volcano`, ``],
    [`⛰️`, `mountain`, ``],
    [`🏔️`, `snow capped mountain`, ``],
    [`🗻`, `mount fuji`, ``],
    [`🏕️`, `camping`, ``],
    [`⛺`, `tent`, ``],
    [`🏠`, `house`, ``],
    [`🏡`, `house with garden`, ``],
    [`🏘️`, `houses`, ``],
    [`🏚️`, `derelict house`, ``],
    [`🏗️`, `building construction`, ``],
    [`🏭`, `factory`, ``],
    [`🏢`, `office building`, ``],
    [`🏬`, `department store`, ``],
    [`🏣`, `japanese post office`, ``],
    [`🏤`, `post office`, ``],
    [`🏥`, `hospital`, ``],
    [`🏦`, `bank`, ``],
    [`🏨`, `hotel`, ``],
    [`🏪`, `convenience store`, ``],
    [`🏫`, `school`, ``],
    [`🏩`, `love hotel`, ``],
    [`💒`, `wedding`, ``],
    [`🏛️`, `classical building`, ``],
    [`⛪`, `church`, ``],
    [`🕌`, `mosque`, ``],
    [`🕍`, `synagogue`, ``],
    [`🛕`, `hindu temple`, ``],
    [`🕋`, `kaaba`, ``],
    [`⛩️`, `shinto shrine`, ``],
    [`🛤️`, `railway track`, ``],
    [`🛣️`, `motorway`, ``],
    [`🌅`, `sunrise`, ``],
    [`🌄`, `sunrise over mountains`, ``],
    [`🌠`, `shooting star`, ``],
    [`🎇`, `sparkler`, ``],
    [`🎆`, `fireworks`, ``],
    [`🌇`, `sunset`, ``],
    [`🌆`, `cityscape at dusk`, ``],
    [`🏙️`, `cityscape`, ``],
    [`🌃`, `night with stars`, ``],
    [`🌌`, `milky way`, ``],
    [`🌉`, `bridge at night`, ``],
    [`🌁`, `foggy`, ``]
];

const OBJECTS: ReadonlyArray<Row> = [
    [`⌚`, `watch`, ``],
    [`📱`, `mobile phone`, ``],
    [`📲`, `mobile phone with arrow`, ``],
    [`💻`, `laptop`, ``],
    [`⌨️`, `keyboard`, ``],
    [`🖥️`, `desktop computer`, ``],
    [`🖨️`, `printer`, ``],
    [`🖱️`, `computer mouse`, ``],
    [`🖲️`, `trackball`, ``],
    [`🕹️`, `joystick`, ``],
    [`🗜️`, `clamp`, ``],
    [`💽`, `computer disk`, ``],
    [`💾`, `floppy disk`, ``],
    [`💿`, `optical disk`, ``],
    [`📀`, `dvd`, ``],
    [`📼`, `videocassette`, ``],
    [`📷`, `camera`, ``],
    [`📸`, `camera with flash`, ``],
    [`📹`, `video camera`, ``],
    [`🎥`, `movie camera`, ``],
    [`📽️`, `film projector`, ``],
    [`🎞️`, `film frames`, ``],
    [`📞`, `telephone receiver`, ``],
    [`☎️`, `telephone`, ``],
    [`📟`, `pager`, ``],
    [`📠`, `fax machine`, ``],
    [`📺`, `television`, `tv`],
    [`📻`, `radio`, ``],
    [`🎙️`, `studio microphone`, ``],
    [`🎚️`, `level slider`, ``],
    [`🎛️`, `control knobs`, ``],
    [`🧭`, `compass`, ``],
    [`⏱️`, `stopwatch`, ``],
    [`⏲️`, `timer clock`, ``],
    [`⏰`, `alarm clock`, ``],
    [`🕰️`, `mantelpiece clock`, ``],
    [`⌛`, `hourglass done`, ``],
    [`⏳`, `hourglass not done`, ``],
    [`📡`, `satellite antenna`, ``],
    [`🔋`, `battery`, ``],
    [`🔌`, `electric plug`, ``],
    [`💡`, `light bulb`, `idea`],
    [`🔦`, `flashlight`, ``],
    [`🕯️`, `candle`, ``],
    [`🪔`, `diya lamp`, ``],
    [`🧯`, `fire extinguisher`, ``],
    [`🛢️`, `oil drum`, ``],
    [`💸`, `money with wings`, ``],
    [`💵`, `dollar banknote`, ``],
    [`💴`, `yen banknote`, ``],
    [`💶`, `euro banknote`, ``],
    [`💷`, `pound banknote`, ``],
    [`🪙`, `coin`, ``],
    [`💰`, `money bag`, ``],
    [`💳`, `credit card`, ``],
    [`💎`, `gem stone`, `diamond`],
    [`⚖️`, `balance scale`, `justice`],
    [`🧰`, `toolbox`, ``],
    [`🔧`, `wrench`, ``],
    [`🔨`, `hammer`, ``],
    [`⚒️`, `hammer and pick`, ``],
    [`🛠️`, `hammer and wrench`, ``],
    [`⛏️`, `pick`, ``],
    [`🔩`, `nut and bolt`, ``],
    [`⚙️`, `gear`, `settings`],
    [`🧱`, `brick`, ``],
    [`⛓️`, `chains`, ``],
    [`🧲`, `magnet`, ``],
    [`🔫`, `water pistol`, ``],
    [`💣`, `bomb`, ``],
    [`🧨`, `firecracker`, ``],
    [`🪓`, `axe`, ``],
    [`🔪`, `kitchen knife`, ``],
    [`🗡️`, `dagger`, ``],
    [`⚔️`, `crossed swords`, ``],
    [`🛡️`, `shield`, ``],
    [`🚬`, `cigarette`, ``],
    [`⚰️`, `coffin`, ``],
    [`⚱️`, `funeral urn`, ``],
    [`🧫`, `petri dish`, ``],
    [`🧪`, `test tube`, ``],
    [`🧬`, `dna`, ``],
    [`🔬`, `microscope`, ``],
    [`🔭`, `telescope`, ``],
    [`💉`, `syringe`, ``],
    [`🩸`, `drop of blood`, ``],
    [`💊`, `pill`, ``],
    [`🩹`, `adhesive bandage`, ``],
    [`🩺`, `stethoscope`, ``],
    [`🚪`, `door`, ``],
    [`🛏️`, `bed`, ``],
    [`🛋️`, `couch and lamp`, ``],
    [`🪑`, `chair`, ``],
    [`🚽`, `toilet`, ``],
    [`🚿`, `shower`, ``],
    [`🛁`, `bathtub`, ``],
    [`🪒`, `razor`, ``],
    [`🧴`, `lotion bottle`, ``],
    [`🧷`, `safety pin`, ``],
    [`🧹`, `broom`, ``],
    [`🧺`, `basket`, ``],
    [`🧻`, `roll of paper`, `toilet paper`],
    [`🧼`, `soap`, ``],
    [`🧽`, `sponge`, ``],
    [`🪣`, `bucket`, ``],
    [`🛒`, `shopping cart`, ``],
    [`🧳`, `luggage`, `suitcase`],
    [`🌂`, `closed umbrella`, ``],
    [`☂️`, `umbrella`, ``],
    [`🎈`, `balloon`, ``],
    [`🎉`, `party popper`, `tada celebrate`],
    [`🎊`, `confetti ball`, ``],
    [`🎎`, `japanese dolls`, ``],
    [`🎏`, `carp streamer`, ``],
    [`🎐`, `wind chime`, ``],
    [`🎀`, `ribbon`, ``],
    [`🎁`, `wrapped gift`, `present`],
    [`📦`, `package`, `box`],
    [`📫`, `closed mailbox with raised flag`, ``],
    [`📪`, `closed mailbox`, ``],
    [`📬`, `open mailbox with raised flag`, ``],
    [`📭`, `open mailbox`, ``],
    [`📮`, `postbox`, ``],
    [`🗳️`, `ballot box`, ``],
    [`✏️`, `pencil`, ``],
    [`✒️`, `black nib`, ``],
    [`🖋️`, `fountain pen`, ``],
    [`🖊️`, `pen`, ``],
    [`🖌️`, `paintbrush`, ``],
    [`🖍️`, `crayon`, ``],
    [`📝`, `memo`, `note write`],
    [`📁`, `file folder`, ``],
    [`📂`, `open file folder`, ``],
    [`🗂️`, `card index dividers`, ``],
    [`📅`, `calendar`, ``],
    [`📆`, `tear off calendar`, ``],
    [`🗒️`, `spiral notepad`, ``],
    [`🗓️`, `spiral calendar`, ``],
    [`📇`, `card index`, ``],
    [`📈`, `chart increasing`, ``],
    [`📉`, `chart decreasing`, ``],
    [`📊`, `bar chart`, ``],
    [`📋`, `clipboard`, ``],
    [`📌`, `pushpin`, ``],
    [`📍`, `round pushpin`, ``],
    [`📎`, `paperclip`, ``],
    [`🖇️`, `linked paperclips`, ``],
    [`📏`, `straight ruler`, ``],
    [`📐`, `triangular ruler`, ``],
    [`✂️`, `scissors`, ``],
    [`🗃️`, `card file box`, ``],
    [`🗄️`, `file cabinet`, ``],
    [`🗑️`, `wastebasket`, `trash`],
    [`🔒`, `locked`, ``],
    [`🔓`, `unlocked`, ``],
    [`🔏`, `locked with pen`, ``],
    [`🔐`, `locked with key`, ``],
    [`🔑`, `key`, ``],
    [`🗝️`, `old key`, ``],
    [`🔍`, `magnifying glass tilted left`, `search`],
    [`🔎`, `magnifying glass tilted right`, `search`],
    [`📖`, `open book`, ``],
    [`📔`, `notebook with decorative cover`, ``],
    [`📕`, `closed book`, ``],
    [`📗`, `green book`, ``],
    [`📘`, `blue book`, ``],
    [`📙`, `orange book`, ``],
    [`📚`, `books`, ``],
    [`📓`, `notebook`, ``],
    [`📒`, `ledger`, ``],
    [`📃`, `page with curl`, ``],
    [`📜`, `scroll`, ``],
    [`📄`, `page facing up`, ``],
    [`📰`, `newspaper`, ``],
    [`🗞️`, `rolled up newspaper`, ``],
    [`🏷️`, `label`, `tag`]
];

const SYMBOLS: ReadonlyArray<Row> = [
    [`❤️`, `red heart`, `love`],
    [`🧡`, `orange heart`, ``],
    [`💛`, `yellow heart`, ``],
    [`💚`, `green heart`, ``],
    [`💙`, `blue heart`, ``],
    [`💜`, `purple heart`, ``],
    [`🖤`, `black heart`, ``],
    [`🤍`, `white heart`, ``],
    [`🤎`, `brown heart`, ``],
    [`💔`, `broken heart`, ``],
    [`❣️`, `heart exclamation`, ``],
    [`💕`, `two hearts`, ``],
    [`💞`, `revolving hearts`, ``],
    [`💓`, `beating heart`, ``],
    [`💗`, `growing heart`, ``],
    [`💖`, `sparkling heart`, ``],
    [`💘`, `heart with arrow`, ``],
    [`💝`, `heart with ribbon`, ``],
    [`💟`, `heart decoration`, ``],
    [`☮️`, `peace symbol`, ``],
    [`✝️`, `latin cross`, ``],
    [`☪️`, `star and crescent`, ``],
    [`🕉️`, `om`, ``],
    [`☸️`, `wheel of dharma`, ``],
    [`✡️`, `star of david`, ``],
    [`🔯`, `dotted six pointed star`, ``],
    [`🕎`, `menorah`, ``],
    [`☯️`, `yin yang`, ``],
    [`☦️`, `orthodox cross`, ``],
    [`🛐`, `place of worship`, ``],
    [`⛎`, `ophiuchus`, ``],
    [`♈`, `aries`, ``],
    [`♉`, `taurus`, ``],
    [`♊`, `gemini`, ``],
    [`♋`, `cancer`, ``],
    [`♌`, `leo`, ``],
    [`♍`, `virgo`, ``],
    [`♎`, `libra`, ``],
    [`♏`, `scorpio`, ``],
    [`♐`, `sagittarius`, ``],
    [`♑`, `capricorn`, ``],
    [`♒`, `aquarius`, ``],
    [`♓`, `pisces`, ``],
    [`🆔`, `id button`, ``],
    [`⚛️`, `atom symbol`, ``],
    [`🉑`, `accept`, ``],
    [`☢️`, `radioactive`, ``],
    [`☣️`, `biohazard`, ``],
    [`📴`, `mobile phone off`, ``],
    [`📳`, `vibration mode`, ``],
    [`🈶`, `Japanese not free of charge`, ``],
    [`🈚`, `Japanese free of charge`, ``],
    [`🈸`, `Japanese application`, ``],
    [`🈺`, `Japanese open for business`, ``],
    [`🈷️`, `Japanese monthly amount`, ``],
    [`✴️`, `eight pointed star`, ``],
    [`🆚`, `vs button`, ``],
    [`🉐`, `bargain`, ``],
    [`㊙️`, `Japanese secret`, ``],
    [`㊗️`, `Japanese congratulations`, ``],
    [`🈴`, `Japanese passing`, ``],
    [`🈵`, `Japanese no vacancy`, ``],
    [`🈹`, `Japanese discount`, ``],
    [`🈲`, `Japanese prohibited`, ``],
    [`🅰️`, `A button blood type`, ``],
    [`🅱️`, `B button blood type`, ``],
    [`🆎`, `AB button blood type`, ``],
    [`🆑`, `CL button`, ``],
    [`🅾️`, `O button blood type`, ``],
    [`🆘`, `sos`, ``],
    [`❌`, `cross mark`, ``],
    [`⭕`, `hollow red circle`, ``],
    [`🛑`, `stop sign`, ``],
    [`⛔`, `no entry`, ``],
    [`📛`, `name badge`, ``],
    [`🚫`, `prohibited`, ``],
    [`💯`, `hundred points`, ``],
    [`💢`, `anger symbol`, ``],
    [`♨️`, `hot springs`, ``],
    [`🚷`, `no pedestrians`, ``],
    [`🚯`, `no littering`, ``],
    [`🚳`, `no bicycles`, ``],
    [`🚱`, `non-potable water`, ``],
    [`🔞`, `no one under eighteen`, ``],
    [`📵`, `no mobile phones`, ``],
    [`🚭`, `no smoking`, ``],
    [`❗`, `red exclamation mark`, ``],
    [`❕`, `white exclamation mark`, ``],
    [`❓`, `red question mark`, ``],
    [`❔`, `white question mark`, ``],
    [`‼️`, `double exclamation`, ``],
    [`⁉️`, `exclamation question`, ``],
    [`🔅`, `dim button`, ``],
    [`🔆`, `bright button`, ``],
    [`〽️`, `part alternation mark`, ``],
    [`⚠️`, `warning`, ``],
    [`🚸`, `children crossing`, ``],
    [`🔱`, `trident emblem`, ``],
    [`⚜️`, `fleur de lis`, ``],
    [`🔰`, `Japanese symbol for beginner`, ``],
    [`♻️`, `recycling`, ``],
    [`✅`, `check mark button`, `tick yes`],
    [`🈯`, `Japanese reserved`, ``],
    [`💹`, `chart increasing yen`, ``],
    [`❇️`, `sparkle`, ``],
    [`✳️`, `eight spoked asterisk`, ``],
    [`❎`, `cross mark button`, ``],
    [`🌐`, `globe with meridians`, ``],
    [`💠`, `diamond with a dot`, ``],
    [`Ⓜ️`, `circled M`, ``],
    [`🌀`, `cyclone`, ``],
    [`💤`, `zzz`, `sleep`],
    [`🏧`, `ATM sign`, ``],
    [`🚾`, `water closet`, ``],
    [`♿`, `wheelchair symbol`, ``],
    [`🅿️`, `P button parking`, ``],
    [`🛗`, `elevator`, ``],
    [`🈳`, `Japanese vacancy`, ``],
    [`🈂️`, `Japanese service charge`, ``],
    [`🛂`, `passport control`, ``],
    [`🛃`, `customs`, ``],
    [`🛄`, `baggage claim`, ``],
    [`🛅`, `left luggage`, ``],
    [`🚹`, `mens room`, ``],
    [`🚺`, `womens room`, ``],
    [`🚼`, `baby symbol`, ``],
    [`🚻`, `restroom`, ``],
    [`🚮`, `litter in bin sign`, ``],
    [`🎦`, `cinema`, ``],
    [`📶`, `antenna bars`, ``],
    [`🈁`, `Japanese here`, ``],
    [`🔣`, `input symbols`, ``],
    [`ℹ️`, `information`, ``],
    [`🔤`, `input latin letters`, ``],
    [`🔡`, `input latin lowercase`, ``],
    [`🔠`, `input latin uppercase`, ``],
    [`🆖`, `NG button`, ``],
    [`🆗`, `OK button`, ``],
    [`🆙`, `UP button`, ``],
    [`🆒`, `COOL button`, ``],
    [`🆕`, `NEW button`, ``],
    [`🆓`, `FREE button`, ``],
    [`0️⃣`, `digit zero`, ``],
    [`1️⃣`, `digit one`, ``],
    [`2️⃣`, `digit two`, ``],
    [`3️⃣`, `digit three`, ``],
    [`4️⃣`, `digit four`, ``],
    [`5️⃣`, `digit five`, ``],
    [`6️⃣`, `digit six`, ``],
    [`7️⃣`, `digit seven`, ``],
    [`8️⃣`, `digit eight`, ``],
    [`9️⃣`, `digit nine`, ``],
    [`🔟`, `keycap ten`, ``],
    [`🔢`, `input numbers`, ``],
    [`#️⃣`, `keycap number sign`, ``],
    [`*️⃣`, `keycap asterisk`, ``],
    [`⏏️`, `eject button`, ``],
    [`▶️`, `play button`, ``],
    [`⏸️`, `pause button`, ``],
    [`⏯️`, `play or pause`, ``],
    [`⏹️`, `stop button`, ``],
    [`⏺️`, `record button`, ``],
    [`⏭️`, `next track button`, ``],
    [`⏮️`, `last track button`, ``],
    [`⏩`, `fast forward`, ``],
    [`⏪`, `fast reverse`, ``],
    [`⏫`, `fast up`, ``],
    [`⏬`, `fast down`, ``],
    [`◀️`, `reverse button`, ``],
    [`🔼`, `upwards button`, ``],
    [`🔽`, `downwards button`, ``],
    [`➡️`, `right arrow`, ``],
    [`⬅️`, `left arrow`, ``],
    [`⬆️`, `up arrow`, ``],
    [`⬇️`, `down arrow`, ``],
    [`↗️`, `up right arrow`, ``],
    [`↘️`, `down right arrow`, ``],
    [`↙️`, `down left arrow`, ``],
    [`↖️`, `up left arrow`, ``],
    [`↕️`, `up down arrow`, ``],
    [`↔️`, `left right arrow`, ``],
    [`↪️`, `right arrow curving left`, ``],
    [`↩️`, `left arrow curving right`, ``],
    [`⤴️`, `right arrow curving up`, ``],
    [`⤵️`, `right arrow curving down`, ``],
    [`🔀`, `shuffle tracks`, ``],
    [`🔁`, `repeat`, ``],
    [`🔂`, `repeat single`, ``],
    [`🔄`, `counterclockwise arrows`, ``],
    [`🔃`, `clockwise arrows`, ``],
    [`🎵`, `musical note`, ``],
    [`🎶`, `musical notes`, ``],
    [`➕`, `plus`, ``],
    [`➖`, `minus`, ``],
    [`➗`, `divide`, ``],
    [`✖️`, `multiply`, ``],
    [`♾️`, `infinity`, ``],
    [`💲`, `heavy dollar sign`, ``],
    [`💱`, `currency exchange`, ``],
    [`™️`, `trade mark`, ``],
    [`©️`, `copyright`, ``],
    [`®️`, `registered`, ``],
    [`👁️‍🗨️`, `eye in speech bubble`, ``],
    [`🔚`, `END arrow`, ``],
    [`🔙`, `BACK arrow`, ``],
    [`🔛`, `ON arrow`, ``],
    [`🔝`, `TOP arrow`, ``],
    [`🔜`, `SOON arrow`, ``],
    [`〰️`, `wavy dash`, ``],
    [`➰`, `curly loop`, ``],
    [`➿`, `double curly loop`, ``],
    [`✔️`, `check mark`, `tick`],
    [`☑️`, `check box with check`, ``],
    [`🔘`, `radio button`, ``],
    [`⚪`, `white circle`, ``],
    [`⚫`, `black circle`, ``],
    [`🔴`, `red circle`, ``],
    [`🔵`, `blue circle`, ``],
    [`🟤`, `brown circle`, ``],
    [`🟣`, `purple circle`, ``],
    [`🟢`, `green circle`, ``],
    [`🟡`, `yellow circle`, ``],
    [`🟠`, `orange circle`, ``],
    [`🔺`, `red triangle pointed up`, ``],
    [`🔻`, `red triangle pointed down`, ``],
    [`🔸`, `small orange diamond`, ``],
    [`🔹`, `small blue diamond`, ``],
    [`🔶`, `large orange diamond`, ``],
    [`🔷`, `large blue diamond`, ``],
    [`🔳`, `white square button`, ``],
    [`🔲`, `black square button`, ``],
    [`▪️`, `black small square`, ``],
    [`▫️`, `white small square`, ``],
    [`◾`, `black medium small square`, ``],
    [`◽`, `white medium small square`, ``],
    [`◼️`, `black medium square`, ``],
    [`◻️`, `white medium square`, ``],
    [`⬛`, `black large square`, ``],
    [`⬜`, `white large square`, ``],
    [`🟫`, `brown square`, ``],
    [`🟪`, `purple square`, ``],
    [`🟦`, `blue square`, ``],
    [`🟩`, `green square`, ``],
    [`🟨`, `yellow square`, ``],
    [`🟧`, `orange square`, ``],
    [`🟥`, `red square`, ``],
    [`💬`, `speech balloon`, ``],
    [`🗨️`, `left speech bubble`, ``],
    [`🗯️`, `right anger bubble`, ``],
    [`💭`, `thought balloon`, ``],
    [`✨`, `sparkles`, `magic`],
    [`💫`, `dizzy`, ``],
    [`💥`, `collision`, ``],
    [`🔥`, `fire`, `hot lit`],
    [`🌟`, `glowing star`, ``],
    [`⭐`, `star`, ``],
    [`☀️`, `sun`, ``],
    [`🌤️`, `sun behind small cloud`, ``],
    [`⛅`, `sun behind cloud`, ``],
    [`🌥️`, `sun behind large cloud`, ``],
    [`☁️`, `cloud`, ``],
    [`🌦️`, `sun behind rain cloud`, ``],
    [`🌧️`, `cloud with rain`, ``],
    [`⛈️`, `cloud with lightning and rain`, ``],
    [`🌩️`, `cloud with lightning`, ``],
    [`🌨️`, `cloud with snow`, ``],
    [`❄️`, `snowflake`, ``],
    [`⛄`, `snowman without snow`, ``],
    [`☃️`, `snowman`, ``],
    [`🌬️`, `wind face`, ``],
    [`💨`, `dashing away`, ``],
    [`💧`, `droplet`, ``],
    [`💦`, `sweat droplets`, ``],
    [`☔`, `umbrella with rain drops`, ``],
    [`🌈`, `rainbow`, ``],
    [`🌊`, `water wave`, ``],
    [`🌫️`, `fog`, ``]
];

const FLAGS: ReadonlyArray<Row> = [
    [`🏳️`, `white flag`, ``],
    [`🏴`, `black flag`, ``],
    [`🏁`, `chequered flag`, `finish`],
    [`🚩`, `triangular flag`, ``],
    [`🏳️‍🌈`, `rainbow flag`, `pride lgbt`],
    [`🏳️‍⚧️`, `transgender flag`, ``],
    [`🏴‍☠️`, `pirate flag`, ``],
    [`🇦🇺`, `australia`, `flag`],
    [`🇦🇹`, `austria`, `flag`],
    [`🇧🇪`, `belgium`, `flag`],
    [`🇧🇷`, `brazil`, `flag`],
    [`🇨🇦`, `canada`, `flag`],
    [`🇨🇳`, `china`, `flag`],
    [`🇨🇿`, `czechia`, `flag`],
    [`🇩🇰`, `denmark`, `flag`],
    [`🇫🇮`, `finland`, `flag`],
    [`🇫🇷`, `france`, `flag`],
    [`🇩🇪`, `germany`, `flag`],
    [`🇬🇷`, `greece`, `flag`],
    [`🇭🇰`, `hong kong sar china`, `flag`],
    [`🇮🇳`, `india`, `flag`],
    [`🇮🇩`, `indonesia`, `flag`],
    [`🇮🇪`, `ireland`, `flag`],
    [`🇮🇱`, `israel`, `flag`],
    [`🇮🇹`, `italy`, `flag`],
    [`🇯🇵`, `japan`, `flag`],
    [`🇰🇷`, `south korea`, `flag`],
    [`🇲🇽`, `mexico`, `flag`],
    [`🇳🇱`, `netherlands`, `flag`],
    [`🇳🇿`, `new zealand`, `flag`],
    [`🇳🇴`, `norway`, `flag`],
    [`🇵🇱`, `poland`, `flag`],
    [`🇵🇹`, `portugal`, `flag`],
    [`🇷🇺`, `russia`, `flag`],
    [`🇸🇦`, `saudi arabia`, `flag`],
    [`🇸🇬`, `singapore`, `flag`],
    [`🇿🇦`, `south africa`, `flag`],
    [`🇪🇸`, `spain`, `flag`],
    [`🇸🇪`, `sweden`, `flag`],
    [`🇨🇭`, `switzerland`, `flag`],
    [`🇹🇼`, `taiwan`, `flag`],
    [`🇹🇭`, `thailand`, `flag`],
    [`🇹🇷`, `turkey`, `flag`],
    [`🇦🇪`, `united arab emirates`, `flag`],
    [`🇬🇧`, `united kingdom`, `flag`],
    [`🇺🇸`, `united states`, `flag`],
    [`🇻🇳`, `vietnam`, `flag`],
    [`🇺🇦`, `ukraine`, `flag`]
];

const expand = (rows: ReadonlyArray<Row>, category: EmojiCategoryId): EmojiEntry[] =>
    rows.map(([char, name, keywords, hasSkinTone]) => ({
        char,
        name,
        keywords: keywords.length > 0 ? keywords.split(/\s+/) : [],
        category,
        hasSkinTone: hasSkinTone === 1
    }));

export const EMOJI_DATA: ReadonlyArray<EmojiEntry> = [
    ...expand(SMILEYS, `smileys`),
    ...expand(PEOPLE, `people`),
    ...expand(ANIMALS, `animals`),
    ...expand(FOOD, `food`),
    ...expand(ACTIVITIES, `activities`),
    ...expand(TRAVEL, `travel`),
    ...expand(OBJECTS, `objects`),
    ...expand(SYMBOLS, `symbols`),
    ...expand(FLAGS, `flags`)
];

// Index by category for O(1) tab-switch lookup. Filtering on every render
// adds up at 500+ entries; the picker reads from this map instead.
const indexByCategory = new Map<EmojiCategoryId, EmojiEntry[]>();
for (const entry of EMOJI_DATA) {
    const bucket = indexByCategory.get(entry.category);
    if (bucket) bucket.push(entry);
    else indexByCategory.set(entry.category, [entry]);
}

// Set membership lookup for `applySkinTone` — see the function comment.
const SKIN_TONE_CAPABLE_CHARS = new Set<string>(
    EMOJI_DATA.filter((entry) => entry.hasSkinTone).map((entry) => entry.char)
);

export const emojisInCategory = (id: EmojiCategoryId): ReadonlyArray<EmojiEntry> => {
    return indexByCategory.get(id) ?? [];
};

/**
 * Case-insensitive prefix-and-contains search across name + keywords.
 * Splits the query on whitespace and AND-matches every token so multi-word
 * queries like "smile cat" both narrow the result set.
 */
export const searchEmojis = (query: string): ReadonlyArray<EmojiEntry> => {
    const normalized = query.trim().toLowerCase();
    if (normalized.length === 0) return [];
    const tokens = normalized.split(/\s+/);
    return EMOJI_DATA.filter((entry) => {
        const haystack = `${entry.name} ${entry.keywords.join(` `)}`;
        return tokens.every((tok) => haystack.includes(tok));
    });
};
