/**
 * Translation slice for commandPalette.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to commandPalette's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface CommandPaletteTranslation {
  default: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        closedByDefault: string;
        opensOnControlled: string;
        rendersActions: string;
        filtersBySearch: string;
        dispatchesOnClick: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const commandPaletteEn: CommandPaletteTranslation = {
  default: {
    title: `Default`,
    description: `Opens via the registered action. Type to filter, click or press Enter to dispatch.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<CommandPalette> is mounted once globally inside <MowsProvider>. It registers itself as the handler for CoreActionIds.OPEN_COMMAND_PALETTE and lists every action currently registered with the ActionManager.`,
    },
    composition: {
      title: `Composition`,
      body: `Open via mowsContext.actionManager.dispatchAction(CoreActionIds.OPEN_COMMAND_PALETTE) or by binding a hotkey through HotkeyManager. Pass open / onOpenChange to control state externally.`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Default`,
        description: `Click the button to open the palette, then type to filter the registered actions.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <CommandPalette> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        closedByDefault: `Is closed by default — no list items rendered.`,
        opensOnControlled: `Opens when the controlled open prop flips to true.`,
        rendersActions: `Renders one row per registered action.`,
        filtersBySearch: `Filters the action list by the typed query.`,
        dispatchesOnClick: `Dispatches the action when an item is clicked.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Under dir="rtl" the search input and command list mirror.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <CommandPalette>.`,
    },
  },
};

export const commandPaletteDe: CommandPaletteTranslation = {
  default: {
    title: `Standard`,
    description: `Wird über die registrierte Aktion geöffnet. Tippen filtert, Klick oder Eingabetaste löst die Aktion aus.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Import-Pfade an deine Projektstruktur an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<CommandPalette> wird einmal global innerhalb von <MowsProvider> eingebunden. Sie registriert sich als Handler für CoreActionIds.OPEN_COMMAND_PALETTE und listet alle aktuell beim ActionManager registrierten Aktionen.`,
    },
    composition: {
      title: `Komposition`,
      body: `Öffnen via mowsContext.actionManager.dispatchAction(CoreActionIds.OPEN_COMMAND_PALETTE) oder per Tastenkombination über den HotkeyManager. open / onOpenChange erlauben externes Steuern des Zustands.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Standard`,
        description: `Klicke die Schaltfläche, um die Befehlspalette zu öffnen, und tippe, um die registrierten Aktionen zu filtern.`,
      },
    },
    definedBehaviour: {
      title: `Definiertes Verhalten`,
      intro: `Aussagen darüber, wie sich <CommandPalette> verhalten soll — jede verlinkt mit dem Test, der sie verifiziert.`,
      verifiedBy: `verifiziert durch`,
      statements: {
        closedByDefault: `Ist standardmäßig geschlossen — keine Listeneinträge gerendert.`,
        opensOnControlled: `Öffnet sich, wenn die kontrollierte open-Prop auf true wechselt.`,
        rendersActions: `Rendert eine Zeile pro registrierter Aktion.`,
        filtersBySearch: `Filtert die Aktionsliste anhand der eingegebenen Suche.`,
        dispatchesOnClick: `Löst die Aktion aus, wenn ein Eintrag geklickt wird.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Unter dir="rtl" werden Suchfeld und Befehlsliste gespiegelt.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <CommandPalette> akzeptiert.`,
    },
  },
};
