VERSION 0.7

deps:
    FROM node:21-alpine
    RUN npm i --location=global pnpm

build:
    FROM +deps
    WORKDIR /app
    COPY package.json pnpm-lock.yaml ./
    RUN pnpm install
    COPY . .
    RUN pnpm build
    SAVE ARTIFACT /app/dist/ /dist

docker:
    FROM pektin/feoco
    COPY +build/dist /public/
    COPY server/config.yml /
    EXPOSE 80
    SAVE IMAGE mows-website:latest

local:
    FROM node:21-alpine
    COPY +build/dist /dist
    SAVE ARTIFACT /dist AS LOCAL dist