/**
 * Translation slice for actionDisplay.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to actionDisplay's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface ActionDisplayTranslation {
  default: { title: string; description: string };
  doc: {
    installation: {
      title: string;
      commandTab: string;
      manualTab: string;
      manualStep1: string;
      manualStep2: string;
      manualStep3: string;
    };
    usage: { title: string; body: string };
    composition: { title: string; body: string };
    examples: {
      title: string;
      default: { title: string; description: string };
    };
    definedBehaviour: {
      title: string;
      intro: string;
      verifiedBy: string;
      statements: {
        translatesLabel: string;
        fallsBackToId: string;
        rendersIcon: string;
        exposesDisabledReason: string;
        rendersHotkeys: string;
      };
    };
    rtl: { title: string; body: string };
    apiReference: { title: string; intro: string };
  };
}

export const actionDisplayEn: ActionDisplayTranslation = {
  default: {
    title: `Registered action`,
    description: `Reads the Greet action from the surrounding ActionManager and renders its label + icon + bound hotkeys.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Command`,
      manualTab: `Manual`,
      manualStep1: `Install the following dependencies:`,
      manualStep2: `Copy and paste the following code into your project.`,
      manualStep3: `Update the import paths to match your project setup.`,
    },
    usage: {
      title: `Usage`,
      body: `<ActionDisplay> renders a single Action — its translated label, optional icon, and bound hotkeys. Pull the Action from the surrounding actionManager.`,
    },
    composition: {
      title: `Composition`,
      body: `Action handlers can supply a custom component() in their state to fully override the rendered content (icon + label).`,
    },
    examples: {
      title: `Examples`,
      default: {
        title: `Registered action`,
        description: `Greet + key combo.`,
      },
    },
    definedBehaviour: {
      title: `Defined behaviour`,
      intro: `Statements describing how <ActionDisplay> is expected to behave, each linked to the test that verifies it.`,
      verifiedBy: `verified by`,
      statements: {
        translatesLabel: `Renders the action label from MowsContext.t.actions[id].`,
        fallsBackToId: `Falls back to the action id when no translation is registered.`,
        rendersIcon: `Renders the icon returned by the action state.`,
        exposesDisabledReason: `Exposes disabledReasonText via the title attribute.`,
        rendersHotkeys: `Renders one KeyComboDisplay per registered hotkey.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Under dir="rtl" the label and trailing hotkey row mirror around the icon.`,
    },
    apiReference: {
      title: `API Reference`,
      intro: `Props accepted by <ActionDisplay>.`,
    },
  },
};

export const actionDisplayDe: ActionDisplayTranslation = {
  default: {
    title: `Registrierte Aktion`,
    description: `Liest die Greet-Action vom umgebenden ActionManager und rendert Label + Icon + gebundene Hotkeys.`,
  },
  doc: {
    installation: {
      title: `Installation`,
      commandTab: `Befehl`,
      manualTab: `Manuell`,
      manualStep1: `Installiere die folgenden Abhängigkeiten:`,
      manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
      manualStep3: `Passe die Importpfade an dein Projekt an.`,
    },
    usage: {
      title: `Verwendung`,
      body: `<ActionDisplay> rendert eine einzelne Action — übersetztes Label, optionales Icon und gebundene Hotkeys. Action aus dem umgebenden actionManager holen.`,
    },
    composition: {
      title: `Komposition`,
      body: `Action-Handler können in ihrem State eine eigene component() liefern, die den gerenderten Inhalt vollständig überschreibt.`,
    },
    examples: {
      title: `Beispiele`,
      default: {
        title: `Registrierte Aktion`,
        description: `Greet + Tastenkürzel.`,
      },
    },
    definedBehaviour: {
      title: `Festgelegtes Verhalten`,
      intro: `Aussagen darüber, wie sich <ActionDisplay> verhalten soll, jeweils mit Verweis auf den Test.`,
      verifiedBy: `geprüft durch`,
      statements: {
        translatesLabel: `Rendert das Action-Label aus MowsContext.t.actions[id].`,
        fallsBackToId: `Fällt auf die Action-ID zurück, wenn keine Übersetzung registriert ist.`,
        rendersIcon: `Rendert das vom Action-State zurückgegebene Icon.`,
        exposesDisabledReason: `Exponiert disabledReasonText via title-Attribut.`,
        rendersHotkeys: `Rendert ein KeyComboDisplay pro registriertem Hotkey.`,
      },
    },
    rtl: {
      title: `RTL`,
      body: `Unter dir="rtl" spiegeln Label und nachfolgende Hotkey-Reihe um das Icon.`,
    },
    apiReference: {
      title: `API-Referenz`,
      intro: `Props, die <ActionDisplay> akzeptiert.`,
    },
  },
};
