/**
 * Translation slice for primaryMenu.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to primaryMenu's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface PrimaryMenuTranslation {
    inline: { title: string; description: string };
    fixed: { title: string; description: string };
    doc: {
        installation: {
            title: string;
            commandTab: string;
            manualTab: string;
            manualStep1: string;
            manualStep2: string;
            manualStep3: string;
        };
        usage: { title: string; body: string };
        composition: { title: string; body: string };
        examples: {
            title: string;
            inline: { title: string; description: string };
            fixed: { title: string; description: string };
        };
        definedBehaviour: {
            title: string;
            intro: string;
            verifiedBy: string;
            statements: {
                loginVisibleWhenAuthConfigured: string;
                loginHiddenWhenAuthNotConfigured: string;
                providerWithoutOidcYieldsNoAuth: string;
                dropsLeadingSeparator: string;
                keepsSeparatorWithLogin: string;
                inlineRendersFullWidth: string;
                inlineLoggedOutMenuIcon: string;
                staleSessionTreatedAsLoggedOut: string;
            };
        };
        rtl: { title: string; body: string };
        apiReference: { title: string; intro: string };
    };
}

export const primaryMenuEn: PrimaryMenuTranslation = {
    inline: {
        title: `Inline`,
        description: `Full-width trigger that fits in a sidebar footer or row — clicks open the dropdown above/below the trigger.`
    },
    fixed: {
        title: `Fixed`,
        description: `Pins the trigger to a viewport corner. In a real app it sits on top of every page; the preview uses a positioned wrapper to contain it.`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Command`,
            manualTab: `Manual`,
            manualStep1: `Install the following dependencies:`,
            manualStep2: `Copy and paste the following code into your project.`,
            manualStep3: `Update the import paths to match your project setup.`
        },
        usage: {
            title: `Usage`,
            body: `Mount <PrimaryMenu> exactly once inside <MowsProvider>. It exposes Login / Logout, the language / theme / code-theme pickers, the keyboard-shortcut editor, and the settings modal.`
        },
        composition: {
            title: `Composition`,
            body: `<PrimaryMenu> composes <DropdownMenu> with the picker components and the modal manager. The "fixed" variant pins to a viewport corner; the "inline" variant adapts to a sidebar footer.`
        },
        examples: {
            title: `Examples`,
            inline: {
                title: `Inline`,
                description: `variant="inline" — full-width trigger.`
            },
            fixed: {
                title: `Fixed`,
                description: `Default variant — pins to top-right.`
            }
        },
        definedBehaviour: {
            title: `Defined behaviour`,
            intro: `Statements describing how <PrimaryMenu> is expected to behave, each linked to the test that verifies it.`,
            verifiedBy: `verified by`,
            statements: {
                loginVisibleWhenAuthConfigured: `Shows the Login entry when auth is configured and the user is not signed in.`,
                loginHiddenWhenAuthNotConfigured: `Hides the Login entry entirely when no OIDC config was passed to <MowsProvider>.`,
                providerWithoutOidcYieldsNoAuth: `A real <MowsProvider> mounted without an oidc prop yields authConfigured=false — and no Login entry appears.`,
                dropsLeadingSeparator: `Drops the leading separator above Language when there is no auth section to separate from.`,
                keepsSeparatorWithLogin: `Keeps the separator between Login and Language when the Login entry is visible.`,
                inlineRendersFullWidth: `variant="inline" renders a full-width trigger (no fixed positioning) and shows the user display name next to the avatar when logged in.`,
                inlineLoggedOutMenuIcon: `variant="inline" renders the menu icon only (no text) when logged out — the openMenu label lives on the title attribute.`,
                staleSessionTreatedAsLoggedOut: `A cached authenticated session is treated as logged out when authConfigured=false — neither Login nor Logout entries appear.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `The menu inherits text direction from its ancestor. Wrap in dir="rtl" to mirror the avatar / icon / chevron order in the trigger.`
        },
        apiReference: {
            title: `API Reference`,
            intro: `Props accepted by <PrimaryMenu>.`
        }
    }
};

export const primaryMenuDe: PrimaryMenuTranslation = {
    inline: {
        title: `Inline`,
        description: `Full-width-Trigger für eine Sidebar-Footer-Zeile — Klicks öffnen das Dropdown ober- oder unterhalb des Triggers.`
    },
    fixed: {
        title: `Fixiert`,
        description: `Pinnt den Trigger an eine Viewport-Ecke. In einer echten App liegt er über jeder Seite; die Vorschau verwendet einen positionierten Wrapper.`
    },
    doc: {
        installation: {
            title: `Installation`,
            commandTab: `Befehl`,
            manualTab: `Manuell`,
            manualStep1: `Installiere die folgenden Abhängigkeiten:`,
            manualStep2: `Kopiere den folgenden Code in dein Projekt.`,
            manualStep3: `Passe die Importpfade an dein Projekt an.`
        },
        usage: {
            title: `Verwendung`,
            body: `Mounte <PrimaryMenu> genau einmal innerhalb von <MowsProvider>. Es bietet Login / Logout, Sprache- / Theme- / Code-Theme-Picker, den Tastenkürzel-Editor und den Einstellungsdialog.`
        },
        composition: {
            title: `Komposition`,
            body: `<PrimaryMenu> kombiniert <DropdownMenu> mit den Picker-Komponenten und dem Modal-Manager. Die "fixed"-Variante pinnt an eine Viewport-Ecke; "inline" passt sich einem Sidebar-Footer an.`
        },
        examples: {
            title: `Beispiele`,
            inline: {
                title: `Inline`,
                description: `variant="inline" — Full-width-Trigger.`
            },
            fixed: {
                title: `Fixiert`,
                description: `Standard-Variante — oben rechts angepinnt.`
            }
        },
        definedBehaviour: {
            title: `Festgelegtes Verhalten`,
            intro: `Aussagen darüber, wie sich <PrimaryMenu> verhalten soll, jeweils mit Verweis auf den Test.`,
            verifiedBy: `geprüft durch`,
            statements: {
                loginVisibleWhenAuthConfigured: `Zeigt den Login-Eintrag, wenn Auth konfiguriert ist und der Nutzer nicht angemeldet ist.`,
                loginHiddenWhenAuthNotConfigured: `Blendet den Login-Eintrag komplett aus, wenn keine OIDC-Konfiguration an <MowsProvider> übergeben wurde.`,
                providerWithoutOidcYieldsNoAuth: `Ein echter <MowsProvider> ohne oidc-Prop liefert authConfigured=false — und kein Login-Eintrag erscheint.`,
                dropsLeadingSeparator: `Lässt den führenden Separator über "Sprache" weg, wenn es keinen Auth-Bereich darüber zum Trennen gibt.`,
                keepsSeparatorWithLogin: `Behält den Separator zwischen Login und Sprache, wenn der Login-Eintrag sichtbar ist.`,
                inlineRendersFullWidth: `variant="inline" rendert einen Full-width-Trigger (keine fixed-Positionierung) und zeigt den Anzeigenamen neben dem Avatar, wenn angemeldet.`,
                inlineLoggedOutMenuIcon: `variant="inline" zeigt im abgemeldeten Zustand nur das Menü-Icon (kein Text) — die openMenu-Beschriftung lebt im title-Attribut.`,
                staleSessionTreatedAsLoggedOut: `Eine gecachte authentifizierte Session wird als abgemeldet behandelt, wenn authConfigured=false — weder Login- noch Logout-Eintrag erscheinen.`
            }
        },
        rtl: {
            title: `RTL`,
            body: `Das Menü erbt die Schreibrichtung vom Vorfahren. Ein umgebendes dir="rtl" spiegelt Avatar / Icon / Chevron im Trigger.`
        },
        apiReference: {
            title: `API-Referenz`,
            intro: `Props, die <PrimaryMenu> akzeptiert.`
        }
    }
};
