/**
 * Translation slice for keyComboRecorder.
 *
 * Owns the type and both locale literals for this feature in one
 * place. Edits to keyComboRecorder's strings happen here; the top-level
 * Translation interface and locale files just reference these exports.
 *
 * Generated by scripts/extract-slices.mjs and intentionally kept
 * verbatim of the original inline literal so a reviewer can compare
 * against git history. Future cleanups (sharing repeated doc helper
 * types, dropping fields, etc.) are welcome but separate.
 */

export interface KeyComboRecorderTranslation {
    default: { title: string; description: string };
    doc: {
        installation: {
            title: string;
            commandTab: string;
            manualTab: string;
            manualStep1: string;
            manualStep2: string;
            manualStep3: string;
        };
        usage: { title: string; body: string };
        composition: { title: string; body: string };
        examples: {
            title: string;
            default: { title: string; description: string };
        };
        definedBehaviour: {
            title: string;
            intro: string;
            verifiedBy: string;
            statements: {
                startsIdle: string;
                togglesListening: string;
                capturesCombo: string;
                capturesModifier: string;
                clearResets: string;
            };
        };
        rtl: { title: string; body: string };
        apiReference: { title: string; intro: string };
    };
}

export const keyComboRecorderEn: KeyComboRecorderTranslation = {
    default: { title: `Default`, description: `Click "Start recording" and press any combo on your keyboard — each press is captured and appended to the list. Releasing a modifier on its own (e.g. just Shift) is also captured.` },
    doc: {
        installation: { title: `Installation`, commandTab: `Command`, manualTab: `Manual`, manualStep1: `Install the following dependencies:`, manualStep2: `Copy and paste the following code into your project.`, manualStep3: `Update the import paths to match your project setup.` },
        usage: { title: `Usage`, body: `<KeyComboRecorder> captures live key combos and formats them through the active HotkeyManager, producing strings that round-trip with HotkeyManager.setHotkey() and KeyComboDisplay.` },
        composition: { title: `Composition`, body: `Wire the onCombo callback to whatever consumes the combo strings — a settings editor, a quick demo, or a debugger. The component renders its own start / stop / clear buttons and a history list out of the box.` },
        examples: { title: `Examples`, default: { title: `Default`, description: `Start recording, then press a combo. The last captured combo is shown in the harness state panel.` } },
        definedBehaviour: {
            title: `Defined behaviour`, intro: `Statements describing how <KeyComboRecorder> is expected to behave, each linked to the test that verifies it.`, verifiedBy: `verified by`,
            statements: {
                startsIdle: `Renders the start button and hint copy before recording.`,
                togglesListening: `Flips to a stop button and a listening indicator once recording starts.`,
                capturesCombo: `Captures a real combo as a list entry and fires onCombo.`,
                capturesModifier: `Captures a standalone modifier release (Shift down → Shift up with no key in between).`,
                clearResets: `Clear button empties the captured-combo list.`
            }
        },
        rtl: { title: `RTL`, body: `Layout flips under dir="rtl"; combos are direction-agnostic.` },
        apiReference: { title: `API Reference`, intro: `Props accepted by <KeyComboRecorder>.` }
    }
};

export const keyComboRecorderDe: KeyComboRecorderTranslation = {
    default: { title: `Standard`, description: `Klicke „Aufzeichnung starten“ und drücke eine beliebige Kombination auf der Tastatur — jeder Tastendruck wird erfasst und an die Liste angehängt. Auch ein allein losgelassener Modifier (z. B. nur Umschalt) wird erfasst.` },
    doc: {
        installation: { title: `Installation`, commandTab: `Befehl`, manualTab: `Manuell`, manualStep1: `Installiere die folgenden Abhängigkeiten:`, manualStep2: `Kopiere den folgenden Code in dein Projekt.`, manualStep3: `Passe die Import-Pfade an deine Projektstruktur an.` },
        usage: { title: `Verwendung`, body: `<KeyComboRecorder> erfasst Tastenkombinationen live und formatiert sie über den aktiven HotkeyManager — die erzeugten Strings sind direkt mit HotkeyManager.setHotkey() und KeyComboDisplay kompatibel.` },
        composition: { title: `Komposition`, body: `Verbinde den onCombo-Callback mit dem, was die Combo-Strings konsumiert — ein Einstellungs-Editor, eine kurze Demo oder ein Debugger. Die Start- / Stop- / Leeren-Schaltflächen und die Verlaufsliste sind bereits enthalten.` },
        examples: { title: `Beispiele`, default: { title: `Standard`, description: `Starte die Aufzeichnung und drücke eine Kombination. Die zuletzt erfasste Combo wird im Harness-State-Panel angezeigt.` } },
        definedBehaviour: {
            title: `Definiertes Verhalten`, intro: `Aussagen darüber, wie sich <KeyComboRecorder> verhalten soll — jede verlinkt mit dem Test, der sie verifiziert.`, verifiedBy: `verifiziert durch`,
            statements: {
                startsIdle: `Zeigt vor dem Aufzeichnen die Start-Schaltfläche und den Hinweistext.`,
                togglesListening: `Wechselt nach dem Start zur Stop-Schaltfläche und blendet den Lausch-Indikator ein.`,
                capturesCombo: `Erfasst eine echte Combo als Listeneintrag und feuert onCombo.`,
                capturesModifier: `Erfasst einen allein losgelassenen Modifier (Umschalt-Druck → Umschalt-Loslassen ohne Taste dazwischen).`,
                clearResets: `Die „Leeren“-Schaltfläche leert die Liste der erfassten Combos.`
            }
        },
        rtl: { title: `RTL`, body: `Layout wird unter dir="rtl" gespiegelt; Combos sind richtungs-agnostisch.` },
        apiReference: { title: `API-Referenz`, intro: `Props, die <KeyComboRecorder> akzeptiert.` }
    }
};
